const mangaList=[
    ["swordArtOnline",{
        title: "Sword Art Online",
        originalTitle: "ソードアート・オンライン",
        otherTitle: false,
        class: "Shonen",
        genre: ["Action","Aventure","Comédie","Romance","Sciences-fiction"],
        theme: ["Adolescence","Amour","Jeux-vidéo","Monde virtuel"],
        VO: 23,
        statusVO: "En cours",
        VF: 23,
        statusVF: "En cours",
        origine: "Japon - 2010",
        sortieVF: "2014",
        editeur: "Ototo",
        auteur: "Kawahara Reki - Nakamura Tamako",
        synopsis: "Bienvenue dans le jeu en ligne Sword Art Online. Kirito adore les MMORPG et fait partie des 10.000 privilégiés ayant réussi à se procurer ce jeu qui fonctionne avec un système de réalité virtuelle directe. Ainsi, le joueur met un casque et entre dans le jeu, maniant son avatar avec sa pensée. Kirito avait déjà testé la version Bêta et se débrouille mieux que d'autres. Sword Art fait la part belle aux combats et ne possède pas de magie. Mais tous paniquent quand ils apprennent qu'ils ne peuvent plus sortir du jeu. La seule façon de se déconnecter est de le finir en arrivant au niveau 99. De plus, si le joueur perd tous ses points de vie, il meurt également dans la réalité ! Quel est le but du créateur du jeu ?",
        image: "asset/SwordArtOnline/AincradT1.jpg",
        background: "asset/SwordArtOnline/Bg.jpg",
        tomes:[
            ["Aincrad",[
                {image: "asset/SwordArtOnline/AincradT1.jpg" , synopsis: `En 2022, Kirito, un adolescent sans histoire, se retrouve piégé avec 10 000 autres joueurs dans un jeu en réalité augmentée massivement multijoueurs : Sword Art Online. Pour regagner leur liberté, les joueurs devront compléter les 100 étages qui composent l'Aincrad, leur prison virtuelle. Mais le moindre faux pas pourrait être fatal, puisqu'un Game Over dans le jeu entraînera une mort réelle. Kirito, le joueur solo, se lance dans une course effrénée pour sa survie, dans un monde où l'art de l'épée dicte la loi des plus forts.`},
                {image: "asset/SwordArtOnline/AincradT2.jpg" , synopsis: `« Vous êtes bien dans un jeu vidéo, mais vous n'êtes plus là pour jouer. ». Deux ans après le début de la partie, seulement six mille survivants... Kirito est l'un d'eux. Il a décidé de conquérir en « solo » les cent étages qui le mèneront au combat final et qui lui permettra de regagner sa liberté. Mais c'est sans compter sur l'obstination d'Asuna, une habile épéiste avec qui il va devoir s'allier. Démarre alors une course effrénée pour survivre dans un monde où l'art de l'épée dicte la loi. Fin du premier chapitre Aincrad de Sword Art Online.`},
            ]],["Fairy Dance",[
                {image: "asset/SwordArtOnline/FairyDanceT1.jpg" , synopsis: `Kazuto Kirigaya, alias Kirito, est revenu sain et sauf d'Aincrad, mais Asuna ne s'est toujours pas réveillée de son coma. Alors qu'il lui rend visite à l'hôpital, il apprend que Nobuyuki Sugô compte l'épouser malgré son état. Peu après, Agil lui montre l'image troublante d'un avatar ressemblant étrangement à Asuna, apparemment prisonnière d'un nouveau VRMMO : ALfheim Online. Convaincu qu'il s'agit bien d'elle, Kirito décide de replonger dans la réalité virtuelle pour la retrouver et découvrir ce qui se cache derrière ce nouveau jeu.`},
                {image: "asset/SwordArtOnline/FairyDanceT2.jpg" , synopsis: `Kirito s'engouffre à l'intérieur du VRMMO « Alfheim Online » pour atteindre le sommet de l'Arbre du monde. Il y rencontre une Sylphide du nom de Leafa, qui accepte de l'y accompagner... Cependant, Leafa n'est en réalité, rien d'autre que la propre sœur de Kazuto, Suguha. Cette dernière éprouve secrètement des sentiments pour celui. Ils poursuivent leur route ensemble vers l' « Arbre du monde » sans connaître le destin qui les lie, ni celui qui les attend...`},
                {image: "asset/SwordArtOnline/FairyDanceT3.jpg" , synopsis: `Kirito, Yui et Lyfa arrivent au pied de l'Arbre du Monde où est retenue Asuna. Yui ressantant fortement l'ID d'Asuna en haut de l'arbre, elle en informe Kirito. Celui-ci, plus résolu que jamais à sauver Asuna, se lance alors seul à l'assaut de la Grande Quête, que personne n'a jamais réussi à accomplir, mais qui constitue le seul moyen de se rendre au sommet de l'arbre.`},
            ]],["Phantom Bullet",[
                {image: "asset/SwordArtOnline/PhantomBulletT1.jpg" , synopsis: `Le volume débute sur un bref rappel des événements de l'arc Aincrad avant de nous plonger directement dans l'univers de GGO via Sinon. Le tournoi du jeu, Bullet of Bullets, est sur le point de débuter lorsqu'un des favoris, Zexceed, disparaît mystérieusement. D'après certains témoins, un étrange individu lui aurait tiré dessus à travers un écran en prétendant le tuer dans la vraie vie. Coïncidence troublante, Zexceed s'est déconnecté peu après, en pleine interview. Kirito est alors choisit par Kikuoka Seijirô pour mener l'enquête de l'intérieur.`},
                {image: "asset/SwordArtOnline/PhantomBulletT2.jpg" , synopsis: `Afin de mener l'enquête qui lui a été confié, Kirito a converti son avatar afin de pouvoir jouer à GGO. Une fois dans le jeu, il a fait la connaissance de Sinon, qui lui a indiqué comment s'inscrire au tournoi. En effet, Kirito est persuadé que Death Gun va profiter du tournoi pour faire de nouvelles victimes et il compte bien l'arrêter avant.`},
                {image: "asset/SwordArtOnline/PhantomBulletT3.jpg" , synopsis: `Alors que la fin du tournoi Bullet of Bullets approche, Kirito et Sinon se trouvent face au mystérieux assassin qui, comme le jeune épéiste, s'avère être un survivant de SAO.`},
                {image: "asset/SwordArtOnline/PhantomBulletT4.jpg" , synopsis: `Kirito a désormais la conviction que Death Gun ne tue pas directement les joueurs dans le jeu, mais qu'il utilise une autre méthode. Ayant l'intuition que Sinon est en danger, il se précipite au secours de cette dernière.`,}
            ]],["Calibur",[
                {image: "asset/SwordArtOnline/Calibur.jpg" , synopsis: `Après avoir résolu l'affaire "Death Gun", Kirito retourne sur ALO afin d'obtenir l'épée la plus puissante du jeu : la légendaire Excalibur. Accompagné d'Asuna, Klein, Lisbeth, Lyfa, Silica et Sinon, qui s'est créée un avatar pour pouvoir jouer avec le groupe, il se lance donc dans une série de quête basées sur la mythologie nordique.`},
            ]],["Mother Rosario",[
                {image: "asset/SwordArtOnline/MothersRosarioT1.jpg" , synopsis: `Depuis quelques temps, un spriggan surnommé Zekken (épée absolue) fait beaucoup parler de lui sur ALO. En effet, ce joueur serait invincible et même Kirito ne serait pas parvenu à le vaincre. Cela pique l'intérêt d'Asuna qui décide de tenter sa chance. C'est ainsi qu'elle rencontre Yuuki, une jeune fille qui lui rappelle beaucoup Kirito et qui, derrière d'impressionnantes capacités, cache un lourd secret.`},
                {image: "asset/SwordArtOnline/MothersRosarioT2.jpg" , synopsis: `Asuna a temporairement rejoint la guilde de Yuuki, les Sleeping Knight, et a entrepris de les aider à accomplir leur objectif : vaincre un boss avec seulement 7 personnes, afin de graver tous leurs pseudonymes sur le Kenshi no Hi, le Mur des Épéistes.`},
                {image: "asset/SwordArtOnline/MothersRosarioT3.jpg" , synopsis: `Alors qu'elle découvre le secret de Yûki, Asuna décide de s'impliquer de plus en plus auprès de la jeune fille et de l'aider à réaliser ses rêves.`},
            ]],["Ordinal Scale",[
                {image: "asset/SwordArtOnline/OrdinalScaleT1.jpg" , synopsis: `Ordinal Scale est le jeu le plus populaire auquel il est possible de jouer grâce à l'Augma. Asuna, Klein et leurs amis en sont fans et adorent participer aux events. Kirito, de son côté, est plus réservé. Il faut dire qu'OS est beaucoup plus physique que les autres VRMMORPG et il manque cruellement d'entraînement.`},
                {image: "asset/SwordArtOnline/OrdinalScaleT2.jpg" , synopsis: `Alors qu'elle participe à un événement d'Ordinal Scale proposant de combattre d'anciens boss issus de SAO, Asuna perd subitement la mémoire ! Elle se souvient de sa famille, de ses amis, de sa relation avec Kirito, mais elle a tout oublié des deux années passées dans le jeu mortel. Intrigué, Kirito décide d'enquêter.`},
                {image: "asset/SwordArtOnline/OrdinalScaleT3.jpg" , synopsis: `Après avoir joué à Ordinal Scale un peu plus sérieusement, Kirito découvre les raisons de l'amnésie d'Asuna ainsi que l'objectif d'Eiji et de son complice. Il décide alors d'intervenir pour que ses amis retrouvent leurs souvenirs.`},
                {image: "asset/SwordArtOnline/OrdinalScaleT4.jpg" , synopsis: `Tout ce qui se passe d'étrange dans Ordinal Scale semble lié à la mystérieuse AI Yuna, dont le premier grand concert aura lieu prochainement. Kirito décide de s'y rendre afin de mettre un terme aux ambitions d'Eiji et de ses complices.`},
                {image: "asset/SwordArtOnline/OrdinalScaleT5.jpg" , synopsis: `Le mystérieux lien entre Yuna et Eiji se dévoile, tout comme le but réel du créateur d'Ordinal Scale. Mais est-il encore possible de l'arrêter?`},
            ]],["Project Alicization",[
                {image: "asset/SwordArtOnline/ProjectAlicizationT1.jpg" , synopsis: `Invité à tester une nouvelle machine de réalité virtuelle, Kirito est agressé par un ancien membre de Laughing Coffin et se retrouve piégé dans un mystérieux monde appelé l'Underworld. Incapable de rejoindre la réalité, il y rencontre Eugeo, un jeune entailleur marqué par la disparition de son amie d'enfance, Alice. Ensemble, ils partent dans une quête qui les mènera bien au-delà de leur village. Mais quels secrets cache l'Underworld, et que se trame-t-il dans le monde réel ? La plus grande aventure de l'Épéiste noir ne fait que commencer.`},
                {image: "asset/SwordArtOnline/ProjectAlicizationT2.jpg" , synopsis: `Après avoir été agressé, Kirito s'éveille dans l'Underworld sans vraiment comprendre ce qui lui est arrivé. Là, il retrouve Eugeo, qui a désormais son âge mais ne se souvient pas de lui.`},
                {image: "asset/SwordArtOnline/ProjectAlicizationT3.jpg" , synopsis: `Après s'être fait quelques frayeurs, Kirito et Eugeo ont enfin réussi à venir à bout de la Tâche de ce dernier. Ils peuvent désormais quitter le village et partir à la recherche d'Alice.`},
                {image: "asset/SwordArtOnline/ProjectAlicizationT4.jpg" , synopsis: `Arrêtés par nulle autre qu'Alice, Kirito et Eugeo sont emmenés à la cathédrale où réside l'Administrateur et l'élite de l'empire humain : les Chevaliers Intègres.`},
                {image: "asset/SwordArtOnline/ProjectAlicizationT5.jpg" , synopsis: `Afin de comprendre ce qui est arrivé à Alice, Kirito et Eugeo s'infiltrent au cœur de la cathédrale afin de trouver l'Administrateur. Mais l'ascension est semée d'embûches et le duo doit affronter de nombreux Chevaliers Intègres.`},
            ]],
        ],
    }],
    ["TonikakuKawaii",{
        title: "Tonikaku Kawaii",
        originalTitle: "トニカクカワイイ",
        otherTitle: "Fly Me to The Moon",
        class: "Shonen",
        genre: ["Comédie","Romance","Slice of Life","Mystère"],
        theme: ["Adolescence","Amour","Mariage"],
        VO: 8,
        statusVO: "En cours",
        VF: 36,
        statusVF: "En cours",
        origine: "Japon - 2018",
        sortieVF: "2022",
        editeur: "noeve grafx",
        auteur: "Hata Kenjiro",
        synopsis: `Yuzaki Nasa sera sans conteste la personne qui atteindra la vitesse de la lumière plus rapidement que la NASA, enfin c'est ce qu'il affirme. En effet, ce collégien extrêmement studieux s'est juré de devenir quelqu'un d'important pour ne plus être le sujet de moqueries de ses camarades du fait de son prénom qui se prononce "NASA", faisant directement référence à l'agence spatiale américaine.
Un jour, en rentrant chez lui après avoir prouvé qu'il avait les capacités pour entrer dans les meilleurs lycées du pays en arrivant en première position lors des examens de fin d'année, il croise par hasard une jeune fille dont il tombe tout de suite sous le charme.
Ne faisant pas attention à la route il se fait percuter par un camion mais sera secouru par cette dernière avant de le laisser au soin du camionneur.
Faisant abstraction de ses blessures, Yuzaki part à la poursuite de la jeune demoiselle en espérant la retrouver afin de lui déclarer son amour et qu'elle accepte de sortir avec lui. Chose qu'elle accepta à condition que les deux se marient. Sans aucune hésitation il répond « Oui ! » avant de s'effondrer de douleur.
Après avoir survécu à ses blessures et s'être réveillé de son coma, Yuzaki n'a plus vraiment gout à la vie. Il arrête ses études, accumule des jobs à temps partiel et quitte le domicile familial. Tout ce qu'il souhaite, c'est de revoir la fille dont il est tombé amoureux.
Alors qu'il entame sa 19e année, un personne vient sonner à la porte de chez lui. Il ne s'agit de nul autre que la mystérieuse jeune fille qui vient lui faire tenir la promesse qu'ils se sont faites il y a quelque années de cela. Ainsi commence la vie à deux de nos jeunes mariés !`,
        image: "asset/TonikakuKawaii/T1.jpg",
        background: "asset/TonikakuKawaii/Bg.jpg",
        tomes: [false,[
            {image: "asset/TonikakuKawaii/T1.jpg" , synopsis: `Depuis le jour où ses parents l'ont nommé, Nasa Yuzaki se sent connecté à l'espace... qu'il le veuille ou non. Ses efforts pour surpasser le programme spatial dévient de leur objectif lorsqu'un accident lui fait rencontrer Tsukasa, une mystérieuse fille aux pouvoirs étranges. Est-ce une extraterrestre, une déesse de la lune ou autre chose ? Comme elle insiste pour l'épouser, Nasa aura de nombreuses occasions de le découvrir !`},
            {image: "asset/TonikakuKawaii/T2.jpg" , synopsis: `Maintenant que Nasa et Tsukasa sont mariés, il est temps pour lui de rencontrer sa famille. Malheureusement pour lui, cela signifie se faire kidnapper par la sœur surprotectrice de Tsukasa, Chitose, et ses servantes de combat. La vie de Nasa s'arrêtera-t-elle avant même qu'il ait embrassé sa nouvelle femme ? Ou qu'il ait choisi une bague ? Ou, plus important encore, qu'il ait découvert quels sont ses films préférés ?`},
            {image: "asset/TonikakuKawaii/T3.jpg" , synopsis: `Je passerai ma vie à lui prouver mon amour. Les jeunes mariés coulent des journées paisibles dans leur minuscule appartement, mais Nasa semble avoir oublié un léger détail... d'ordre parental ! Un détail qui amène le couple à prendre la route vers la ville de Nara. Un premier voyage en amoureux... n'est-ce pas là le début de leur lune de miel ?! Quelles suprises attendent Nasa et Tsukasa en chemin ?!`},
            {image: "asset/TonikakuKawaii/T4.jpg" , synopsis: `Tsukasa et Nasa sont hébergés chez les Arisugawa le temps de trouver un nouveau logement... Grâce à la générosité de ses voisines, le jeune couple peut prendre le temps de profiter d’une vie maritale remplie d’amour ! Mais ce bonheur tout neuf soulève des suspicions dans l’entourage de Nasa... Voilà que Tsukasa est mise à l’épreuve!`},
            {image: "asset/TonikakuKawaii/T5.jpg" , synopsis: `La lune de miel de Nasa et Tsukasa touche à sa fin... mais une mauvaise surprise les attend à leur retour ! Alors que leur vie de couple débute à peine, il leur reste beaucoup à apprendre l'un sur l'autre... et encore beaucoup de premières fois à vivre ensemble.`},
            {image: "asset/TonikakuKawaii/T6.jpg" , synopsis: `La famille Yuzaki accueille un adorable chaton ! Ginga, le cousin de Nasa, vient lui rendre visite car il a un service à lui demander ! Voilà comment un personnage mignon de plus fait son entrée dans la famille ! ♡ Dans la suite du tome, Nasa et Tsukasa vont passer une journée en amoureux dans un parc d'attraction !`},
            {image: "asset/TonikakuKawaii/T7.jpg" , synopsis: `Nos tourtereaux se retrouvent séparés pour la première fois ?! Voici venue la première épreuve pour notre couple fusionnel. Nasa doit retourner travailler une journée entière chez un ancien employeur. Tsukasa se sent bien seule pour leur première longue séparation. Bien entendu, ce volume va ensuite déborder d'amour !`},
            {image: "asset/TonikakuKawaii/T8.jpg" , synopsis: `Nasa et Tsukasa vont prendre leur bain ensemble ! Notre petit couple se retrouve aux sources chaudes de Kusatsu. Un voyage plein d'amour et de bonheur teinté de quelques petits soucis. Car ils vont se baigner ensemble. Un moment à la fois heureux et gênant !`},

        ]]
    }],
    ["DeathNote",{
        title: "Death Note",
        originalTitle: "デスノート",
        otherTitle: false,
        class: "Seinen",
        genre: ["Drame","Mystère","Psychologique","Surnaturel","Tragique"],
        theme: ["Détective","Mort","Police","Shinigami"],
        VO: 12,
        statusVO: "Termnié",
        VF: 12,
        statusVF: "Terminé",
        origine: "Japon - 2003",
        sortieVF: "2007",
        editeur: "Kana",
        auteur: "Ohba Tsugumi - Obata Takeshi",
        synopsis: `Light Yagami est un jeune lycéen de 17 ans qui possède toutes les qualités pour devenir un brillant policier comme son père, mais il s'ennuie. Les cours lui semblent trop simple, et la vie trop ennuyeuse. Un jour, il trouve le Death Note d'un Shinigami (un Dieu de la Mort). Il y est écrit que chaque nom de personne inscrit provoquera la mort de celle-ci, par crise cardiaque, ou par accident au choix de l'utilisateur.

Tout d'abord, Light n'y croit pas, puis il y voit une excellente occasion de débarrasser le monde des malfrats, assassins et autres bandits. Une intention que les gouvernements verront bientôt comme une menace. Ils feront alors appel à L, un célèbre détective, pour démasquer celui que ses fans appellent Kira.`,
        image: "asset/DeathNote/T1.jpg",
        background: "asset/DeathNote/Bg.jpg",
        tomes: [false,[
            {image: "asset/DeathNote/T1.jpg" , synopsis: `Light Yagami, est un lycéen de 17 ans, qui obtient toujours les meilleurs résultats à l'école. Un jour, il trouva le Death Note, un cahier où, en écrivant le nom d'une personne tout en ayant son visage en tête, on peut décider des circonstances de sa mort ainsi que de l'heure de son decès.`},
            {image: "asset/DeathNote/T2.jpg" , synopsis: `Le FBI arrive au Japon pour mener l'enquête sur l'affaire Kira. Light qui fait partie des principaux suspects, il devra alors trouver tout les moyens possible pour ne plus l'être !`},
            {image: "asset/DeathNote/T3.jpg" , synopsis: `La résidence des Yagami est placée sous surveillance vidéo et audio, Light, aussi malin qu'il soit, réussit à tromper L, et continue ses activités ! Par la suite, un message d'un faux Kira est envoyé à une chaine de télévision, Light pense à une mauvaise blague.`},
            {image: "asset/DeathNote/T4.jpg" , synopsis: `La résidence des Yagami est placée sous surveillance vidéo et audio, Light, aussi malin qu'il soit, réussit à tromper L, et continue ses activités ! Par la suite, un message d'un faux Kira est envoyé à une chaine de télévision, Light pense à une mauvaise blague.`},
            {image: "asset/DeathNote/T5.jpg" , synopsis: `Light est enfermé à sa demande dans le but de prouver qu'il n'est pas Kira, plusieurs jours passent, et les meurtres reprennent. L est donc forcé de les faire sortir, mais à une seul condition ! Malgré la libération de Light, il sera toujours sous surveillance avec Misa.`},
            {image: "asset/DeathNote/T6.jpg" , synopsis: `Un nouveau Kira apparaît, L aurait déjà un suspect, il appartiendrait au groupe Yotsuba, qu'il va placer sous surveillance. A la demande de L, Amane Misa devra infiltrer le groupe Yotsuba, et ainsi découvrir qui est Kira. Elle fera la rencontre de Rem, son ancien dieu de la mort, et lui dira qui est Kira ! C'est alors que L et les autres commencent une course poursuite contre Higuchi.`},
            {image: "asset/DeathNote/T7.jpg" , synopsis: `La police est parvenue à encercler Higuchi, l'actuel possesseur du Death Note. Light parviendra-t-il à remettre la main sur le cahier ?! Va-t-il réussir à mener à bien le plan qu'il avait mis au point avant d'être placé sous surveillance ?!`},
            {image: "asset/DeathNote/T8.jpg" , synopsis: `Grâce à la mort de L, le monde idéal voulu par Light est en train de se construire. Mais les deux garçons désignés pour succéder à L, Near et Mello, entrent en scène. Une lutte commence alors pour la possession des Death Notes ! Mello enlève Sayu, la sœur de Light, et exige de procéder à un échange de cahiers !`},
            {image: "asset/DeathNote/T9.jpg" , synopsis: `Il n'y a plus que les membres du bureau d'enquête qui soient en mesure d'agir pour récupérer le cahier que possède Mello. Light a un plan pour les faire passer à l'action... C'est alors que Sôichirô Yagami, le père de Light, réintègre le bureau d'enquête. Il entend, en effet, jouer le rôle principal dans le plan de son fils !!`},
            {image: "asset/DeathNote/T10.jpg" , synopsis: `Le Q. G. du S. P. K. est encerclé par les partisans de Kira, mais Near réussit à s'évader d'une façon surprenante ! Les réflexions de Near le poussent dorénavant à concevoir de lourds soupçons à l'égard du second L, alias Light, ce qui n'est pas sans incidence sur le bureau d'enquête japonais...`},
            {image: "asset/DeathNote/T11.jpg" , synopsis: `Par l'intermédiaire de Kiyomi Takada, Light communique avec Mikami à qui il a remis son cahier de la Mort. De son côté, Near décide de se rendre au Japon. Les différents acteurs de l'intrigue sont maintenant tous réunis dans l'archipel... Quelle direction les événements vont-ils prendre ?`},
            {image: "asset/DeathNote/T12.jpg" , synopsis: `Le dénouement est proche pour Light et Near qui vont enfin s'affronter ! Quelles stratégies ces deux esprits hors du commun ont-ils donc élaborées pour prendre le dessus sur leur adversaire ?`},
        ]]
    }],
    ["LookBack",{
        title: "Look Back",
        originalTitle: "ルックバック",
        otherTitle: false,
        class: "Shonen",
        genre: ["Drame","School Life","Slice of Life"],
        theme: ["Adolescence","Amitié","Solitude"],
        VO: 1,
        statusVO: "Termnié",
        VF: 1,
        statusVF: "Terminé",
        origine: "Japon - 2021",
        sortieVF: "2022",
        editeur: "Shueisha",
        auteur: "Fujimoto Tatsuki",
        synopsis: `Fujino, adolescente surdouée, a une confiance absolue en son talent. Kyômoto, elle, se terre dans sa chambre et pratique sans relâche. Deux jeunes filles d'une même ville de province, qu'une passion fervente pour le dessin va rapprocher et unir par un lien indéfectible...`,
        image: "asset/LookBack/T1.jpg",
        background: "asset/LookBack/Bg.jpg",
        tomes: false,
    }],
    ["TheAncientMagusBride",{
        title: "The Ancient Magus Bride",
        originalTitle: "魔法使いの嫁",
        otherTitle: "Mahō Tsukai no Yome",
        class: "Shonen",
        genre: ["Aventure","Drame","Fantastique","Mystère","Slice of Life","Surnaturel"],
        theme: ["Dragons","Magie","Quotidien","Sorcellerie"],
        VO: 24,
        statusVO: "En cours",
        VF: 23,
        statusVF: "En cours",
        origine: "Japon - 2014",
        sortieVF: "2015",
        editeur: "komikku",
        auteur: "Yamazaki Kore",
        synopsis: `Chise Hatori a le pouvoir spécial de voir des choses que d'autres ne peuvent voir. Un magicien étrange, dont la tête est un crâne tout aussi bizarre, est le premier à déceler le don de Chise. Il achètera cette jeune fille aux enchères au Japon pour la modique somme de 5 millions de livres sterling. De retour ensemble en Angleterre, Chise deviendra l'apprenti du magicien et est supposée l'épouser dans l'avenir. Le pouvoir spécial de Chise est appelé "Slay Vega" et permet de produire ainsi que d'émettre énormément de magie. Un pouvoir rare et de valeur qu'elle va devoir apprendre à maîtriser pour survivre car être un "Slay Vega" demande beaucoup d'énergie et peut conduire à la mort...`,
        image: "asset/TheAncientMagusBride/T1.jpg",
        background: "asset/TheAncientMagusBride/Bg.jpg",
        tomes: [false,[
            {image: "asset/TheAncientMagusBride/T1.jpg" , synopsis: `Chisé Hatori a 15 ans. Elle n'a ni famille, ni talent particulier, ni aucun espoir dans la vie. Un jour, elle est vendue à un sorcier, un non-humain dont l'existence remonte à la nuit des temps... Il la prend sous son aile pour faire d'elle sa disciple et lui annonce qu'à terme, elle deviendra son épouse. Alors, les aiguilles qui semblaient à tout jamais figées dans son cœur se mettent à tourner de nouveau, petit à petit...`},
            {image: "asset/TheAncientMagusBride/T2.jpg" , synopsis: `Alors que Chisé et Elias ont été envoyés en mission pour le compte de l'Eglise, ils se font brusquement attaquer par un mystérieux magicien et son apprentie. Quel peut bien être leur objectif ? Et quelle est la vraie nature du pouvoir de Chisé, que tout le monde appelle «Slay Vega» ? De sa plume élégante, Koré Yamazaki nous offre le tome deux de cette romance improbable entre deux êtres que tout oppose.`},
            {image: "asset/TheAncientMagusBride/T3.jpg" , synopsis: `Les Slay Vega disposent d'un pouvoir immense… Mais en contrepartie, ils portent un funeste destin sur leurs épaules. Chisé se retrouve aux prises avec le magicien à l'origine de la souillure d'Ulthar ! Blessée, elle tombe inconsciente… C'est alors qu'Elias révèle la puissance associée à son ancien surnom, celle du Pilum Murialis !`},
            {image: "asset/TheAncientMagusBride/T4.jpg" , synopsis: `Chisé est de retour aux pays des dragons, mandée par Lindel, leur gardien. Alors qu'elle se donne du mal pour se tailler une baguette, Lindel se met à raconter un pan d'un lointain passé. Un souvenir d'Elias... Quelle sera la réaction de Chisé face à son récit ? Sa relation particulière avec le non-humain va-t-elle être remise en question ?`},
            {image: "asset/TheAncientMagusBride/T5.jpg" , synopsis: `À force de combattre son lourd passé, Chisé décide d'aller de l'avant en compagnie d'Elias. Ce dernier, de son côté, apprend petit à petit à éprouver de la compassion et s'éveille aux beautés du monde. Un soir, la Leanan Sidhe, visiblement paniquée, vient chercher secours auprès de Chisé... Que pourra-t-elle faire pour l'aider ?`},
            {image: "asset/TheAncientMagusBride/T6.jpg" , synopsis: `À la croisée des sentiers où cheminent les humains et les êtres surnaturels, Chisé a décidé de suivre sa propre route, à son rythme. Après avoir reçu une lettre, elle se rend à Londres en secret, où elle retrouve Alice, l'apprentie de Renfred. Les voilà toutes deux en train d'arpenter les rues bondées... mais dans quel but ?`},
            {image: "asset/TheAncientMagusBride/T7.jpg" , synopsis: `Face à Chisé, qui s'est fait sa première amie "normale" et commence à changer, Elias est envahi par un sentiment qu'il ne s'explique pas. Alors qu'ils évoluent tous deux, chacun de leur côté, et que le sorcier a peur de voir s'éloigner sa disciple, Cartaphilus s'en prend cette fois-ci à Lindel en envoyant des braconniers au pays des dragons. Quel est l'objectif du magicien errant condamné à la souffrance éternelle ?`},
            {image: "asset/TheAncientMagusBride/T8.jpg" , synopsis: `Un plan ourdi par Cartaphilus, le magicien errant, pousse un dragon à perdre la tête… Alors qu'il s'enfuit dans le ciel de Londres, Chisé s'élance pour le sauver et doit pour cela payer une lourde compensation… La voilà maudite par trois fois : une fois par sa mère, une fois par sa naissance et une fois par le dragon. Il est temps d'affronter ceux qui jusqu'à maintenant détournaient les yeux, ce qui risque de fortement ébranler le cours de l'histoire.`},
            {image: "asset/TheAncientMagusBride/T9.jpg" , synopsis: `"Je ne peux plus rester avec vous…" Pour lever la malédiction qui pèse sur Chisé, Elias a dû faire un choix que la jeune fille ne cautionne pas. C'est la rupture… Elle décide de conclure un marché avec Cartaphilus, le magicien errant, mais que pourra-t-il lui apporter? Des vies presque terminées, des maléfices immuables, des routes qui se séparent… Quel avenir pour l'humaine et le non-humain ?`},
            {image: "asset/TheAncientMagusBride/T10.jpg" , synopsis: `Tout n'est pas parfait. Mais au moins, Chisé a réussi à s'accepter et à comprendre un peu mieux Elias. Cartaphilus est tombé dans un profond sommeil et alors que la situation s'est apaisée, les magiciens viennent voir la jeune sorcière pour lui proposer d'intégrer le collège de magie. Voilà Chisé et Elias précipités dans un lieu tout nouveau pour eux, dissimulé dans les sous-sols de la British Library, là où les apprentis magiciens étudient, découvrent et grandissent… Mais le non-humain va-t-il trouver sa place parmi tant d'humains ?`},
            {image: "asset/TheAncientMagusBride/T11.jpg" , synopsis: `Chisé est devenue auditrice libre au collège. De son côté, Elias a fini par accepter les changements de la jeune fille et commence à évoluer lui-même. Tandis que Chisé se fait de nouveaux amis, on découvre l'existence des "Sept boucliers" et l'Église entre à présent dans la partie. C'est le moment que choisit Rahab pour refaire son apparition. Quelle influence ces nouvelles fréquentations vont-elles avoir sur Elias et Chisé ?`},
            {image: "asset/TheAncientMagusBride/T12.jpg" , synopsis: `Le collège est un établissement qui regroupe plein d'apprentis magiciens. Ils suivent les mêmes cours, dorment sur place dans le dortoir et se connaissent depuis des années. Chisé va donc devoir trouver sa place parmi eux. Son quotidien est devenu beaucoup plus tranquille qu'auparavant. Elle continue d'aller de l'avant, entre les leçons et ses nouveaux camarades qu'elle apprend à connaître. Comme cette rumeur qui court sur Lucy, sa colocataire...`},
            {image: "asset/TheAncientMagusBride/T13.jpg" , synopsis: `Tout le monde a ses secrets. Chisé tout comme Zoey Ivy. Mais son secret a lui a été découvert et pour le protéger, les cinq élèves présents ont noué un pacte qui les empêche de parler. Plus Chisé se rapproche de ses camarades du collège, plus elle découvre le passé des différentes familles de magiciens. Mais personne ne sait ce que l'avenir leur réserve... Un jour, Chisé et le reste de sa classe partent en camp de survie dans les Highlands, une terre où les êtres de la nuit s'en donnent à cœur joie. Et comme d'habitude...`},
            {image: "asset/TheAncientMagusBride/T14.jpg" , synopsis: `Lucy s'est fait attaquer pendant que la classe était partie en camping. Simeon, un professeur, a été retrouvé inconscient dans l'enceinte du lycée. Alors que deux personnes ont déjà été victimes de malaise, les bibliothécaires découvrent qu'un livre interdit a été dérobé. Il s'agit d'une copie du "Testament de Carnamagos", un ouvrage qu'Elias avait demandé à lire par le passé... Alors que le lien peine à être établi entre les deux états de fait, Chisé se fait attaquer par deux hybrides chargés d'éliminer les survivants des Webster...`},
            {image: "asset/TheAncientMagusBride/T15.jpg" , synopsis: `Après leur rencontre inopinée avec un professeur dans la tour abandonnée et la découverte de plusieurs mystères, Chisé et ses camarades commencent à changer de gré ou de force. Alors que certains se lient davantage et d'autres se déchirent un peu plus, la copie du grimoire "Le testament de Carnamagos" est toujours introuvable. Pour éviter que d'autres drames se produisent, la directrice décide de sceller le collège par magie pendant quelque temps...`},
            {image: "asset/TheAncientMagusBride/T16.jpg" , synopsis: `Le grimoire volé est toujours à l'intérieur du collège. Pour quelle raison le coupable est-il resté sur place ? Quel est son véritable but ? Hélas, nul ne le sait. Confinés dans l'établissement, Chisé et les autres élèves se rapprochent petit à petit, mais l'ombre de la discorde plane toujours et le moindre détail peut vite tourner au soupçon. Et plus un fil est tendu, plus il risque de casser au moindre choc...`},
            {image: "asset/TheAncientMagusBride/T17.jpg" , synopsis: `Voici que se manifeste la divinité de l'imposture. Le testament ou Philomela ? À présent que les deux ont fusionné, ils veulent s'échapper du collège et pendant la fête de Noël, ils s'opposent à tous les magiciens de l'établissement. Alors que la situation est critique, Chisé et Elias lui font face...`},
            {image: "asset/TheAncientMagusBride/T18.jpg" , synopsis: `Chisé s'est transformée en dragon pour traverser la terre et s'introduire avec Elias dans le manoir des Sargent. Aidés par d'autres élèves du collège, ils retrouvent Philomela mais elle a tellement fusionné avec le "testament" qu'elle ne les écoute plus... Pour la sauver, Chisé va s'introduire à l'intérieur de sa psyché, ignorant tout de ce qui l'attend là-bas...`},
            {image: "asset/TheAncientMagusBride/T19.jpg" , synopsis: `Chisé s'est transformée en dragon pour traverser la terre et s'introduire avec Elias dans le manoir des Sargent. Aidés par d'autres élèves du collège, ils retrouvent Philomela mais elle a tellement fusionné avec le "testament" qu'elle ne les écoute plus... Pour la sauver, Chisé va s'introduire à l'intérieur de sa psyché, ignorant tout de ce qui l'attend là-bas...`},
            {image: "asset/TheAncientMagusBride/T20.jpg" , synopsis: `Qu'est-ce que l'amour, la haine ou encore la malédiction ? Au beau milieu de la bataille, Philomela trouve elle-même la réponse en utilisant la rune Thurizas que Chisé lui avait donnée... Ainsi se termine la tragédie du clan Sargent. Chise rentre chez elle en compagnie d'Elias et de ses camarades de classe pour goûter à quelques moments de tranquillité, Mais elle va devoir payer le prix fort pour avoir fait appel à ses pouvoirs surnaturels et s'être transformée en dragon. Le tumulte des bêtes sauvages s'intensifie... La chasse va bientôt être ouverte.`},
            {image: "asset/TheAncientMagusBride/T21.jpg" , synopsis: `Le murmure des illusions grouille et s'amplifie. Le concile demande la coopération des puissants clans des magiciens, appartenant aux sept boucliers, afin d'enquêter sur les rumeurs parlant du dragon rouge.`},
            {image: "asset/TheAncientMagusBride/T22.jpg" , synopsis: `La nouvelle année commence et Chisé et Elias sont invités à enquêter sur le dragon rouge en compagnie des jumeaux et de Lindsay, un des chefs de clan des "sept boucliers". Bien qu'ils hésitent au début, ils finissent par accepter et commencent les préparatifs pour retourner au collège. Au même moment, la mère de Violette et Jasmine, Hilda Saint-George, se rend au territoire des dragons et implore Lindel de la suivre en Grande-Bretagne...`},
            {image: "asset/TheAncientMagusBride/T23.jpg" , synopsis: `Chisé et Elias sont chargés d'enquêter sur les troubles qui sévissent en Grande-Bretagne, à la demande des "sept boucliers". En attendant des nouvelles de la famille Saint-George qui les épaulera, ils sont invités par leur ami Zoey dans le village des gorgones. Ce dernier est ravi de retrouver ses parents, mais c'est sans compter sur les rancunes du passé qui l'enchaînent...`},
        ]],
    }],
];

// ------------------------------ Trier le tableau par ordre alphabétique -----------------------------------------------
const mangaOrdered = mangaList.sort((a, b) =>
    a[1].title.localeCompare(b[1].title, undefined, {
        sensitivity: "base"
    })
);