const animeList=[
    ["swordArtOnline",{
        support:"anime",
        title: "Sword Art Online",
        originalTitle: "ソードアート・オンライン",
        otherTitle: false,
        type: "Série",
        class: "Shonen",
        genre: ["Action","Aventure","Comédie","Isekai","Romance","Sciences-fiction"],
        theme: ["Adolescence","Amour","Jeux-vidéo","Monde virtuel"],
        episodes: 76,
        saisons: 3,
        status: "En cours",
        date: "Eté 2012",
        studio: "A-1 Pictures",
        diffusion: "ADN",
        synopsis: `Cette série raconte les aventures de Kirito qui se retrouve piégé dans un jeu massivement multi-joueurs, Sword Art Online. En 2022, l'humanité a réussi à créer une réalité virtuelle. Grâce à un casque, les humains peuvent se plonger entièrement dans le monde virtuel en étant comme déconnectés de la réalité, et Sword Art Online est le premier MMORPG a utiliser ce système. Mais voila que le premier jour de jeu, 10 000 personnes se retrouvent piégées dans cette réalité virtuelle par son créateur : Akihiko Kayaba. Le seul moyen d'en sortir est de finir le jeu. Mais ce ne sera pas facile de sortir de ce monde virtuel puisque si un joueur perd la partie, il meurt également dans la vraie vie. Kirito décide alors de partir à la conquête du jeu en solo, avec pour avantage le fait de faire partie des 1 000 ex-bêta-testeurs, mais arrivera-t-il à terminer les 99 donjons et leurs boss ? "Même si cela semble être un jeu vidéo, ce n'est pas un jeu" Akihiko Kayaba - Créateur de "Sword Art Online"`,
        image: "asset/SwordArtOnline/S1.jpg",
        background:"asset/SwordArtOnline/Bg.jpg",
        listSaisons:[
            {title: "Saison 1" , image: "asset/SwordArtOnline/S1.jpg" , synopsis: `En 2022, Sword Art Online devient le premier MMORPG utilisant une technologie de réalité virtuelle permettant une immersion totale. Mais dès son lancement, 10 000 joueurs se retrouvent piégés par son créateur, Akihiko Kayaba. Pour retrouver leur liberté, ils devront terminer le jeu, avec une terrible règle : mourir dans SAO signifie mourir dans la réalité. Kirito, ancien bêta-testeur, décide de partir seul à la conquête des 100 étages d'Aincrad et de leurs redoutables boss. Parviendra-t-il à terminer le jeu et à libérer tous les joueurs ?`},
            {title: "Saison 2" , image: "asset/SwordArtOnline/S2.jpg" , synopsis: `Après sa victoire face à Sugou Nobuyuki, Kirito retrouve enfin sa paisible vie de lycéen. Mais plusieurs morts mystérieuses viennent bientôt troubler son quotidien : des joueurs de Gun Gale Online seraient décédés dans la réalité après avoir été abattus dans le jeu. Sollicité par Kikuoka Seijirô pour enquêter, Kirito plonge dans ce nouvel univers dominé par les armes à feu. Il devra participer au tournoi Bullet of Bullets et retrouver Death Gun, un mystérieux joueur qui semble capable de tuer ses victimes à travers le monde virtuel.`},
            {title: "Saison 3 - Alicization" , image: "asset/SwordArtOnline/S3.jpg" , synopsis: `À la demande de Seijirô Kikuoka, Kazuto teste le Soul Translator, une nouvelle technologie développée par Rath qui lui permet d'accéder à l'Underworld. Il y rencontre Eugeo et Alice, deux enfants avec lesquels il se lie d'amitié, avant qu'Alice ne soit emmenée pour avoir enfreint les lois de ce monde. Plus tard, Kazuto est grièvement blessé dans la réalité par un ancien membre de Laughing Coffin. Pour le sauver, il est plongé dans l'Underworld, où plusieurs années se sont écoulées et où il retrouve Eugeo, désormais devenu un jeune homme.`},            
        ],
    }],
    ["TonikakuKawaii",{
        support:"anime",
        title: "Tonikaku Kawaii",
        originalTitle: "トニカクカワイイ",
        otherTitle: "Fly Me to The Moon",
        type: "Série",
        class: "Shonen",
        genre: ["Comédie","Romance","Slice of Life"],
        theme: ["Adolescence","Amour","Mariage","Mystère"],
        episodes: 24,
        saisons: 2,
        status: "En cours",
        date: "Automne 2020",
        studio: "SEVEN·ARCS",
        diffusion: "Crunchyroll",
        synopsis: `Le prénom de Nasa Yuzaki, un collégien studieux, s'écrit avec le kanji de «Nuit étoilée», mais il se prononce «Nasa». Pour ne plus que l'on se moque de son nom étrange, il s'est juré de devenir une personne importante.
Durant une nuit enneigée, il aperçoit une jeune fille dont il tombe tout de suite amoureux. Cependant, alors qu'il ne fait plus attention à la route, il se fait renverser par un camion.
Tsukasa, la jeune fille qu'il regardait, le sauve et Nasa profite de cette situation pour lui avouer ses sentiments. La jeune fille accepte de sortir avec lui mais à une seule condition : ils doivent se marier !
Plusieurs années après cet événement, Tsukasa vient sonner chez Nasa pour tenir la promesse qu'elle a faite. Ainsi commence la vie à deux de nos jeunes mariés !`,
        image: "asset/TonikakuKawaii/S1.jpg",
        background:"asset/TonikakuKawaii/Bg.jpg",
        listSaisons: [
            {title: "Saison 1", image: "asset/TonikakuKawaii/S1.jpg", synopsis: `Après avoir frôlé la mort dans un accident, Nasa rencontre Tsukasa, une mystérieuse jeune fille dont il tombe immédiatement amoureux. Lorsqu'il lui avoue ses sentiments, celle-ci accepte de sortir avec lui à une seule condition : qu'ils se marient. Quelques années plus tard, Tsukasa réapparaît à sa porte et tient sa promesse. À peine réunis, les deux jeunes mariés découvrent alors ensemble les joies et les embarras de la vie de couple, tandis que Nasa cherche encore à percer les nombreux mystères qui entourent sa nouvelle épouse.`},
            {title: "Saison 2", image: "asset/TonikakuKawaii/S2.jpg", synopsis: `Désormais bien installés dans leur vie de jeunes mariés, Nasa et Tsukasa continuent de découvrir les petits bonheurs du quotidien à deux. Entre rendez-vous amoureux, nouvelles rencontres et moments passés avec leurs proches, leur relation devient peu à peu plus profonde. La question d'une cérémonie de mariage commence également à se poser. Mais derrière cette vie paisible, Tsukasa conserve encore des secrets sur son passé, tandis que Nasa réalise chaque jour un peu plus ce que signifie partager sa vie avec celle qu'il aime.`},
        ],
    }],
    ["DeathNote",{
        support:"anime",
        title: "Death Note",
        originalTitle: "デスノート",
        otherTitle: false,
        type: "Série",
        class: "Seinen",
        genre: ["Drame","Psychologique","Surnaturel","Thriller"],
        theme: ["Détective","Mort","Police","Shinigami","Mystère","Tragique"],
        episodes: 37,
        saisons: 1,
        status: "Terminé",
        date: "Automne 2006",
        studio: "Madhouse",
        diffusion: "YouTube - Netflix - Crunchyroll",
        synopsis: `Light Yagami, un jeune étudiant surdoué, ramasse un jour le "Death Note", un carnet tenu auparavant par un shinigami (Dieu de la mort), Ryuk, qui apparemment s'ennuyait dans son monde.
Il suffit d'écrire le nom d'une personne dans ce carnet, et celle-ci meurt (selon certaines conditions que le shinigami expliquera à Light lors de leur rencontre).
C'est ainsi qu'avec le "Death Note" entre les mains, Light décide de débarrasser la planète de tous les criminels pour en faire un monde juste, un monde parfait.
Cependant, qui est-il pour juger les gens ? Il devient donc le pire criminel recherché de toute la planète...`,
        image: "asset/DeathNote/S1.jpg",
        background:"asset/DeathNote/Bg.jpg",
        listSaisons: false,
    }],
    ["AccelWorld",{
        support:"anime",
        title: "Accel World",
        originalTitle: "アクセル・ワールド",
        otherTitle: false,
        type: "Série",
        class: "Shonen",
        genre: ["Action","Drame","Romance","School Life","Science-fiction"],
        theme: ["Adolescence","Amour","Jeux-vidéo","Monde virtuel"],
        episodes: 24,
        saisons: 1,
        status: "Terminé",
        date: "printemps 2012",
        studio: "SUNRISE",
        diffusion: "Wakanim (Licence expirée)",
        synopsis: `L'histoire se passe au cours de l'année 2046, dans un monde où le virtuel est omniprésent, notamment grâce aux "neuro-linkers".
Le personnage principal se nomme Haruyuki, ou plus simplement Haru pour ses proches, et est le souffre douleur des caïds de son lycée. Son seul plaisir est un jeu virtuel ressemblant au squash, dans lequel il excelle... jusqu'au jour où il est battu par une mystérieuse jeune fille. Cette dernière s'avère être Kuroyukihime, une des membres du Conseil des élèves.
Si elle a battu son score, c'est pour lui demander de l'aide. Haru étant quelque peu hésitant, elle lui présente un curieux jeu, "Brain Burst", qui s'avère être bien plus qu'un simple jeu.
En effet, ceux qui possèdent ce logiciel sont capables de se transférer dans un monde virtuel où 1 seconde du monde réel correspond à 16 minutes et 40 secondes. Cela s'appelle "accélérer".
Mais pour conserver ce pouvoir, il faut combattre, et gagner des points. L'aventure de Haru dans ce nouveau monde ne fait que commencer.`,
        image: "asset/AccelWorld/S1.jpg",
        background:"asset/AccelWorld/Bg.jpg",
        listSaisons: false,
    }],
    ["LookBack",{
        support:"anime",
        title: "Look Back",
        originalTitle: "ルックバック",
        otherTitle: false,
        type: "Film",
        class: "Shonen",
        genre: ["Drame","Slice of Life"],
        theme: ["Adolescence","Amitié","Solitude","School Life"],
        episodes: 1,
        saisons: 1,
        status: "Terminé",
        date: "Eté 2024",
        studio: "Studio Durian",
        diffusion: "Amazon Prime Video",
        synopsis: `Fujino est une adolescente qui dessine des manga pour le journal de l'école. Son art fait d'elle la star de sa classe mais un jour, elle apprend que Kyomoto, une élève qui refuse de venir à l'école, aimerait elle aussi soumettre un manga pour le journal...`,
        image: "asset/LookBack/Film.jpg",
        background:"asset/LookBack/Bg.jpg",
        listSaisons: false,
    }],
    ["TheAncientMagusBride",{
        support:"anime",
        title: "The Ancient Magus Bride",
        originalTitle: "魔法使いの嫁",
        otherTitle:  "Mahō Tsukai no Yome",
        type: "Série",
        class: "Shonen",
        genre: ["Aventure","Drame","Fantastique","Slice of Life"],
        theme: ["Dragons","Magie","Sorcellerie","Mystère"],
        episodes: 48,
        saisons: 2,
        status: "Terminé",
        date: "automne 2017",
        studio: "Wit Studio",
        diffusion: "Crunchyroll",
        synopsis: `Fujino est une adolescente qui dessine des manga pour le journal de l'école. Son art fait d'elle la star de sa classe mais un jour, elle apprend que Kyomoto, une élève qui refuse de venir à l'école, aimerait elle aussi soumettre un manga pour le journal...`,
        image: "asset/TheAncientMagusBride/S1.jpg",
        background:"asset/TheAncientMagusBride/Bg.jpg",
        listSaisons: [
            {title: "Saison 1", image: "asset/TheAncientMagusBride/S1.jpg", synopsis: `Il s'agit d'une série animée se basant sur le manga Mahou Tsukai no Yome de Yamazaki Koré. Chise Hatori est une esclave jusqu'au jour où sa route croise celle du Magus Elias Ainsworth. Ce dernier décèle en elle un don certain pour la magie et décide de l'acheter pour faire d'elle son apprentie. Elle devra également l'épouser dans le futur.`},
            {title: "Saison 2", image: "asset/TheAncientMagusBride/S2.jpg", synopsis: `Grâce à Elias et tous ceux qu'elle a rencontré, Chise continue d'appréhender le monde magique dans lequel elle évolue désormais, parfois avec difficultés.`},
        ],
    }],
    ["SPYxFAMILY",{
        support:"anime",
        title: "SPY×FAMILY",
        originalTitle: "スパイファミリー",
        otherTitle:  false,
        type: "Série",
        class: "Shonen",
        genre: ["Action","Aventure","Comédie"],
        theme: ["Assassinat","Espionnage","Famille","Guerre","Mensonges","Mystère","Organisations secrètes","Politique","Super pouvoirs","Terrorisme"],
        episodes: 50,
        saisons: 3,
        status: "Terminé",
        date: "Printemps 2022",
        studio: "CloverWorks - Wit Studio",
        diffusion: "Crunchyroll - Netflix - Amazon Prime Video",
        synopsis: `Sauvez le monde avec l'élite des agents (très) spéciaux : la famille Forger ! Une comédie d'espionnage pétillante ! Twilight, le plus grand espion du monde, doit pour sa nouvelle mission créer une famille de toutes pièces afin de pouvoir s'introduire dans la plus prestigieuse école de l'aristocratie. Totalement dépourvu d'expérience familiale, il va adopter une petite fille en ignorant qu'elle est télépathe, et s'associer à une jeune femme timide, sans se douter qu'elle est une redoutable tueuse à gages. Ce trio atypique va devoir composer pour passer inaperçu, tout en découvrant les vraies valeurs d'une famille unie et aimante.`,
        image: "asset/SPYxFAMILY/S1.jpg",
        background:"asset/SPYxFAMILY/Bg.jpg",
        listSaisons: [
            {title: "Saison 1", image: "asset/SPYxFAMILY/S1.jpg", synopsis: `Afin de préserver la paix entre Westalis et Ostania, l'espion Twilight reçoit une mission capitale : approcher Donovan Desmond. Sous l'identité de Loid Forger, il doit fonder une famille et inscrire son enfant à la prestigieuse académie Eden. Il adopte alors Anya et épouse Yor, sans savoir que la première est télépathe et que la seconde est une redoutable tueuse à gages. Chacun cachant sa véritable identité, cette famille improvisée va devoir apprendre à vivre ensemble tandis que Loid poursuit secrètement l'opération Strix.`},
            {title: "Saison 2", image: "asset/SPYxFAMILY/S2.jpg", synopsis: `La famille Forger poursuit son quotidien mouvementé tandis que Loid continue l'opération Strix et qu'Anya tente de se rapprocher de Damian à l'académie Eden. De son côté, Yor commence à s'interroger sur sa double vie lorsqu'une nouvelle mission lui est confiée : protéger une femme et son enfant traqués par de nombreux assassins à bord d'un luxueux paquebot. Par un incroyable hasard, Loid et Anya embarquent eux aussi pour la croisière. Yor devra alors accomplir sa mission sans révéler à sa famille qu'elle est la redoutable Princesse Ibara.`},
            {title: "Saison 3", image: "asset/SPYxFAMILY/S3.jpg", synopsis: `L'opération Strix se poursuit et Anya doit toujours gagner suffisamment d'Étoiles Stella pour permettre à Loid d'approcher Donovan Desmond. Mais le passé de Twilight refait surface, dévoilant les événements qui l'ont conduit à devenir espion et son désir de créer un monde où les enfants ne pleurent plus. Pendant ce temps, Anya se retrouve au cœur d'une situation autrement plus dangereuse lorsque son bus scolaire est détourné par le Cirque Rouge. Les Forger vont une nouvelle fois être confrontés aux tensions qui menacent la fragile paix entre les deux pays.`},
        ],
    }],
];


// -------------------------------------- Trier le tableau par ordre alphabétique --------------------------------

const animeOrdered = animeList.sort((a, b) =>
    a[0].localeCompare(b[0], undefined, {
        sensitivity: "base"
    })
);