const mangaList=[
    ["swordArtOnline",{
        support:"manga",
        title: "Sword Art Online",
        originalTitle: "ソードアート・オンライン",
        otherTitle: false,
        class: "Shonen",
        genre: ["Action","Aventure","Comédie","Isekai","Romance","Sciences-fiction"],
        theme: ["Adolescence","Amour","Jeux-vidéo","Monde virtuel"],
        VO: 23,
        statusVO: "En cours",
        VF: 23,
        statusVF: "En cours",
        origine: "Japon - 2010",
        sortieVF: "2014",
        editeur: "Ototo",
        auteur: "Kawahara Reki - Nakamura Tamako",
        synopsis: "Bienvenue dans le jeu en ligne Sword Art Online. Kirito adore les MMORPG et fait partie des 10.000 privilégiés ayant réussi à se procurer ce jeu qui fonctionne avec un système de réalité virtuelle directe. Ainsi, le joueur met un casque et entre dans le jeu, maniant son avatar avec sa pensée. Kirito avait déjà testé la version Bêta et se débrouille mieux que d'autres. Sword Art fait la part belle aux combats et ne possède pas de magie. Mais tous paniquent quand ils apprennent qu'ils ne peuvent plus sortir du jeu. La seule façon de se déconnecter est de le finir en arrivant au niveau 99. De plus, si le joueur perd tous ses points de vie, il meurt également dans la réalité ! Quel est le but du créateur du jeu ?",
        image: "asset/SwordArtOnline/AincradT1.jpg",
        background: "asset/SwordArtOnline/Bg.jpg",
        tomes:[
            ["Aincrad",[
                {image: "asset/SwordArtOnline/AincradT1.jpg" , synopsis: `En 2022, Kirito, un adolescent sans histoire, se retrouve piégé avec 10 000 autres joueurs dans un jeu en réalité augmentée massivement multijoueurs : Sword Art Online. Pour regagner leur liberté, les joueurs devront compléter les 100 étages qui composent l'Aincrad, leur prison virtuelle. Mais le moindre faux pas pourrait être fatal, puisqu'un Game Over dans le jeu entraînera une mort réelle. Kirito, le joueur solo, se lance dans une course effrénée pour sa survie, dans un monde où l'art de l'épée dicte la loi des plus forts.`},
                {image: "asset/SwordArtOnline/AincradT2.jpg" , synopsis: `« Vous êtes bien dans un jeu vidéo, mais vous n'êtes plus là pour jouer. ». Deux ans après le début de la partie, seulement six mille survivants... Kirito est l'un d'eux. Il a décidé de conquérir en « solo » les cent étages qui le mèneront au combat final et qui lui permettra de regagner sa liberté. Mais c'est sans compter sur l'obstination d'Asuna, une habile épéiste avec qui il va devoir s'allier. Démarre alors une course effrénée pour survivre dans un monde où l'art de l'épée dicte la loi. Fin du premier chapitre Aincrad de Sword Art Online.`},
            ]],["Fairy Dance",[
                {image: "asset/SwordArtOnline/FairyDanceT1.jpg" , synopsis: `Kazuto Kirigaya, alias Kirito, est revenu sain et sauf d'Aincrad, mais Asuna ne s'est toujours pas réveillée de son coma. Alors qu'il lui rend visite à l'hôpital, il apprend que Nobuyuki Sugô compte l'épouser malgré son état. Peu après, Agil lui montre l'image troublante d'un avatar ressemblant étrangement à Asuna, apparemment prisonnière d'un nouveau VRMMO : ALfheim Online. Convaincu qu'il s'agit bien d'elle, Kirito décide de replonger dans la réalité virtuelle pour la retrouver et découvrir ce qui se cache derrière ce nouveau jeu.`},
                {image: "asset/SwordArtOnline/FairyDanceT2.jpg" , synopsis: `Kirito s'engouffre à l'intérieur du VRMMO « Alfheim Online » pour atteindre le sommet de l'Arbre du monde. Il y rencontre une Sylphide du nom de Leafa, qui accepte de l'y accompagner... Cependant, Leafa n'est en réalité, rien d'autre que la propre sœur de Kazuto, Suguha. Cette dernière éprouve secrètement des sentiments pour celui. Ils poursuivent leur route ensemble vers l' « Arbre du monde » sans connaître le destin qui les lie, ni celui qui les attend...`},
                {image: "asset/SwordArtOnline/FairyDanceT3.jpg" , synopsis: `Kirito, Yui et Lyfa arrivent au pied de l'Arbre du Monde où est retenue Asuna. Yui ressantant fortement l'ID d'Asuna en haut de l'arbre, elle en informe Kirito. Celui-ci, plus résolu que jamais à sauver Asuna, se lance alors seul à l'assaut de la Grande Quête, que personne n'a jamais réussi à accomplir, mais qui constitue le seul moyen de se rendre au sommet de l'arbre.`},
            ]],["Phantom Bullet",[
                {image: "asset/SwordArtOnline/PhantomBulletT1.jpg" , synopsis: `Le volume débute sur un bref rappel des événements de l'arc Aincrad avant de nous plonger directement dans l'univers de GGO via Sinon. Le tournoi du jeu, Bullet of Bullets, est sur le point de débuter lorsqu'un des favoris, Zexceed, disparaît mystérieusement. D'après certains témoins, un étrange individu lui aurait tiré dessus à travers un écran en prétendant le tuer dans la vraie vie. Coïncidence troublante, Zexceed s'est déconnecté peu après, en pleine interview. Kirito est alors choisit par Kikuoka Seijirô pour mener l'enquête de l'intérieur.`},
                {image: "asset/SwordArtOnline/PhantomBulletT2.jpg" , synopsis: `Afin de mener l'enquête qui lui a été confié, Kirito a converti son avatar afin de pouvoir jouer à GGO. Une fois dans le jeu, il a fait la connaissance de Sinon, qui lui a indiqué comment s'inscrire au tournoi. En effet, Kirito est persuadé que Death Gun va profiter du tournoi pour faire de nouvelles victimes et il compte bien l'arrêter avant.`},
                {image: "asset/SwordArtOnline/PhantomBulletT3.jpg" , synopsis: `Alors que la fin du tournoi Bullet of Bullets approche, Kirito et Sinon se trouvent face au mystérieux assassin qui, comme le jeune épéiste, s'avère être un survivant de SAO.`},
                {image: "asset/SwordArtOnline/PhantomBulletT4.jpg" , synopsis: `Kirito a désormais la conviction que Death Gun ne tue pas directement les joueurs dans le jeu, mais qu'il utilise une autre méthode. Ayant l'intuition que Sinon est en danger, il se précipite au secours de cette dernière.`,}
            ]],["Calibur",[
                {image: "asset/SwordArtOnline/Calibur.jpg" , synopsis: `Après avoir résolu l'affaire "Death Gun", Kirito retourne sur ALO afin d'obtenir l'épée la plus puissante du jeu : la légendaire Excalibur. Accompagné d'Asuna, Klein, Lisbeth, Lyfa, Silica et Sinon, qui s'est créée un avatar pour pouvoir jouer avec le groupe, il se lance donc dans une série de quête basées sur la mythologie nordique.`},
            ]],["Mother Rosario",[
                {image: "asset/SwordArtOnline/MothersRosarioT1.jpg" , synopsis: `Depuis quelques temps, un spriggan surnommé Zekken (épée absolue) fait beaucoup parler de lui sur ALO. En effet, ce joueur serait invincible et même Kirito ne serait pas parvenu à le vaincre. Cela pique l'intérêt d'Asuna qui décide de tenter sa chance. C'est ainsi qu'elle rencontre Yuuki, une jeune fille qui lui rappelle beaucoup Kirito et qui, derrière d'impressionnantes capacités, cache un lourd secret.`},
                {image: "asset/SwordArtOnline/MothersRosarioT2.jpg" , synopsis: `Asuna a temporairement rejoint la guilde de Yuuki, les Sleeping Knight, et a entrepris de les aider à accomplir leur objectif : vaincre un boss avec seulement 7 personnes, afin de graver tous leurs pseudonymes sur le Kenshi no Hi, le Mur des Épéistes.`},
                {image: "asset/SwordArtOnline/MothersRosarioT3.jpg" , synopsis: `Alors qu'elle découvre le secret de Yûki, Asuna décide de s'impliquer de plus en plus auprès de la jeune fille et de l'aider à réaliser ses rêves.`},
            ]],["Ordinal Scale",[
                {image: "asset/SwordArtOnline/OrdinalScaleT1.jpg" , synopsis: `Ordinal Scale est le jeu le plus populaire auquel il est possible de jouer grâce à l'Augma. Asuna, Klein et leurs amis en sont fans et adorent participer aux events. Kirito, de son côté, est plus réservé. Il faut dire qu'OS est beaucoup plus physique que les autres VRMMORPG et il manque cruellement d'entraînement.`},
                {image: "asset/SwordArtOnline/OrdinalScaleT2.jpg" , synopsis: `Alors qu'elle participe à un événement d'Ordinal Scale proposant de combattre d'anciens boss issus de SAO, Asuna perd subitement la mémoire ! Elle se souvient de sa famille, de ses amis, de sa relation avec Kirito, mais elle a tout oublié des deux années passées dans le jeu mortel. Intrigué, Kirito décide d'enquêter.`},
                {image: "asset/SwordArtOnline/OrdinalScaleT3.jpg" , synopsis: `Après avoir joué à Ordinal Scale un peu plus sérieusement, Kirito découvre les raisons de l'amnésie d'Asuna ainsi que l'objectif d'Eiji et de son complice. Il décide alors d'intervenir pour que ses amis retrouvent leurs souvenirs.`},
                {image: "asset/SwordArtOnline/OrdinalScaleT4.jpg" , synopsis: `Tout ce qui se passe d'étrange dans Ordinal Scale semble lié à la mystérieuse AI Yuna, dont le premier grand concert aura lieu prochainement. Kirito décide de s'y rendre afin de mettre un terme aux ambitions d'Eiji et de ses complices.`},
                {image: "asset/SwordArtOnline/OrdinalScaleT5.jpg" , synopsis: `Le mystérieux lien entre Yuna et Eiji se dévoile, tout comme le but réel du créateur d'Ordinal Scale. Mais est-il encore possible de l'arrêter?`},
            ]],["Project Alicization",[
                {image: "asset/SwordArtOnline/ProjectAlicizationT1.jpg" , synopsis: `Invité à tester une nouvelle machine de réalité virtuelle, Kirito est agressé par un ancien membre de Laughing Coffin et se retrouve piégé dans un mystérieux monde appelé l'Underworld. Incapable de rejoindre la réalité, il y rencontre Eugeo, un jeune entailleur marqué par la disparition de son amie d'enfance, Alice. Ensemble, ils partent dans une quête qui les mènera bien au-delà de leur village. Mais quels secrets cache l'Underworld, et que se trame-t-il dans le monde réel ? La plus grande aventure de l'Épéiste noir ne fait que commencer.`},
                {image: "asset/SwordArtOnline/ProjectAlicizationT2.jpg" , synopsis: `Après avoir été agressé, Kirito s'éveille dans l'Underworld sans vraiment comprendre ce qui lui est arrivé. Là, il retrouve Eugeo, qui a désormais son âge mais ne se souvient pas de lui.`},
                {image: "asset/SwordArtOnline/ProjectAlicizationT3.jpg" , synopsis: `Après s'être fait quelques frayeurs, Kirito et Eugeo ont enfin réussi à venir à bout de la Tâche de ce dernier. Ils peuvent désormais quitter le village et partir à la recherche d'Alice.`},
                {image: "asset/SwordArtOnline/ProjectAlicizationT4.jpg" , synopsis: `Arrêtés par nulle autre qu'Alice, Kirito et Eugeo sont emmenés à la cathédrale où réside l'Administrateur et l'élite de l'empire humain : les Chevaliers Intègres.`},
                {image: "asset/SwordArtOnline/ProjectAlicizationT5.jpg" , synopsis: `Afin de comprendre ce qui est arrivé à Alice, Kirito et Eugeo s'infiltrent au cœur de la cathédrale afin de trouver l'Administrateur. Mais l'ascension est semée d'embûches et le duo doit affronter de nombreux Chevaliers Intègres.`},
            ]],
        ],
    }],
    ["TonikakuKawaii",{
        support:"manga",
        title: "Tonikaku Kawaii",
        originalTitle: "トニカクカワイイ",
        otherTitle: "Fly Me to The Moon",
        class: "Shonen",
        genre: ["Comédie","Romance","Slice of Life"],
        theme: ["Adolescence","Amour","Mariage","Mystère"],
        VO: 8,
        statusVO: "En cours",
        VF: 36,
        statusVF: "En cours",
        origine: "Japon - 2018",
        sortieVF: "2022",
        editeur: "noeve grafx",
        auteur: "Hata Kenjiro",
        synopsis: `Yuzaki Nasa sera sans conteste la personne qui atteindra la vitesse de la lumière plus rapidement que la NASA, enfin c'est ce qu'il affirme. En effet, ce collégien extrêmement studieux s'est juré de devenir quelqu'un d'important pour ne plus être le sujet de moqueries de ses camarades du fait de son prénom qui se prononce "NASA", faisant directement référence à l'agence spatiale américaine.
Un jour, en rentrant chez lui après avoir prouvé qu'il avait les capacités pour entrer dans les meilleurs lycées du pays en arrivant en première position lors des examens de fin d'année, il croise par hasard une jeune fille dont il tombe tout de suite sous le charme.
Ne faisant pas attention à la route il se fait percuter par un camion mais sera secouru par cette dernière avant de le laisser au soin du camionneur.
Faisant abstraction de ses blessures, Yuzaki part à la poursuite de la jeune demoiselle en espérant la retrouver afin de lui déclarer son amour et qu'elle accepte de sortir avec lui. Chose qu'elle accepta à condition que les deux se marient. Sans aucune hésitation il répond « Oui ! » avant de s'effondrer de douleur.
Après avoir survécu à ses blessures et s'être réveillé de son coma, Yuzaki n'a plus vraiment gout à la vie. Il arrête ses études, accumule des jobs à temps partiel et quitte le domicile familial. Tout ce qu'il souhaite, c'est de revoir la fille dont il est tombé amoureux.
Alors qu'il entame sa 19e année, un personne vient sonner à la porte de chez lui. Il ne s'agit de nul autre que la mystérieuse jeune fille qui vient lui faire tenir la promesse qu'ils se sont faites il y a quelque années de cela. Ainsi commence la vie à deux de nos jeunes mariés !`,
        image: "asset/TonikakuKawaii/T1.jpg",
        background: "asset/TonikakuKawaii/Bg.jpg",
        tomes: [false,[
            {image: "asset/TonikakuKawaii/T1.jpg" , synopsis: `Depuis le jour où ses parents l'ont nommé, Nasa Yuzaki se sent connecté à l'espace... qu'il le veuille ou non. Ses efforts pour surpasser le programme spatial dévient de leur objectif lorsqu'un accident lui fait rencontrer Tsukasa, une mystérieuse fille aux pouvoirs étranges. Est-ce une extraterrestre, une déesse de la lune ou autre chose ? Comme elle insiste pour l'épouser, Nasa aura de nombreuses occasions de le découvrir !`},
            {image: "asset/TonikakuKawaii/T2.jpg" , synopsis: `Maintenant que Nasa et Tsukasa sont mariés, il est temps pour lui de rencontrer sa famille. Malheureusement pour lui, cela signifie se faire kidnapper par la sœur surprotectrice de Tsukasa, Chitose, et ses servantes de combat. La vie de Nasa s'arrêtera-t-elle avant même qu'il ait embrassé sa nouvelle femme ? Ou qu'il ait choisi une bague ? Ou, plus important encore, qu'il ait découvert quels sont ses films préférés ?`},
            {image: "asset/TonikakuKawaii/T3.jpg" , synopsis: `Je passerai ma vie à lui prouver mon amour. Les jeunes mariés coulent des journées paisibles dans leur minuscule appartement, mais Nasa semble avoir oublié un léger détail... d'ordre parental ! Un détail qui amène le couple à prendre la route vers la ville de Nara. Un premier voyage en amoureux... n'est-ce pas là le début de leur lune de miel ?! Quelles suprises attendent Nasa et Tsukasa en chemin ?!`},
            {image: "asset/TonikakuKawaii/T4.jpg" , synopsis: `Tsukasa et Nasa sont hébergés chez les Arisugawa le temps de trouver un nouveau logement... Grâce à la générosité de ses voisines, le jeune couple peut prendre le temps de profiter d’une vie maritale remplie d’amour ! Mais ce bonheur tout neuf soulève des suspicions dans l’entourage de Nasa... Voilà que Tsukasa est mise à l’épreuve!`},
            {image: "asset/TonikakuKawaii/T5.jpg" , synopsis: `La lune de miel de Nasa et Tsukasa touche à sa fin... mais une mauvaise surprise les attend à leur retour ! Alors que leur vie de couple débute à peine, il leur reste beaucoup à apprendre l'un sur l'autre... et encore beaucoup de premières fois à vivre ensemble.`},
            {image: "asset/TonikakuKawaii/T6.jpg" , synopsis: `La famille Yuzaki accueille un adorable chaton ! Ginga, le cousin de Nasa, vient lui rendre visite car il a un service à lui demander ! Voilà comment un personnage mignon de plus fait son entrée dans la famille ! ♡ Dans la suite du tome, Nasa et Tsukasa vont passer une journée en amoureux dans un parc d'attraction !`},
            {image: "asset/TonikakuKawaii/T7.jpg" , synopsis: `Nos tourtereaux se retrouvent séparés pour la première fois ?! Voici venue la première épreuve pour notre couple fusionnel. Nasa doit retourner travailler une journée entière chez un ancien employeur. Tsukasa se sent bien seule pour leur première longue séparation. Bien entendu, ce volume va ensuite déborder d'amour !`},
            {image: "asset/TonikakuKawaii/T8.jpg" , synopsis: `Nasa et Tsukasa vont prendre leur bain ensemble ! Notre petit couple se retrouve aux sources chaudes de Kusatsu. Un voyage plein d'amour et de bonheur teinté de quelques petits soucis. Car ils vont se baigner ensemble. Un moment à la fois heureux et gênant !`},

        ]]
    }],
    ["DeathNote",{
        support:"manga",
        title: "Death Note",
        originalTitle: "デスノート",
        otherTitle: false,
        class: "Seinen",
        genre: ["Drame","Psychologique","Surnaturel","Thriller"],
        theme: ["Détective","Mort","Police","Shinigami","Mystère","Tragique"],
        VO: 12,
        statusVO: "Termnié",
        VF: 12,
        statusVF: "Terminé",
        origine: "Japon - 2003",
        sortieVF: "2007",
        editeur: "Kana",
        auteur: "Ohba Tsugumi - Obata Takeshi",
        synopsis: `Light Yagami est un jeune lycéen de 17 ans qui possède toutes les qualités pour devenir un brillant policier comme son père, mais il s'ennuie. Les cours lui semblent trop simple, et la vie trop ennuyeuse. Un jour, il trouve le Death Note d'un Shinigami (un Dieu de la Mort). Il y est écrit que chaque nom de personne inscrit provoquera la mort de celle-ci, par crise cardiaque, ou par accident au choix de l'utilisateur.

Tout d'abord, Light n'y croit pas, puis il y voit une excellente occasion de débarrasser le monde des malfrats, assassins et autres bandits. Une intention que les gouvernements verront bientôt comme une menace. Ils feront alors appel à L, un célèbre détective, pour démasquer celui que ses fans appellent Kira.`,
        image: "asset/DeathNote/T1.jpg",
        background: "asset/DeathNote/Bg.jpg",
        tomes: [false,[
            {image: "asset/DeathNote/T1.jpg" , synopsis: `Light Yagami, est un lycéen de 17 ans, qui obtient toujours les meilleurs résultats à l'école. Un jour, il trouva le Death Note, un cahier où, en écrivant le nom d'une personne tout en ayant son visage en tête, on peut décider des circonstances de sa mort ainsi que de l'heure de son decès.`},
            {image: "asset/DeathNote/T2.jpg" , synopsis: `Le FBI arrive au Japon pour mener l'enquête sur l'affaire Kira. Light qui fait partie des principaux suspects, il devra alors trouver tout les moyens possible pour ne plus l'être !`},
            {image: "asset/DeathNote/T3.jpg" , synopsis: `La résidence des Yagami est placée sous surveillance vidéo et audio, Light, aussi malin qu'il soit, réussit à tromper L, et continue ses activités ! Par la suite, un message d'un faux Kira est envoyé à une chaine de télévision, Light pense à une mauvaise blague.`},
            {image: "asset/DeathNote/T4.jpg" , synopsis: `La résidence des Yagami est placée sous surveillance vidéo et audio, Light, aussi malin qu'il soit, réussit à tromper L, et continue ses activités ! Par la suite, un message d'un faux Kira est envoyé à une chaine de télévision, Light pense à une mauvaise blague.`},
            {image: "asset/DeathNote/T5.jpg" , synopsis: `Light est enfermé à sa demande dans le but de prouver qu'il n'est pas Kira, plusieurs jours passent, et les meurtres reprennent. L est donc forcé de les faire sortir, mais à une seul condition ! Malgré la libération de Light, il sera toujours sous surveillance avec Misa.`},
            {image: "asset/DeathNote/T6.jpg" , synopsis: `Un nouveau Kira apparaît, L aurait déjà un suspect, il appartiendrait au groupe Yotsuba, qu'il va placer sous surveillance. A la demande de L, Amane Misa devra infiltrer le groupe Yotsuba, et ainsi découvrir qui est Kira. Elle fera la rencontre de Rem, son ancien dieu de la mort, et lui dira qui est Kira ! C'est alors que L et les autres commencent une course poursuite contre Higuchi.`},
            {image: "asset/DeathNote/T7.jpg" , synopsis: `La police est parvenue à encercler Higuchi, l'actuel possesseur du Death Note. Light parviendra-t-il à remettre la main sur le cahier ?! Va-t-il réussir à mener à bien le plan qu'il avait mis au point avant d'être placé sous surveillance ?!`},
            {image: "asset/DeathNote/T8.jpg" , synopsis: `Grâce à la mort de L, le monde idéal voulu par Light est en train de se construire. Mais les deux garçons désignés pour succéder à L, Near et Mello, entrent en scène. Une lutte commence alors pour la possession des Death Notes ! Mello enlève Sayu, la sœur de Light, et exige de procéder à un échange de cahiers !`},
            {image: "asset/DeathNote/T9.jpg" , synopsis: `Il n'y a plus que les membres du bureau d'enquête qui soient en mesure d'agir pour récupérer le cahier que possède Mello. Light a un plan pour les faire passer à l'action... C'est alors que Sôichirô Yagami, le père de Light, réintègre le bureau d'enquête. Il entend, en effet, jouer le rôle principal dans le plan de son fils !!`},
            {image: "asset/DeathNote/T10.jpg" , synopsis: `Le Q. G. du S. P. K. est encerclé par les partisans de Kira, mais Near réussit à s'évader d'une façon surprenante ! Les réflexions de Near le poussent dorénavant à concevoir de lourds soupçons à l'égard du second L, alias Light, ce qui n'est pas sans incidence sur le bureau d'enquête japonais...`},
            {image: "asset/DeathNote/T11.jpg" , synopsis: `Par l'intermédiaire de Kiyomi Takada, Light communique avec Mikami à qui il a remis son cahier de la Mort. De son côté, Near décide de se rendre au Japon. Les différents acteurs de l'intrigue sont maintenant tous réunis dans l'archipel... Quelle direction les événements vont-ils prendre ?`},
            {image: "asset/DeathNote/T12.jpg" , synopsis: `Le dénouement est proche pour Light et Near qui vont enfin s'affronter ! Quelles stratégies ces deux esprits hors du commun ont-ils donc élaborées pour prendre le dessus sur leur adversaire ?`},
        ]]
    }],
    ["LookBack",{
        support:"manga",
        title: "Look Back",
        originalTitle: "ルックバック",
        otherTitle: false,
        class: "Shonen",
        genre: ["Drame","Slice of Life"],
        theme: ["Adolescence","Amitié","Solitude","School Life"],
        VO: 1,
        statusVO: "Termnié",
        VF: 1,
        statusVF: "Terminé",
        origine: "Japon - 2021",
        sortieVF: "2022",
        editeur: "Shueisha",
        auteur: "Fujimoto Tatsuki",
        synopsis: `Fujino, adolescente surdouée, a une confiance absolue en son talent. Kyômoto, elle, se terre dans sa chambre et pratique sans relâche. Deux jeunes filles d'une même ville de province, qu'une passion fervente pour le dessin va rapprocher et unir par un lien indéfectible...`,
        image: "asset/LookBack/T1.jpg",
        background: "asset/LookBack/Bg.jpg",
        tomes: false,
    }],
    ["TheAncientMagusBride",{
        support:"manga",
        title: "The Ancient Magus Bride",
        originalTitle: "魔法使いの嫁",
        otherTitle: "Mahō Tsukai no Yome",
        class: "Shonen",
        genre: ["Aventure","Drame","Fantastique","Slice of Life"],
        theme: ["Dragons","Magie","Sorcellerie","Mystère"],
        VO: 24,
        statusVO: "En cours",
        VF: 23,
        statusVF: "En cours",
        origine: "Japon - 2014",
        sortieVF: "2015",
        editeur: "komikku",
        auteur: "Yamazaki Kore",
        synopsis: `Chise Hatori a le pouvoir spécial de voir des choses que d'autres ne peuvent voir. Un magicien étrange, dont la tête est un crâne tout aussi bizarre, est le premier à déceler le don de Chise. Il achètera cette jeune fille aux enchères au Japon pour la modique somme de 5 millions de livres sterling. De retour ensemble en Angleterre, Chise deviendra l'apprenti du magicien et est supposée l'épouser dans l'avenir. Le pouvoir spécial de Chise est appelé "Slay Vega" et permet de produire ainsi que d'émettre énormément de magie. Un pouvoir rare et de valeur qu'elle va devoir apprendre à maîtriser pour survivre car être un "Slay Vega" demande beaucoup d'énergie et peut conduire à la mort...`,
        image: "asset/TheAncientMagusBride/T1.jpg",
        background: "asset/TheAncientMagusBride/Bg.jpg",
        tomes: [false,[
            {image: "asset/TheAncientMagusBride/T1.jpg" , synopsis: `Chisé Hatori a 15 ans. Elle n'a ni famille, ni talent particulier, ni aucun espoir dans la vie. Un jour, elle est vendue à un sorcier, un non-humain dont l'existence remonte à la nuit des temps... Il la prend sous son aile pour faire d'elle sa disciple et lui annonce qu'à terme, elle deviendra son épouse. Alors, les aiguilles qui semblaient à tout jamais figées dans son cœur se mettent à tourner de nouveau, petit à petit...`},
            {image: "asset/TheAncientMagusBride/T2.jpg" , synopsis: `Alors que Chisé et Elias ont été envoyés en mission pour le compte de l'Eglise, ils se font brusquement attaquer par un mystérieux magicien et son apprentie. Quel peut bien être leur objectif ? Et quelle est la vraie nature du pouvoir de Chisé, que tout le monde appelle «Slay Vega» ? De sa plume élégante, Koré Yamazaki nous offre le tome deux de cette romance improbable entre deux êtres que tout oppose.`},
            {image: "asset/TheAncientMagusBride/T3.jpg" , synopsis: `Les Slay Vega disposent d'un pouvoir immense… Mais en contrepartie, ils portent un funeste destin sur leurs épaules. Chisé se retrouve aux prises avec le magicien à l'origine de la souillure d'Ulthar ! Blessée, elle tombe inconsciente… C'est alors qu'Elias révèle la puissance associée à son ancien surnom, celle du Pilum Murialis !`},
            {image: "asset/TheAncientMagusBride/T4.jpg" , synopsis: `Chisé est de retour aux pays des dragons, mandée par Lindel, leur gardien. Alors qu'elle se donne du mal pour se tailler une baguette, Lindel se met à raconter un pan d'un lointain passé. Un souvenir d'Elias... Quelle sera la réaction de Chisé face à son récit ? Sa relation particulière avec le non-humain va-t-elle être remise en question ?`},
            {image: "asset/TheAncientMagusBride/T5.jpg" , synopsis: `À force de combattre son lourd passé, Chisé décide d'aller de l'avant en compagnie d'Elias. Ce dernier, de son côté, apprend petit à petit à éprouver de la compassion et s'éveille aux beautés du monde. Un soir, la Leanan Sidhe, visiblement paniquée, vient chercher secours auprès de Chisé... Que pourra-t-elle faire pour l'aider ?`},
            {image: "asset/TheAncientMagusBride/T6.jpg" , synopsis: `À la croisée des sentiers où cheminent les humains et les êtres surnaturels, Chisé a décidé de suivre sa propre route, à son rythme. Après avoir reçu une lettre, elle se rend à Londres en secret, où elle retrouve Alice, l'apprentie de Renfred. Les voilà toutes deux en train d'arpenter les rues bondées... mais dans quel but ?`},
            {image: "asset/TheAncientMagusBride/T7.jpg" , synopsis: `Face à Chisé, qui s'est fait sa première amie "normale" et commence à changer, Elias est envahi par un sentiment qu'il ne s'explique pas. Alors qu'ils évoluent tous deux, chacun de leur côté, et que le sorcier a peur de voir s'éloigner sa disciple, Cartaphilus s'en prend cette fois-ci à Lindel en envoyant des braconniers au pays des dragons. Quel est l'objectif du magicien errant condamné à la souffrance éternelle ?`},
            {image: "asset/TheAncientMagusBride/T8.jpg" , synopsis: `Un plan ourdi par Cartaphilus, le magicien errant, pousse un dragon à perdre la tête… Alors qu'il s'enfuit dans le ciel de Londres, Chisé s'élance pour le sauver et doit pour cela payer une lourde compensation… La voilà maudite par trois fois : une fois par sa mère, une fois par sa naissance et une fois par le dragon. Il est temps d'affronter ceux qui jusqu'à maintenant détournaient les yeux, ce qui risque de fortement ébranler le cours de l'histoire.`},
            {image: "asset/TheAncientMagusBride/T9.jpg" , synopsis: `"Je ne peux plus rester avec vous…" Pour lever la malédiction qui pèse sur Chisé, Elias a dû faire un choix que la jeune fille ne cautionne pas. C'est la rupture… Elle décide de conclure un marché avec Cartaphilus, le magicien errant, mais que pourra-t-il lui apporter? Des vies presque terminées, des maléfices immuables, des routes qui se séparent… Quel avenir pour l'humaine et le non-humain ?`},
            {image: "asset/TheAncientMagusBride/T10.jpg" , synopsis: `Tout n'est pas parfait. Mais au moins, Chisé a réussi à s'accepter et à comprendre un peu mieux Elias. Cartaphilus est tombé dans un profond sommeil et alors que la situation s'est apaisée, les magiciens viennent voir la jeune sorcière pour lui proposer d'intégrer le collège de magie. Voilà Chisé et Elias précipités dans un lieu tout nouveau pour eux, dissimulé dans les sous-sols de la British Library, là où les apprentis magiciens étudient, découvrent et grandissent… Mais le non-humain va-t-il trouver sa place parmi tant d'humains ?`},
            {image: "asset/TheAncientMagusBride/T11.jpg" , synopsis: `Chisé est devenue auditrice libre au collège. De son côté, Elias a fini par accepter les changements de la jeune fille et commence à évoluer lui-même. Tandis que Chisé se fait de nouveaux amis, on découvre l'existence des "Sept boucliers" et l'Église entre à présent dans la partie. C'est le moment que choisit Rahab pour refaire son apparition. Quelle influence ces nouvelles fréquentations vont-elles avoir sur Elias et Chisé ?`},
            {image: "asset/TheAncientMagusBride/T12.jpg" , synopsis: `Le collège est un établissement qui regroupe plein d'apprentis magiciens. Ils suivent les mêmes cours, dorment sur place dans le dortoir et se connaissent depuis des années. Chisé va donc devoir trouver sa place parmi eux. Son quotidien est devenu beaucoup plus tranquille qu'auparavant. Elle continue d'aller de l'avant, entre les leçons et ses nouveaux camarades qu'elle apprend à connaître. Comme cette rumeur qui court sur Lucy, sa colocataire...`},
            {image: "asset/TheAncientMagusBride/T13.jpg" , synopsis: `Tout le monde a ses secrets. Chisé tout comme Zoey Ivy. Mais son secret a lui a été découvert et pour le protéger, les cinq élèves présents ont noué un pacte qui les empêche de parler. Plus Chisé se rapproche de ses camarades du collège, plus elle découvre le passé des différentes familles de magiciens. Mais personne ne sait ce que l'avenir leur réserve... Un jour, Chisé et le reste de sa classe partent en camp de survie dans les Highlands, une terre où les êtres de la nuit s'en donnent à cœur joie. Et comme d'habitude...`},
            {image: "asset/TheAncientMagusBride/T14.jpg" , synopsis: `Lucy s'est fait attaquer pendant que la classe était partie en camping. Simeon, un professeur, a été retrouvé inconscient dans l'enceinte du lycée. Alors que deux personnes ont déjà été victimes de malaise, les bibliothécaires découvrent qu'un livre interdit a été dérobé. Il s'agit d'une copie du "Testament de Carnamagos", un ouvrage qu'Elias avait demandé à lire par le passé... Alors que le lien peine à être établi entre les deux états de fait, Chisé se fait attaquer par deux hybrides chargés d'éliminer les survivants des Webster...`},
            {image: "asset/TheAncientMagusBride/T15.jpg" , synopsis: `Après leur rencontre inopinée avec un professeur dans la tour abandonnée et la découverte de plusieurs mystères, Chisé et ses camarades commencent à changer de gré ou de force. Alors que certains se lient davantage et d'autres se déchirent un peu plus, la copie du grimoire "Le testament de Carnamagos" est toujours introuvable. Pour éviter que d'autres drames se produisent, la directrice décide de sceller le collège par magie pendant quelque temps...`},
            {image: "asset/TheAncientMagusBride/T16.jpg" , synopsis: `Le grimoire volé est toujours à l'intérieur du collège. Pour quelle raison le coupable est-il resté sur place ? Quel est son véritable but ? Hélas, nul ne le sait. Confinés dans l'établissement, Chisé et les autres élèves se rapprochent petit à petit, mais l'ombre de la discorde plane toujours et le moindre détail peut vite tourner au soupçon. Et plus un fil est tendu, plus il risque de casser au moindre choc...`},
            {image: "asset/TheAncientMagusBride/T17.jpg" , synopsis: `Voici que se manifeste la divinité de l'imposture. Le testament ou Philomela ? À présent que les deux ont fusionné, ils veulent s'échapper du collège et pendant la fête de Noël, ils s'opposent à tous les magiciens de l'établissement. Alors que la situation est critique, Chisé et Elias lui font face...`},
            {image: "asset/TheAncientMagusBride/T18.jpg" , synopsis: `Chisé s'est transformée en dragon pour traverser la terre et s'introduire avec Elias dans le manoir des Sargent. Aidés par d'autres élèves du collège, ils retrouvent Philomela mais elle a tellement fusionné avec le "testament" qu'elle ne les écoute plus... Pour la sauver, Chisé va s'introduire à l'intérieur de sa psyché, ignorant tout de ce qui l'attend là-bas...`},
            {image: "asset/TheAncientMagusBride/T19.jpg" , synopsis: `Chisé s'est transformée en dragon pour traverser la terre et s'introduire avec Elias dans le manoir des Sargent. Aidés par d'autres élèves du collège, ils retrouvent Philomela mais elle a tellement fusionné avec le "testament" qu'elle ne les écoute plus... Pour la sauver, Chisé va s'introduire à l'intérieur de sa psyché, ignorant tout de ce qui l'attend là-bas...`},
            {image: "asset/TheAncientMagusBride/T20.jpg" , synopsis: `Qu'est-ce que l'amour, la haine ou encore la malédiction ? Au beau milieu de la bataille, Philomela trouve elle-même la réponse en utilisant la rune Thurizas que Chisé lui avait donnée... Ainsi se termine la tragédie du clan Sargent. Chise rentre chez elle en compagnie d'Elias et de ses camarades de classe pour goûter à quelques moments de tranquillité, Mais elle va devoir payer le prix fort pour avoir fait appel à ses pouvoirs surnaturels et s'être transformée en dragon. Le tumulte des bêtes sauvages s'intensifie... La chasse va bientôt être ouverte.`},
            {image: "asset/TheAncientMagusBride/T21.jpg" , synopsis: `Le murmure des illusions grouille et s'amplifie. Le concile demande la coopération des puissants clans des magiciens, appartenant aux sept boucliers, afin d'enquêter sur les rumeurs parlant du dragon rouge.`},
            {image: "asset/TheAncientMagusBride/T22.jpg" , synopsis: `La nouvelle année commence et Chisé et Elias sont invités à enquêter sur le dragon rouge en compagnie des jumeaux et de Lindsay, un des chefs de clan des "sept boucliers". Bien qu'ils hésitent au début, ils finissent par accepter et commencent les préparatifs pour retourner au collège. Au même moment, la mère de Violette et Jasmine, Hilda Saint-George, se rend au territoire des dragons et implore Lindel de la suivre en Grande-Bretagne...`},
            {image: "asset/TheAncientMagusBride/T23.jpg" , synopsis: `Chisé et Elias sont chargés d'enquêter sur les troubles qui sévissent en Grande-Bretagne, à la demande des "sept boucliers". En attendant des nouvelles de la famille Saint-George qui les épaulera, ils sont invités par leur ami Zoey dans le village des gorgones. Ce dernier est ravi de retrouver ses parents, mais c'est sans compter sur les rancunes du passé qui l'enchaînent...`},
        ]],
    }],
    ["AccelWorld",{
        support:"manga",
        title: "Accel World",
        originalTitle: "アクセルワールド",
        otherTitle: false,
        class: "Shonen",
        genre: ["Action","Drame","Romance","School Life","Science-fiction"],
        theme: ["Adolescence","Amour","Jeux-vidéo","Monde virtuel"],
        VO: 8,
        statusVO: "Termnié",
        VF: 8,
        statusVF: "Terminé",
        origine: "Japon - 2010",
        sortieVF: "2015",
        editeur: "Ototo",
        auteur: "Kawahara Reki - Aigamo Hiroyuki",
        synopsis: `An 2056. Haruyuki Arita fait partie d'un monde futuriste et impitoyable. Petit, obèse, persécuté, il préfère le monde virtuel plutôt que le réel. Pour s'adonner à ses passes-temps favoris, il utilise son Neuro-Linker, objet lui permettant d'être connecté où et quand il le souhaite sur les réseaux virtuels. La plupart du temps, il joue au squash sur son Neuro-Linker et n'en décroche que pour les cours. Un jour, il est abordé par la charmante Kuroyukihime, qui lui propose d'aller encore plus vite ! Intrigué, Haruyuki accepte. Kuroyukihime lui transmet alors le Burst Link, un programme créé pour augmenter les capacités mentales. Pourtant, il y a quelques effets secondaires...`,
        image: "asset/AccelWorld/T1.jpg",
        background: "asset/AccelWorld/Bg.jpg",
        tomes: [false,[
            {image: "asset/AccelWorld/T1.jpg" , synopsis: `Dans les années 2056, le monde est devenu totalement dépendant de toutes les technologies. Haruyuki Arita, étudiant et passionné par son jeu de squash sur Neuro-linker, n'en décroche que pour les cours. Persécuté par les autres en raison de son obésité, il n'a pas vraiment d'ami. Un jour comme les autres, une dénommée Kuroyukihime lui fait une proposition : aller encore plus vite. Curieux, Arita accepte, et accède à un programme sur-développé, le Burst-link, lui permettant d'accroître ses capacités mentales. Le voila parti pour un voyage inoubliable !`},
            {image: "asset/AccelWorld/T2.jpg" , synopsis: `Haruyuki fait désormais partie du monde accéléré sous l'apparence de « Silver Crow ». Il est confronté au mystérieux « Cyan Pile » qui poursuit ses attaques contre Princesse Kuroyuki... Mais Haru découvre alors que celui qui se cache derrière cet avatar n'est autre qu'une personne qu'il connaît très bien... Confrontation entre Silver Crow et Cyan Pile ! À ne pas rater !`},
            {image: "asset/AccelWorld/T3.jpg" , synopsis: `Haruyuki est venu à bout de Cyan Pile qui n'était autre que Takumu... Ils s'unissent alors avec Princesse Kuroyuki pour former à trois la nouvelle légion du Roi Noir, les « Nega Nebulus ». Pendant que Princesse Kuroyuki se remet de ses blessures, Takumu et Haruyuki enchaînent les combats dans le monde accéléré... Mais alors que ce dernier vient à peine de passer niveau 2, il commet une grave erreur qui met brusquement sa vie en danger ! Que va faire Haruyuki pour se sortir de cette situation des plus périlleuses ?!`},
            {image: "asset/AccelWorld/T4.jpg" , synopsis: `« Bonsoir, mon grand frère chéri ♡ ». C'est sur ces mots que la jeune sœur de Haruyuki l'accueille alors qu'il rentre de l'école. Mais la véritable identité de la petite fille n'est autre que celle du Roi Rouge du « Monde Accéléré », Scarlet Rain. Yuniko Yûzuki vient demander l'aide de Princesse Kuroyuki et de Haruyuki pour venir à bout du cinquième Chrome Disaster, un joueur dont l'âme est envoûtée par une mystérieuse armure diabolique...`},
            {image: "asset/AccelWorld/T5.jpg" , synopsis: `2026. Kazuto Kirigaya, plus connu sous le surnom de Kirito l'épéiste noir, survivant du célèbre VRMMORPG « Sword Art Online », accepte de tester la nouvelle machine d'immersion complète fabriquée par le programmeur Takeru Higa. 2047. Alors qu'il termine ses devoirs dans le « monde accéléré », Haruyuki remarque une ombre suspecte flottant non loin de lui. En vérifiant sa matching list, il se rend compte que cette ombre semble être un Burst Linker du nom de « Kirito »... `},
            {image: "asset/AccelWorld/T6.jpg" , synopsis: `Les « Nega Nebulus » sont désormais quatre, comptant désormais Chiyuri et son avatar « Lime Bell » parmi eux. Cependant, durant l'absence de Princesse Kuroyuki, Haruyuki, Takumu et Chiyuri se retrouvent face à un adversaire qui va mettre à rude épreuve leur amitié. Haruyuki se confie à Kuroyuki à son retour de voyage pour lui conter tous les détails de sa terrible bataille menée contre Seiji Nômi alias Dusk Taker ! Apparition de Sky Raker, c'est-à-dire Fûko Kurasaki, ancienne meilleure amie de Kuroyuki !`},
            {image: "asset/AccelWorld/T7.jpg" , synopsis: `Un ascenseur sur orbite qui relié à la station spatiale Hermes Cord. C'est en pénétrant par un portail apparu dans la Sky Tree de Tokyo que Haruyuki découvre sur place un immense pylône érigé vers le ciel, avec à son pied dix véhicules prêts à partir. Le compte à rebours de la course verticale Hermes Cord est lancé. Haruyuki, Princesse Kuroyuki, Takumi, Chiyuri et Fûko décident de former l'équipe des "Nega Nebulus" pour tenter de remporter cet évènement unique dans l'univers de Brain Burst.`},
            {image: "asset/AccelWorld/T8.jpg" , synopsis: `Sky Raker vient se rajouter à l'équipe des Nega Nebulus pour participer à la course verticale opposant les joueurs de différentes légions. C'est avec la hargne de vaincre que Haruyuki, Princesse Kuroyuki et leurs compagnons se lancent sur la piste. Mais c'est compter sans l'intervention de l'Association de recherche sur l'accélération qui va tout mettre en oeuvre pour mettre des bâtons dans les roues de Silver Crow… Dernier tome de l'adaptation manga de la série Accel World !`},
        ]]
    }],
    ["SPYxFAMILY",{
        support:"manga",
        title: "SPY×FAMILY",
        originalTitle: " スパイファミリー",
        otherTitle: false,
        class: "Shonen",
        genre: ["Action","Aventure","Comédie"],
        theme: ["Assassinat","Espionnage","Famille","Guerre","Mensonges","Mystère","Organisations secrètes","Politique","Super pouvoirs","Terrorisme"],
        VO: 17,
        statusVO: "En cours",
        VF: 16,
        statusVF: "En Cours",
        origine: "Japon - 2019",
        sortieVF: "2020",
        editeur: "Shueisha",
        auteur: "Endo Tatsuya",
        synopsis: `Sauvez le monde avec l'élite des agents (très) spéciaux : la famille Forger ! Une comédie d'espionnage pétillante ! Twilight, le plus grand espion du monde, doit pour sa nouvelle mission créer une famille de toutes pièces afin de pouvoir s'introduire dans la plus prestigieuse école de l'aristocratie. Totalement dépourvu d'expérience familiale, il va adopter une petite fille en ignorant qu'elle est télépathe, et s'associer à une jeune femme timide, sans se douter qu'elle est une redoutable tueuse à gages. Ce trio atypique va devoir composer pour passer inaperçu, tout en découvrant les vraies valeurs d'une famille unie et aimante.`,
        image: "asset/SPYxFAMILY/T1.jpg",
        background: "asset/SPYxFAMILY/Bg.jpg",
        tomes: [false,[
            {image: "asset/SPYxFAMILY/T1.jpg" , synopsis: `Twilight, le plus grand espion du monde, doit pour sa nouvelle mission créer une famille de toutes pièces afin de pouvoir s'introduire dans la plus prestigieuse école de l'aristocratie. Totalement dépourvu d'expérience familiale, il va adopter une petite fille en ignorant qu'elle est télépathe, et s'associer à une jeune femme timide, sans se douter qu'elle est une redoutable tueuse à gages. Ce trio atypique va devoir composer pour passer inaperçu, tout en découvrant les vraies valeurs d'une famille unie et aimante.`},
            {image: "asset/SPYxFAMILY/T2.jpg" , synopsis: `Anya a finalement réussi à intégrer l'académie d'Eden !! Mais pas le temps de souffler, car la prochaine étape de l'opération Stryx est de faire d'Anya une "élève impériale", titre donné aux plus brillants esprits de l'académie, afin d'intégrer le cercle social très fermé des "élèves impériaux" auquel Desmond appartient !`},
            {image: "asset/SPYxFAMILY/T3.jpg" , synopsis: `Pour Twilight, l'opération Strix reste une priorité absolue : approcher Donovan Desmond afin de préserver la paix entre Ostania et Westalis. Mais l'espion doit aussi gérer sa famille factice : Yor, son épouse qui cache son activité de tueuse à gages, et Anya, sa fille télépathe en difficulté à l'école. La situation se complique lorsque Yuri, le frère de Yor, leur rend une visite inattendue. Lui aussi dissimule un secret : il travaille pour la police secrète. Méfiant envers Loid, il compte bien vérifier si ce mariage soudain est réellement sincère.`},
            {image: "asset/SPYxFAMILY/T4.jpg" , synopsis: `Face à la menace d'attentat qui pèse sur un ministre de Westalis en visite à Ostania, Twilight et la cellule de WISE se mobilisent. Les conspirateurs comptent employer des chiens pour arriver à leurs fins, une curieuse coïncidence alors que la famille Forger souhaite adopter un canidé pour récompenser Anya d'avoir décroché sa première étoile à l'école Eden. Et voilà qu'Anya est enlevée par les terroristes au détour d'un salon canin ! Une fois de plus, son intervention (maladroite) comme celle (inattendue) de Yor mettront Twilight sur la bonne piste...`},
            {image: "asset/SPYxFAMILY/T5.jpg" , synopsis: `Après avoir déjoué en deux temps trois mouvements un complot terroriste (rien que ça), la (fausse) famille Forger accueille un nouveau membre dont le nom est Bond, le chien Bond. Sous son abondante pilosité canine se cache un amour infini pour Anya et plus discret, un don de prescience. Alors que l'opération «Strix» semble enfin sur les rails, les examens qu'Anya doit passer dans le cadre de sa scolarité pourraient à nouveau mettre en péril la délicate mission de Loid Forger, alias Twilight, le meilleur espion du monde...`},
            {image: "asset/SPYxFAMILY/T6.jpg" , synopsis: `Twilight doit récupérer un document susceptible de menacer la paix entre l’Est et l’Ouest. Pour cette mission, il fait équipe avec Nocturna, une espionne secrètement amoureuse de lui, lors d’un tournoi de tennis clandestin. Bien décidée à remplacer Yor comme épouse dans le cadre de l’opération Strix, Nocturna fait naître le doute chez cette dernière quant à sa place au sein de la famille. Pendant ce temps, Twilight poursuit sa mission principale et cherche toujours un moyen de se rapprocher de son insaisissable cible : Donovan Desmond.`},
            {image: "asset/SPYxFAMILY/T7.jpg" , synopsis: `Twilight, vrai espion et faux père de famille, a enfin réussi à entrer en contact avec Donovan Desmond, sa cible sur l'opération « Strix ». Mais l'homme politique reste insaisissable. Anya demeure peut-être finalement la meilleure carte à jouer pour mener à bien la mission de son « père »...`},
            {image: "asset/SPYxFAMILY/T8.jpg" , synopsis: `Gagnants d'une croisière à bord d'un paquebot de luxe, Loid et Anya embarquent sur le Princess Lorelei en même temps que Yor, chargée d'une mission ultra-dangereuse. Sous couvert de son travail à la mairie, la jeune femme doit en effet assurer la protection de l'épouse d'un mafieux assassiné...`},
            {image: "asset/SPYxFAMILY/T9.jpg" , synopsis: `En pleine mer, le paquebot Princesse Lorelei est le théâtre d'un affrontement sanglant entre Yor et les tueurs envoyés aux trousses de la femme qu'elle doit protéger. Loin d'elle, Loid et Anya se retrouvent eux aussi pris dans la tourmente. La menace d'une bombe sur le point d'exploser oblige Loid à intervenir, alors que le voici à deux doigts d'être démasqué...`},
            {image: "asset/SPYxFAMILY/T10.jpg" , synopsis: `Les mauvaises notes d’Anya compromettent l’opération Strix, mais Twilight doit poursuivre sa mission pour préserver la fragile paix entre l’Est et l’Ouest. Alors que les tensions entre les deux nations persistent, son passé refait surface. Autrefois simple enfant vivant à Ruen, il passait ses journées à jouer aux soldats avec ses amis malgré les réprimandes de son père. Mais lorsque la guerre éclate et que les premières bombes s’abattent sur sa ville, son existence bascule à jamais. Commence alors le parcours qui fera de lui l’espion Twilight.`},
            {image: "asset/SPYxFAMILY/T11.jpg" , synopsis: `Le maître espion Twilight est sans précédent lorsqu'il s'agit d'aller sous couverture dans des missions dangereuses pour le bien du monde. Mais quand il reçoit la mission ultime, se marier et avoir un enfant, il est peut-être enfin dépassé ! Menacée par la relation de Yor avec Melinda Desmond, Anya prend au sérieux son propre plan d'amitié. Sur le chemin d'une excursion dans un musée, cependant, elle et sa classe deviennent la cible d'activistes politiques qui cherchent à libérer leurs alliés politiques.`},
            {image: "asset/SPYxFAMILY/T12.jpg" , synopsis: `Après le détournement des bus scolaires de l'école Éden par des terroristes, les Forger sont heureux de se retrouver en famille. L'accalmie est cependant de courte durée, Yor s'étant mis en tête de créer des problèmes dans son couple pour que celui-ci soit " comme les autres ". Plus grave encore, un agent de Westalis s'avère être une taupe...`},
            {image: "asset/SPYxFAMILY/T13.jpg" , synopsis: `Twilight est acculé après son combat contre un agent d'Ostania. Nocturna pourra-t-elle renverser la situation, et récupérer les informations confidentielles que les deux agents sont venus chercher ? Et qu'en est-il de la crise que traverse le couple ? De son côté, Anya, qui mène l'opération " amitié ", tente de recevoir des bonbons de Damien en guise de remerciement...`},
            {image: "asset/SPYxFAMILY/T14.jpg" , synopsis: `Avec les examens de fin d'année de l'école Eden, stellas et tonitos sont en jeu ! Anya s'est donnée à fond en ostanian classique, mais pour quel résultat ? Dans sa poursuite du "plan B", elle cherche à se rapprocher de Damien et invite son camarade à danser lors du bal de l'école...`},
            {image: "asset/SPYxFAMILY/T15.jpg" , synopsis: `Twilight est acculé après son combat contre un agent d'Ostania. Nocturna pourra-t-elle renverser la situation, et récupérer les informations confidentielles que les deux agents sont venus chercher ? Et qu'en est-il de la crise que traverse le couple ? De son côté, Anya, qui mène l'opération " amitié ", tente de recevoir des bonbons de Damien en guise de remerciement...`},
            {image: "asset/SPYxFAMILY/T16.jpg" , synopsis: `Loid a l'opportunité de se renseigner lors d'une consultation de Melinda. Quels secrets de Donovan Desmond lui seront dévoilés ? À la rentrée scolaire, Anya se retrouve dans des classes différentes en fonction de son niveau. Cela l'amène à être impliquée dans un conflit international !`},
        ]]
    }],
    ["SteinsGate",{
        support:"manga",
        title: "Steins;Gate",
        originalTitle: " シュタインズ・ゲート",
        otherTitle: false,
        class: "Seinen",
        genre: ["Drame","Sciences-Fiction"],
        theme: ["Mystère","Voyage temporel"],
        VO: 3,
        statusVO: "Terminé",
        VF: 3,
        statusVF: "Terminé",
        origine: "Japon - 2009",
        sortieVF: "2020",
        editeur: "Mana Books",
        auteur: "Sarachi Yomi",
        synopsis: `Steins;Gate suit un groupe hétéroclite d'individus capables d'envoyer des SMS dans le passé. Mais au fil de leurs expériences, une organisation nommée SERN, menant ses propres recherches sur le voyage dans le temps, les traque. Commence alors un jeu dangereux du chat et de la souris pour échapper à la capture et, surtout, survivre.`,
        image: "asset/SteinsGate/T1.jpg",
        background: "asset/SteinsGate/Bg.jpg",
        tomes: [false,[
            {image: "asset/SteinsGate/T1.jpg" , synopsis: `Rintaro Okabe est un étudiant à l'imagination débridée. Savant fou autoproclamé, il passe ses journées avec deux de ses amis à inventer des objets farfelus dans son "Laboratoire des gadgets futuristes". Lorsqu'ils branchent un téléphone portable sur un micro-ondes, ils découvrent avec stupeur qu'ils ont la possibilité d'envoyer des messages dans le passé ! Ce grand pouvoir implique une responsabilité colossale, mais qui peut prédire ce qu'en feront ces trois otaku ?`},
            {image: "asset/SteinsGate/T2.jpg" , synopsis: `Le laboratoire des gadgets futuristes compte désormais sept membres réunis autour du télé-micro-ondes. Après quelques expériences aux conséquences imprévisibles, Rintaro commence à craindre que les choses ne lui échappent. L'étrange menace anonyme qu'il a reçue par message ne fait rien pour calmer son inquiétude... Et, alors que le fonctionnement de la machine devient soudain plus clair, il n'est plus possible de fermer les yeux sur le danger potentiel qu'elle représente...`},
            {image: "asset/SteinsGate/T3.jpg" , synopsis: `Rintaro enchaîne sans répit les voyages temporels dans l'espoir de sauver Mayuri. Et le seul moyen d'y parvenir, c'est d'annuler une à une toutes les modifications que les D-mails ont engendrées... De lourds sacrifices seront nécessaires, mais il faut à tout prix récupérer l'IBN 5100 afin d'effacer les informations collectées par le SERN, puis retourner à la ligne temporelle originelle, celle où le télé-micro-ondes n'a pas été utilisé comme machine à remonter le temps...`},
        ]]
    }],
    ["BlueBox",{
        support:"manga",
        title: "Blue Box",
        originalTitle: "アオのハコ",
        otherTitle: "Ao no Hako",
        class: "Shonen",
        genre: ["Comédie","Romance","Slice of Life"],
        theme: ["Adolescence","Amitié","Amour","Badminton","Basketball","Club","School life","Sport"],
        VO: 26,
        statusVO: "En cours",
        VF: 12,
        statusVF: "En cours",
        origine: "Japon - 2021",
        sortieVF: "2023",
        editeur: "Delcourt/Tonkam",
        auteur: "Miura Koji",
        synopsis: `Taiki Inomata, un lycéen passionné de badminton, est secrètement amoureux de Chinatsu Kano, une élève plus âgée et talentueuse membre de l'équipe de basket-ball. Chaque matin, il la croise lors de leurs entraînements respectifs et admire sa détermination autant que ses qualités sportives.
Un événement inattendu va cependant bouleverser leur quotidien : Chinatsu se retrouve à vivre sous le même toit que Taiki. Entre leurs ambitions sportives, la pression des compétitions et leurs sentiments qui évoluent progressivement, les deux jeunes doivent apprendre à gérer une relation de plus en plus importante.`,
        image: "asset/BlueBox/T1.jpg",
        background: "asset/BlueBox/Bg.jpg",
        tomes: [false,[
            {image: "asset/BlueBox/T1.jpg" , synopsis: `Taiki Inomata est un membre de l'équipe masculine de badminton de l'école Eimei. Il est amoureux d'une fille de l'équipe de basketball, Chinatsu Kano, aux côtés de qui, il s'entraîne tous les matins dans le gymnase. Cependant, sa relation avec Chinatsu prendra un tournant lors d'un jour de printemps.`},
            {image: "asset/BlueBox/T2.jpg" , synopsis: `Taiki va devoir surmonter l'entraînement spartiate imposé par Haryû, son nouveau partenaire de double. Le jeune lycéen va débuter le tournoi régional avec brio, jusqu'à l'arrivée d'un nouveau rival avide de le battre pour obtenir le numéro de téléphone de Chinatsu... La défaite n'est plus une option pour Taiki qui donnera tout, aussi bien en amour qu'en badminton !`},
            {image: "asset/BlueBox/T3.jpg" , synopsis: `Alors que Hina échoue plusieurs fois dans son sport, on apprend que son père était un grand sportifs du nom de Hirohiko Chono. Et ce sont de lourdes tâches qui reposent sur les épaules de l'amie de Taiki ! Alors que tout aller s'améliorer, en sortant du gymnase elle se blesse à la cheville et c'est Taiki qui vient à son secours.`},
            {image: "asset/BlueBox/T4.jpg" , synopsis: `Taiki Inomata, membre du club de badminton, a eu le coup de foudre pour Chinatsu Kano, la star du club de basket de son établissement. Il s'entraîne à ses côtés tous les matin. Sa relation avec Chinatsu va prendre un tournant totalement inédit lorsqu'un jour de printemps, une nouvelle des plus déconcertantes va lui offrir une opportunité inespérée de conquérir sa belle.`},
            {image: "asset/BlueBox/T5.jpg" , synopsis: `Après être tombé par hasard sur Chinatsu lors du feu d'artifice, Taiki aide cette dernière à retrouver la mère d'une enfant perdue, avant de retourner auprès de Hina qui attend son retour avec impatience... Quelques jours plus tard, c'est enfin au tour de Haryû d'affronter Hyôdô, son éternel rival, lors du tournoi national de badminton ! Tout s'accélère pour les élèves du lycée Eimei, tant sur le plan sportif qu'amoureux...`},
            {image: "asset/BlueBox/T6.jpg" , synopsis: `Nous sommes le 26 août, la fin des vacances d'été approche. Chinatsu est sous pression après avoir été nommée vice-capitaine de l'équipe de basket-ball. Voyant que célébrer son anniversaire avec ses amis ne suffit pas à lui remonter le moral, Taiki lui propose d'aller à la mer en train, pour lui changer les idées. Ce voyage à deux va prendre des allures d'escapade de fin d'été...`},
            {image: "asset/BlueBox/T7.jpg" , synopsis: `À la suite d'une rencontre amicale organisée avec le lycée Sajikawa, Taiki se remet en question. Le badiste n'a toujours pas digéré sa défaite lors des éliminatoires qui l'a empêché d'être qualifié au tournoi national. L'heure est enfin venue pour lui de prendre sa revanche contre Yusa, son rival. Même face à un mur, Taiki continue de s'accrocher avec ténacité pour surmonter son échec passé !`},
            {image: "asset/BlueBox/T8.jpg" , synopsis: `Taiki doit remplacer au pied levé l'élève censée jouer le rôle du prince charmant dans la pièce organisée par sa classe. En dépit de son trac, il fait de son mieux, mais un accident inattendu se produit... Après un festival culturel mouvementé, le quotidien au lycée reprend tranquillement son cours, jusqu'à ce qu'une nouvelle recrue vienne faire souffler un vent de fraîcheur sur le gymnase...`},
            {image: "asset/BlueBox/T9.jpg" , synopsis: `Le stage d'automne a débuté. Taiki a beau endurer des entraînements encore plus intenses que d'habitude, son esprit est totalement accaparé par Chinatsu, la fille de ses rêves, mais aussi par Hina, qui lui a avoué ses sentiments. D'ailleurs, c'est avec cette dernière qu'il se retrouve seul, dans le gymnase, lors du feu de camp organisé pour la dernière soirée de leu éprouvant séjour...`},
            {image: "asset/BlueBox/T10.jpg" , synopsis: `Après un rendez-vous interrompu par Matsuoka, alors qu'ils admirent le coucher de soleil sur le chemin du retour, Taiki et Chinatsu tombent par hasard sur Yumeka, une ancienne coéquipière du collège de Chinatsu. Mais contre toute attente, Yumeka profite de ces retrouvailles inattendues pour se montrer particulièrement dure avec cette dernière. Les deux amies d'enfance semblent cacher un lourd passé ...`},
            {image: "asset/BlueBox/T11.jpg" , synopsis: `Grâce au billet que lui a offert Taiki, Yumeka assiste au match de basket de Chinatsu. Voir son ancienne coéquipière se battre sous ses yeux ravive en elle des souvenirs de l'époque où elle adorait le basket. Après son match, Chinatsu se rend au gymnase habituel pour voir Taiki, qui est occupé à décorer un sapin de Noël ...`},
            {image: "asset/BlueBox/T12.jpg" , synopsis: `Bien que Chinatsu et Taiki passent les fêtes de fin d'année chacun de leur côté, cette courte séparation ne les empêche pas de penser l'un à l'autre en permanence. Lors d'un séjour au ski avec ses camarades du club de badminton, Taiki reçoit un message de Chinatsu et réalise alors qu'il aura peut être l'occasion de la revoir plus tôt que prévu ...`},
        ]]
    }],
    ["Bloom",{
        support:"manga",
        title: "Bloom",
        originalTitle: "薫る花は凛と咲く",
        otherTitle: "Kaoru Hana wa Rin to Saku - The Fragrant Flower Blooms With Dignity - Kaoruhana",
        class: "Shonen",
        genre: ["Romance","Slice of Life"],
        theme: ["Amour","Gastronomie","École","School life"],
        VO: 23,
        statusVO: "En cours",
        VF: 11,
        statusVF: "En cours",
        origine: "Japon - 2021",
        sortieVF: "2025",
        editeur: "nobi nobi!",
        auteur: "Mikami Saka",
        synopsis: `Au cœur d'une banlieue japonaise, se dressent face à face deux établissements que tout oppose : Chidori, le lycée public pour garçons, réunit les pires cancres de la ville, tandis que le prestigieux Kikyô rassemble les esprits les plus brillants des filles de bonne famille.
Donnant régulièrement un coup de main à la pâtisserie familiale, Rintarô Tsumugi, élève à Chidori, sympathise avec l'une de ses clientes régulières, Kaoruko Waguri. Alors qu'il sent peu à peu un lien se tisser entre eux, le lycéen apprend que la jeune fille fréquente Kikyô et que comme tous les élèves de ces établissements, ils sont supposés se haïr mutuellement ! La rivalité entre leurs lycées est-elle forcément signe de fatalité ?`,
        image: "asset/Bloom/T1.jpg",
        background: "asset/Bloom/Bg.jpg",
        tomes: [false,[
            {image: "asset/Bloom/T1.jpg" , synopsis: `Rintarô Tsumugi, 16 ans, est élève au lycée public pour garçons de Chidori, réputé pour n'accueillir que des cancres. À cause de sa grande taille et de ses cheveux décolorés, il a tendance à faire fuir les gens malgré lui. Alors qu'il donne un coup de main à la pâtisserie familiale, il rencontre la rayonnante Kaoruko Waguri qui, à sa grande surprise, n'est pas du tout intimidé par lui, bien au contraire... Malheureusement, il découvre rapidement qu'elle étudie à Kikyô, un prestigieux lycée rassemblant les jeunes filles les plus brillantes qui vouent une haine profonde envers leurs voisins d'en face : les étudiants de Chidori !`},
            {image: "asset/Bloom/T2.jpg" , synopsis: `Rintarô a fait la connaissance de Kaoruko Waguri, qui fréquente l'établissement des filles de bonne famille, Kikyô. Le jeune homme est d'abord perplexe devant l'attitude de Kaoruko, qui lui fait face avec une grande sincérité. Pour la première fois, il va peu à peu oser s'ouvrir à la jeune fille... Mais malgré le rapprochement qui s'opère entre les deux lycéens, le fossé entre leurs écoles reste encore profond : Subaru Hoshina, une amie de Kaoruko semble d'ailleurs être particulièrement remontée contre Rintarô...`},
            {image: "asset/Bloom/T3.jpg" , synopsis: `Rintarô a tissé des liens avec Kaoruko Waguri, qui fréquente l'établissement des filles de bonne famille, Kikyô. Malgré tout un monde qui les sépare, les deux jeunes trouvent une forme de réconfort dans les moments passés l'un avec l'autre. Mais si la distance entre Rintarô et Kaoruko se réduit peu à peu, le mur entre leurs deux lycées demeure, et Rintarô se garde toujours de parler de cette relation à ses amis, ce qui finit par créer un malentendu entre eux... Un soir après les cours, alors qu'il avait pris son courage à deux mains pour proposer à Kaoruko et son amie Subaru de se voir, une bande de lycéens vient le provoquer. Comment réussir à éviter la menace d'une bagarre ou pire... qu'ils s'en prennent aux filles?`},
            {image: "asset/Bloom/T4.jpg" , synopsis: `Bien qu'il reste préoccupé par le fossé qui existe entre les deux écoles, Rintarô décide de présenter Kaoruko et Subaru à ses amis, et de les inviter chez lui. En confiance, il livre un récit de son enfance et leurs liens s'approfondissent. Si sa mère se retrouve chamboulée à l'évocation de ces souvenirs, de son côté, Rintarô s'apprête à vivre pleinement un été placé sous le signe de l'amitié !`},
            {image: "asset/Bloom/T5.jpg" , synopsis: `Les vacances d'été commencent, l'occasion propice pour passer du temps entre amis. Mais, prenant conscience de ses sentiments à l'égard de la jeune fille, Rintarô perd ses moyens lorsqu'il apprend que l'anniversaire de Kaoruko approche à grands pas. Après des heures de réflexion, il décide de lui préparer un gâteau pour exprimer sa gratitude. Kaoruko saura-t-elle apprécier ce cadeau empreint de sincérité ?`},
            {image: "asset/Bloom/T6.jpg" , synopsis: `Appréciant de plus en plus les moments passés en compagnie de la jeune fille, notre héros commence bientôt à s'apercevoir de ses sentiments naissants à son égard. Un jour, alors qu'ils se retrouvent tous les deux, submergé par ses sentiments à l'égard de Kaoruko, les mots lui échappent... et Rintarô lui déclare sa flamme. Suite à cet épisode, il est bien déterminé à lui transmettre tout ce qu'il ressent pour elle. L'amour sincère entre ces deux lycéens que tout oppose, et pourtant si proches, finira-t-il par éclore ?`},
            {image: "asset/Bloom/T7.jpg" , synopsis: `Persuadé d'avoir mis la jeune fille mal à l'aise depuis qu'il lui a déclaré sa flamme, Rintaro cherche par tous les moyens à sauver leur relation. Et alors que les vacances d'été mémorables touchent à leur fin, une fête d'anniversaire est organisée pour Natsuzawa. Rintaro décide de lui préparer un gâteau mais il craint les réactions de ses amis...`},
            {image: "asset/Bloom/T8.jpg" , synopsis: `Tandis que l'été qui marque le début de leur relation touche bientôt à sa fin, Rintarô donne rendez-vous à Waguri pour lui offrir un gâteau en récompense de son dur labeur estival. Le jour de leur tête-à-tête, le jeune homme s'attendait à tout... sauf à se retrouver soudain invité à dîner chez la famille de sa petite amie ! L'aspirant pâtissier en profite alors pour transmettre ses bonnes intentions à la mère de Waguri...`},
            {image: "asset/Bloom/T9.jpg" , synopsis: `Rintaro et Kaoruko franchissent une étape importante dans leur relation lorsqu'elle présente officiellement Rintaro à sa mère et à son frère. Cependant, avant qu'ils ne puissent aller plus loin, les amies de Kaoruko, membres de Kikyo, les surprennent en plein rendez-vous. À l'école, Subaru tente de rassurer les autres filles au sujet de leurs amis Chidori, allant même jusqu'à leur proposer de rencontrer les garçons. Rintaro, désireux lui aussi d'apporter son soutien, trouve un moyen très visible de le manifester.`},
            {image: "asset/Bloom/T10.jpg" , synopsis: `Subaru convainc les filles qui ont aperçu Kaoruko et Rintaro lors de leur rendez-vous de rencontrer les garçons de Chidori. Si la rencontre se déroule plutôt bien au début, une crise de colère d'Ayu menace les progrès réalisés. Heureusement, le groupe parvient à calmer le jeu, et maintenant que leurs amis ont été présentés les uns aux autres, Kaoruko et Rintaro peuvent franchir une nouvelle étape dans leur relation : aller chez Rintaro ensemble !`},
            {image: "asset/Bloom/T11.jpg" , synopsis: `Alors que Kaoruko se présente officiellement comme la petite amie de Rintaro à ses parents, les garçons de Chidori, Subaru et Madoka profitent d'une journée ensemble à la salle d'arcade – une belle illustration de leur amitié, au-delà des murs de l'école. L'automne arrive et, avec la baisse des températures, un événement scolaire très attendu se profile : le voyage scolaire ! Chidori et Kikyo visiteront peut-être des endroits différents, mais cela suffira-t-il à empêcher Kaoruko et Rintaro de partager de nouvelles expériences ?`},
        ]]
    }],
];

// ------------------------------ Trier le tableau par ordre alphabétique -----------------------------------------------
const mangaOrdered = mangaList.sort((a, b) =>
    a[0].localeCompare(b[0], undefined, {
        sensitivity: "base"
    })
);