const animeList=[
    ["swordArtOnline",{
        support:"anime",
        title: "Sword Art Online",
        originalTitle: "ソードアート・オンライン",
        otherTitle: false,
        type: "Série",
        class: "Shonen",
        genre: ["Action","Aventure","Comédie","Isekai","Romance","Sciences-fiction"],
        theme: ["Adolescence","Amour","Jeux-vidéo","Monde virtuel"],
        episodes: 76,
        saisons: 3,
        status: "En cours",
        date: "Eté 2012",
        studio: "A-1 Pictures",
        diffusion: "ADN",
        synopsis: `Cette série raconte les aventures de Kirito qui se retrouve piégé dans un jeu massivement multi-joueurs, Sword Art Online. En 2022, l'humanité a réussi à créer une réalité virtuelle. Grâce à un casque, les humains peuvent se plonger entièrement dans le monde virtuel en étant comme déconnectés de la réalité, et Sword Art Online est le premier MMORPG a utiliser ce système. Mais voila que le premier jour de jeu, 10 000 personnes se retrouvent piégées dans cette réalité virtuelle par son créateur : Akihiko Kayaba. Le seul moyen d'en sortir est de finir le jeu. Mais ce ne sera pas facile de sortir de ce monde virtuel puisque si un joueur perd la partie, il meurt également dans la vraie vie. Kirito décide alors de partir à la conquête du jeu en solo, avec pour avantage le fait de faire partie des 1 000 ex-bêta-testeurs, mais arrivera-t-il à terminer les 99 donjons et leurs boss ? "Même si cela semble être un jeu vidéo, ce n'est pas un jeu" Akihiko Kayaba - Créateur de "Sword Art Online"`,
        image: "../img/SwordArtOnline/S1.jpg",
        background:"../img/SwordArtOnline/Bg.jpg",
        listSaisons:[
            {title: "Saison 1" , image: "../img/SwordArtOnline/S1.jpg" , synopsis: `En 2022, Sword Art Online devient le premier MMORPG utilisant une technologie de réalité virtuelle permettant une immersion totale. Mais dès son lancement, 10 000 joueurs se retrouvent piégés par son créateur, Akihiko Kayaba. Pour retrouver leur liberté, ils devront terminer le jeu, avec une terrible règle : mourir dans SAO signifie mourir dans la réalité. Kirito, ancien bêta-testeur, décide de partir seul à la conquête des 100 étages d'Aincrad et de leurs redoutables boss. Parviendra-t-il à terminer le jeu et à libérer tous les joueurs ?`},
            {title: "Saison 2" , image: "../img/SwordArtOnline/S2.jpg" , synopsis: `Après sa victoire face à Sugou Nobuyuki, Kirito retrouve enfin sa paisible vie de lycéen. Mais plusieurs morts mystérieuses viennent bientôt troubler son quotidien : des joueurs de Gun Gale Online seraient décédés dans la réalité après avoir été abattus dans le jeu. Sollicité par Kikuoka Seijirô pour enquêter, Kirito plonge dans ce nouvel univers dominé par les armes à feu. Il devra participer au tournoi Bullet of Bullets et retrouver Death Gun, un mystérieux joueur qui semble capable de tuer ses victimes à travers le monde virtuel.`},
            {title: "Saison 3 - Alicization" , image: "../img/SwordArtOnline/S3.jpg" , synopsis: `À la demande de Seijirô Kikuoka, Kazuto teste le Soul Translator, une nouvelle technologie développée par Rath qui lui permet d'accéder à l'Underworld. Il y rencontre Eugeo et Alice, deux enfants avec lesquels il se lie d'amitié, avant qu'Alice ne soit emmenée pour avoir enfreint les lois de ce monde. Plus tard, Kazuto est grièvement blessé dans la réalité par un ancien membre de Laughing Coffin. Pour le sauver, il est plongé dans l'Underworld, où plusieurs années se sont écoulées et où il retrouve Eugeo, désormais devenu un jeune homme.`},            
        ],
    }],
    ["TonikakuKawaii",{
        support:"anime",
        title: "Tonikaku Kawaii",
        originalTitle: "トニカクカワイイ",
        otherTitle: "Fly Me to The Moon",
        type: "Série",
        class: "Shonen",
        genre: ["Comédie","Romance","Slice of Life"],
        theme: ["Adolescence","Amour","Mariage","Mystère"],
        episodes: 24,
        saisons: 2,
        status: "En cours",
        date: "Automne 2020",
        studio: "SEVEN·ARCS",
        diffusion: "Crunchyroll",
        synopsis: `Le prénom de Nasa Yuzaki, un collégien studieux, s'écrit avec le kanji de «Nuit étoilée», mais il se prononce «Nasa». Pour ne plus que l'on se moque de son nom étrange, il s'est juré de devenir une personne importante.
Durant une nuit enneigée, il aperçoit une jeune fille dont il tombe tout de suite amoureux. Cependant, alors qu'il ne fait plus attention à la route, il se fait renverser par un camion.
Tsukasa, la jeune fille qu'il regardait, le sauve et Nasa profite de cette situation pour lui avouer ses sentiments. La jeune fille accepte de sortir avec lui mais à une seule condition : ils doivent se marier !
Plusieurs années après cet événement, Tsukasa vient sonner chez Nasa pour tenir la promesse qu'elle a faite. Ainsi commence la vie à deux de nos jeunes mariés !`,
        image: "../img/TonikakuKawaii/S1.jpg",
        background:"../img/TonikakuKawaii/Bg.jpg",
        listSaisons: [
            {title: "Saison 1", image: "../img/TonikakuKawaii/S1.jpg", synopsis: `Après avoir frôlé la mort dans un accident, Nasa rencontre Tsukasa, une mystérieuse jeune fille dont il tombe immédiatement amoureux. Lorsqu'il lui avoue ses sentiments, celle-ci accepte de sortir avec lui à une seule condition : qu'ils se marient. Quelques années plus tard, Tsukasa réapparaît à sa porte et tient sa promesse. À peine réunis, les deux jeunes mariés découvrent alors ensemble les joies et les embarras de la vie de couple, tandis que Nasa cherche encore à percer les nombreux mystères qui entourent sa nouvelle épouse.`},
            {title: "Saison 2", image: "../img/TonikakuKawaii/S2.jpg", synopsis: `Désormais bien installés dans leur vie de jeunes mariés, Nasa et Tsukasa continuent de découvrir les petits bonheurs du quotidien à deux. Entre rendez-vous amoureux, nouvelles rencontres et moments passés avec leurs proches, leur relation devient peu à peu plus profonde. La question d'une cérémonie de mariage commence également à se poser. Mais derrière cette vie paisible, Tsukasa conserve encore des secrets sur son passé, tandis que Nasa réalise chaque jour un peu plus ce que signifie partager sa vie avec celle qu'il aime.`},
        ],
    }],
    ["DeathNote",{
        support:"anime",
        title: "Death Note",
        originalTitle: "デスノート",
        otherTitle: false,
        type: "Série",
        class: "Seinen",
        genre: ["Drame","Psychologique","Surnaturel","Thriller"],
        theme: ["Détective","Mort","Police","Shinigami","Mystère","Tragique"],
        episodes: 37,
        saisons: 1,
        status: "Terminé",
        date: "Automne 2006",
        studio: "Madhouse",
        diffusion: "YouTube - Netflix - Crunchyroll",
        synopsis: `Light Yagami, un jeune étudiant surdoué, ramasse un jour le "Death Note", un carnet tenu auparavant par un shinigami (Dieu de la mort), Ryuk, qui apparemment s'ennuyait dans son monde.
Il suffit d'écrire le nom d'une personne dans ce carnet, et celle-ci meurt (selon certaines conditions que le shinigami expliquera à Light lors de leur rencontre).
C'est ainsi qu'avec le "Death Note" entre les mains, Light décide de débarrasser la planète de tous les criminels pour en faire un monde juste, un monde parfait.
Cependant, qui est-il pour juger les gens ? Il devient donc le pire criminel recherché de toute la planète...`,
        image: "../img/DeathNote/S1.jpg",
        background:"../img/DeathNote/Bg.jpg",
        listSaisons: false,
    }],
    ["AccelWorld",{
        support:"anime",
        title: "Accel World",
        originalTitle: "アクセル・ワールド",
        otherTitle: false,
        type: "Série",
        class: "Shonen",
        genre: ["Action","Drame","Romance","School Life","Science-fiction"],
        theme: ["Adolescence","Amour","Jeux-vidéo","Monde virtuel"],
        episodes: 24,
        saisons: 1,
        status: "Terminé",
        date: "printemps 2012",
        studio: "SUNRISE",
        diffusion: "Wakanim (Licence expirée)",
        synopsis: `L'histoire se passe au cours de l'année 2046, dans un monde où le virtuel est omniprésent, notamment grâce aux "neuro-linkers".
Le personnage principal se nomme Haruyuki, ou plus simplement Haru pour ses proches, et est le souffre douleur des caïds de son lycée. Son seul plaisir est un jeu virtuel ressemblant au squash, dans lequel il excelle... jusqu'au jour où il est battu par une mystérieuse jeune fille. Cette dernière s'avère être Kuroyukihime, une des membres du Conseil des élèves.
Si elle a battu son score, c'est pour lui demander de l'aide. Haru étant quelque peu hésitant, elle lui présente un curieux jeu, "Brain Burst", qui s'avère être bien plus qu'un simple jeu.
En effet, ceux qui possèdent ce logiciel sont capables de se transférer dans un monde virtuel où 1 seconde du monde réel correspond à 16 minutes et 40 secondes. Cela s'appelle "accélérer".
Mais pour conserver ce pouvoir, il faut combattre, et gagner des points. L'aventure de Haru dans ce nouveau monde ne fait que commencer.`,
        image: "../img/AccelWorld/S1.jpg",
        background:"../img/AccelWorld/Bg.jpg",
        listSaisons: false,
    }],
    ["LookBack",{
        support:"anime",
        title: "Look Back",
        originalTitle: "ルックバック",
        otherTitle: false,
        type: "Film",
        class: "Shonen",
        genre: ["Drame","Slice of Life"],
        theme: ["Adolescence","Amitié","Solitude","School Life"],
        episodes: 1,
        saisons: 1,
        status: "Terminé",
        date: "Eté 2024",
        studio: "Studio Durian",
        diffusion: "Amazon Prime Video",
        synopsis: `Fujino est une adolescente qui dessine des manga pour le journal de l'école. Son art fait d'elle la star de sa classe mais un jour, elle apprend que Kyomoto, une élève qui refuse de venir à l'école, aimerait elle aussi soumettre un manga pour le journal...`,
        image: "../img/LookBack/Film.jpg",
        background:"../img/LookBack/Bg.jpg",
        listSaisons: false,
    }],
    ["TheAncientMagusBride",{
        support:"anime",
        title: "The Ancient Magus Bride",
        originalTitle: "魔法使いの嫁",
        otherTitle:  "Mahō Tsukai no Yome",
        type: "Série",
        class: "Shonen",
        genre: ["Aventure","Drame","Fantastique","Slice of Life"],
        theme: ["Dragons","Magie","Sorcellerie","Mystère"],
        episodes: 48,
        saisons: 2,
        status: "Terminé",
        date: "automne 2017",
        studio: "Wit Studio",
        diffusion: "Crunchyroll",
        synopsis: `Fujino est une adolescente qui dessine des manga pour le journal de l'école. Son art fait d'elle la star de sa classe mais un jour, elle apprend que Kyomoto, une élève qui refuse de venir à l'école, aimerait elle aussi soumettre un manga pour le journal...`,
        image: "../img/TheAncientMagusBride/S1.jpg",
        background:"../img/TheAncientMagusBride/Bg.jpg",
        listSaisons: [
            {title: "Saison 1", image: "../img/TheAncientMagusBride/S1.jpg", synopsis: `Il s'agit d'une série animée se basant sur le manga Mahou Tsukai no Yome de Yamazaki Koré. Chise Hatori est une esclave jusqu'au jour où sa route croise celle du Magus Elias Ainsworth. Ce dernier décèle en elle un don certain pour la magie et décide de l'acheter pour faire d'elle son apprentie. Elle devra également l'épouser dans le futur.`},
            {title: "Saison 2", image: "../img/TheAncientMagusBride/S2.jpg", synopsis: `Grâce à Elias et tous ceux qu'elle a rencontré, Chise continue d'appréhender le monde magique dans lequel elle évolue désormais, parfois avec difficultés.`},
        ],
    }],
    ["SPYxFAMILY",{
        support:"anime",
        title: "SPY×FAMILY",
        originalTitle: "スパイファミリー",
        otherTitle:  false,
        type: "Série",
        class: "Shonen",
        genre: ["Action","Aventure","Comédie"],
        theme: ["Assassinat","Espionnage","Famille","Guerre","Mensonges","Mystère","Organisations secrètes","Politique","Super pouvoirs","Terrorisme"],
        episodes: 50,
        saisons: 3,
        status: "Terminé",
        date: "Printemps 2022",
        studio: "CloverWorks - Wit Studio",
        diffusion: "Crunchyroll - Netflix - Amazon Prime Video",
        synopsis: `Sauvez le monde avec l'élite des agents (très) spéciaux : la famille Forger ! Une comédie d'espionnage pétillante ! Twilight, le plus grand espion du monde, doit pour sa nouvelle mission créer une famille de toutes pièces afin de pouvoir s'introduire dans la plus prestigieuse école de l'aristocratie. Totalement dépourvu d'expérience familiale, il va adopter une petite fille en ignorant qu'elle est télépathe, et s'associer à une jeune femme timide, sans se douter qu'elle est une redoutable tueuse à gages. Ce trio atypique va devoir composer pour passer inaperçu, tout en découvrant les vraies valeurs d'une famille unie et aimante.`,
        image: "../img/SPYxFAMILY/S1.jpg",
        background:"../img/SPYxFAMILY/Bg.jpg",
        listSaisons: [
            {title: "Saison 1", image: "../img/SPYxFAMILY/S1.jpg", synopsis: `Afin de préserver la paix entre Westalis et Ostania, l'espion Twilight reçoit une mission capitale : approcher Donovan Desmond. Sous l'identité de Loid Forger, il doit fonder une famille et inscrire son enfant à la prestigieuse académie Eden. Il adopte alors Anya et épouse Yor, sans savoir que la première est télépathe et que la seconde est une redoutable tueuse à gages. Chacun cachant sa véritable identité, cette famille improvisée va devoir apprendre à vivre ensemble tandis que Loid poursuit secrètement l'opération Strix.`},
            {title: "Saison 2", image: "../img/SPYxFAMILY/S2.jpg", synopsis: `La famille Forger poursuit son quotidien mouvementé tandis que Loid continue l'opération Strix et qu'Anya tente de se rapprocher de Damian à l'académie Eden. De son côté, Yor commence à s'interroger sur sa double vie lorsqu'une nouvelle mission lui est confiée : protéger une femme et son enfant traqués par de nombreux assassins à bord d'un luxueux paquebot. Par un incroyable hasard, Loid et Anya embarquent eux aussi pour la croisière. Yor devra alors accomplir sa mission sans révéler à sa famille qu'elle est la redoutable Princesse Ibara.`},
            {title: "Saison 3", image: "../img/SPYxFAMILY/S3.jpg", synopsis: `L'opération Strix se poursuit et Anya doit toujours gagner suffisamment d'Étoiles Stella pour permettre à Loid d'approcher Donovan Desmond. Mais le passé de Twilight refait surface, dévoilant les événements qui l'ont conduit à devenir espion et son désir de créer un monde où les enfants ne pleurent plus. Pendant ce temps, Anya se retrouve au cœur d'une situation autrement plus dangereuse lorsque son bus scolaire est détourné par le Cirque Rouge. Les Forger vont une nouvelle fois être confrontés aux tensions qui menacent la fragile paix entre les deux pays.`},
        ],
    }],
    ["SteinsGate",{
        support:"anime",
        title: "Steins;gate",
        originalTitle: "シュタインズ ゲート",
        otherTitle:  false,
        type: "Série",
        class: "Seinen",
        genre: ["Drame","Sciences-Fiction"],
        theme: ["Mystère","Voyage temporel"],
        episodes: 24,
        saisons: 1,
        status: "Terminé",
        date: "Printemps 2011",
        studio: "WHITE FOX",
        diffusion: "Amazon Prime Video - ADN",
        synopsis: `Dans le quartier Otaku qu'est Akihabara, un groupe d'amis modifient leur micro-ondes de manière à en faire un dispositif qui leur permet d'envoyer des emails dans le passé.
Une organisation, la SERN, a mené différentes recherches à propos des voyages temporels. 
À présent, le groupe, ayant effectué plusieurs expériences diverses, doit absolument éviter de se faire capturer par cette organisation qui les perturbe en les traquant...`,
        image: "../img/SteinsGate/S1.jpg",
        background:"../img/SteinsGate/Bg.jpg",
        listSaisons: false,
    }],
    ["BlueBox",{
        support:"anime",
        title: "Blue Box",
        originalTitle: "アオのハコ",
        otherTitle:  "Ao no Hako",
        type: "Série",
        class: "Shonen",
        genre: ["Comédie","Romance","Slice of Life"],
        theme: ["Adolescence","Amitié","Amour","Badminton","Basketball","Club","School life","Sport"],
        episodes: 25,
        saisons: 1,
        status: "En cours",
        date: "Automne 2024",
        studio: "Telecom Animation Film",
        diffusion: "Netflix",
        synopsis: `Taiki Inomata, membre du club de badminton, a eu le coup de foudre pour Chinatsu Kano, la star du club de basket de son établissement. Il s'entraîne à ses côtés tous les matin. Sa relation avec Chinatsu va prendre un tournant totalement inédit lorsqu'un jour de printemps, une nouvelle des plus déconcertantes va lui offrir une opportunité inespérée de conquérir sa belle.`,
        image: "../img/BlueBox/S1.jpg",
        background:"../img/BlueBox/Bg.jpg",
        listSaisons: false,
    }],
    ["Bloom",{
        support:"anime",
        title: "Bloom",
        originalTitle: "薫る花は凛と咲く",
        otherTitle:  "Kaoru Hana wa Rin to Saku - The Fragrant Flower Blooms With Dignity - Kaoruhana",
        type: "Série",
       class: "Shonen",
        genre: ["Romance","Slice of Life"],
        theme: ["Amour","Gastronomie","École","School life"],
        episodes: 13,
        saisons: 1,
        status: "En cours",
        date: "Eté 2025",
        studio: "CloverWorks",
        diffusion: "Netflix",
        synopsis: `L'histoire se déroule dans une ville où deux écoles sont tristement célèbres pour être en conflit permanent. D'un côté, il y a le lycée Chidori, une école pour garçons fréquentée principalement par des élèves aux notes accablantes et de l'autre, le lycée pour filles Kikyo dont la plupart des étudiantes sont issues de familles riches et prestigieuses.Un jour, alors que Rintaro Tsumugi, élève du lycée Chidori à l'allure imposante aide à la pâtisserie de sa famille, il fait la rencontre d'une cliente nommée Kaoruko Waguri. Rintaro apprécie le temps qu'il passe avec Kaoruko car elle ne le juge pas pour son apparence. Cependant, Rintaro découvre rapidement que Kaoruko est en réalité une étudiante de Kikyo. Cette révélation marque le début d'une histoire mouvementée pour les deux jeunes gens, qui doivent lutter contre les obstacles imposés par leur école et leur entourage pour tenter de trouver leur propre voie !`,
        image: "../img/Bloom/S1.jpg",
        background:"../img/Bloom/Bg.jpg",
        listSaisons: false,
    }],
    ["JunLaVoixDuCoeur",{
        support:"anime",
        title: "Jun, la voix du cœur",
        originalTitle: "心が叫びたがってるんだ。",
        otherTitle:  "Kokoro ga Sakebitagatterun Da. -  The Anthem of the Heart - Beautiful Word, Beautiful World - Kokosake",
        type: "Film",
        class: "Shonen",
        genre: ["Drame","Romance","Slice of Life"],
        theme: ["Quotidien","École"],
        episodes: 1,
        saisons: 1,
        status: "Terminé",
        date: "Eté 2015",
        studio: "A-1 Pictures",
        diffusion: "ADN (License expirée)",
        synopsis: `Jun est une fille dont les mots ont été scellés. Avant, elle était une fille très heureuse, mais à cause d'une certaine chose qu'elle a dite lorsqu'elle était très jeune, sa famille s'est déchirée. Un jour, la fée des œufs est apparue devant elle et a scellé sa capacité à parler afin de l'empêcher de blesser autrui. Depuis cette expérience traumatisante, Jun vit dans l'ombre de la foule. Mais, un jour, elle est nommée pour devenir membre exécutif d'un groupe scolaire. Par-dessus le marché, Jun est aussi désignée pour jouer le rôle principal dans leur comédie musicale...`,
        image: "../img/JunLaVoixDuCoeur/Film.jpg",
        background:"../img/JunLaVoixDuCoeur/Bg.jpg",
        listSaisons: false,
    }],
    ["SaikiKusuoNoPsyNan",{
        support:"anime",
        title: "Saiki Kusuo no Ψ Nan",
        originalTitle: " 斉木楠雄のサイ難",
        otherTitle: "Saiki Kusuo no PSY Nan - Saiki Kusuo no Sainan -  The Disastrous Life of Saiki K.",
        type:  "Série",
        class: "Shonen",
        genre: ["Comédie","Slice of Life","Surnaturel"],
        theme: ["Quotidien","École","Médium","School life","Super pouvoirs"],
        episodes: 48,
        saisons: 2,
        status: "Terminé",
        date: "Hiver 2018",
        studio: "Egg Firm - J.C. Staff",
        diffusion: "Netflix",
        synopsis: `Kusuo Saiki est un étudiant de 16 ans qui possède plusieurs dons surnaturels, dont la télépathie et la télékinésie. Des pouvoirs dont n'importe qui rêverait, mais qui cause à notre héros un certain nombres de problèmes... Kusuo tente malgré tout de mener une vie normale.`,
        image: "../img/SaikiKusuoNoPsyNan/S1.jpg",
        background:"../img/SaikiKusuoNoPsyNan/Bg.jpg",
        listSaisons: [
            {title: "Saison 1", image:"../img/SaikiKusuoNoPsyNan/S1.jpg", synopsis: `Kusuo Saiki est un lycéen doté de pouvoirs psychiques extraordinaires, qu'il cherche à garder secrets afin de mener une vie normale. Télépathie, télékinésie, téléportation… aucun pouvoir ne lui permet pourtant d'échapper aux situations absurdes provoquées par ses camarades, entre Nendô, Kaidô, Teruhashi et bien d'autres. Alors qu'il tente constamment de rester discret, son quotidien devient de plus en plus mouvementé.`},
            {title: "Saison 2", image:"../img/SaikiKusuoNoPsyNan/S2.jpg", synopsis: `Kusuo poursuit son quotidien de lycéen en espérant enfin vivre tranquillement, mais ses pouvoirs et ses camarades ne lui laissent aucun répit. Entre l'arrivée de nouveaux personnages, notamment une autre personne aux pouvoirs psychiques, et les nombreuses mésaventures de son entourage, Kusuo doit une nouvelle fois tout faire pour rester discret. Et cette fois, une menace bien plus importante pourrait mettre en danger l'avenir du Japon.`},
        ],
    }],
    ["RollOverAndDie",{
        support:"anime",
        title: "Roll Over and Die",
        originalTitle: "「お前ごときが魔王に勝てると思うな」と勇者パーティを追放されたので、王都で気ままに暮らしたい",
        otherTitle: `Jamais tu ne vaincras le Roi démon ! - "Omae Gotoki ga Maō ni Kateru to Omou na" to Yūsha Party wo Tsuihō Sareta no de, Ōto de Kimama ni Kurashitai - ROLL OVER AND DIE: I Will Fight for an Ordinary Life with My Love and Cursed Sword!`,
        type:  "Série",
        class: "Shonen",
        genre: ["Action","Aventure","Drame","Fantastique","Slice of Life"],
        theme: ["Gore","Magie","Malédiction","Monstres","Shôjo-aï","Vengeance"],
        episodes: 12,
        saisons: 1,
        status: "En cours",
        date: "Hiver 2026",
        studio: "A.C.G.T.",
        diffusion: "Crunchyroll",
        synopsis: `Flum Apricot n'a jamais été destinée à être une héroïne. Malgré des statistiques proches de zéro et un pouvoir qu'elle ne peut même pas utiliser, elle se retrouve membre d'un groupe de héros. Mais la vie de Flum sombre lorsque Jean Inteige, le célèbre sage du groupe, décide qu'elle est un poids mort et s'arrange pour qu'elle soit vendue comme esclave.
Jetée aux monstres pour qu'ils la dévorent afin de divertir son maître, Flum fait le choix désespéré de s'emparer d'une arme maudite... Suite à ce choix, quelque chose de nouveau s'éveille en elle. Ainsi débute le récit sombre sur la quête sanglante d'une femme pour retrouver sa vie !`,
        image: "../img/RollOverAndDie/S1.jpg",
        background:"../img/RollOverAndDie/Bg.jpg",
        listSaisons: false,
    }],
    ["Mashle",{
        support:"anime",
        title: "Mashle",
        originalTitle: "マッシュル",
        otherTitle: "Mashle - Magic and Muscles",
        type:  "Série",
        class: "Shonen",
        genre: ["Action","Aventure","Comédie","Fantastique",],
        theme: ["Arts martiaux","Combats","Magie"],
        episodes: 24,
        saisons: 2,
        status: "En cours",
        date: "Printemps 2023",
        studio: "A-1 Pictures",
        diffusion: "Crunchyroll",
        synopsis: `L'histoire se déroule dans un royaume où la magie est omniprésente et est considérée comme un don divin. Dans cette société, le rang social est déterminé par le potentiel magique et ceux qui n'en disposent pas sont punis de mort.
Mash Burnedead est né sans pouvoirs magiques mais il a survécu caché dans une épaisse forêt. Le jour où son secret est découvert, il se voit proposer un marché : intégrer Easton, la prestigieuse académie de magie, et y obtenir le titre d'élu divin. Pour retrouver sa vie tranquille, Mash accepte.`,
        image: "../img/Mashle/S1.jpg",
        background:"../img/Mashle/Bg.jpg",
        listSaisons: [
            {title: "Saison 1", image:"../img/Mashle/S1.jpg", synopsis: ``},
            {title: "Saison 2", image:"../img/Mashle/S2.jpg", synopsis: ``},
        ],
    }],
    ["LaVoieDuTablier",{
        support:"anime",
        title: "La Voie du Tablier",
        originalTitle: "極主夫道",
        otherTitle: "Gokushufudō - The Way of the Househusband",
        type:  "Série",
        class: "Seinen",
        genre: ["Comédie","Slice of Life"],
        theme: ["Gastronomie","Homme au foyer","Mariage","Quotidien","Yakuza"],
        episodes: 15,
        saisons: 2,
        status: "En cours",
        date: "Printemps 2021",
        studio: "J.C. Staff",
        diffusion: "Netflix",
        synopsis: `Tatsu, l'immortel, le légendaire yakuza qui a vaincu à lui seul un gang rival avec un tuyau de plomb, est connu pour autant effrayer les policiers endurcis que les criminels les plus vicieux. Peu de temps après sa disparition, il refait surface avec un léger changement de profession. Désormais équipé d'un tablier, Tatsu a renoncé à la violence et tente de gagner honnêtement sa vie en tant que mari au foyer.
Tout en s'adaptant aux tâches banales ménagères, Tatsu découvre qu'être un mari au foyer comporte ses propres défis, du champ de bataille connu sous le nom de ventes au supermarché aux échecs dans la cuisine. Bien qu'il vive paisiblement, les malentendus semblent le suivre à gauche et à droite.
Nous allons donc suivre le quotidien d'un ex-yakuza qui a laissé sa dangereuse vie derrière lui pour devenir un mari au foyer.`,
        image: "../img/LaVoieDuTablier/S1.jpg",
        background:"../img/LaVoieDuTablier/Bg.jpg",
        listSaisons: [
            {title: "Saison 1", image:"../img/LaVoieDuTablier/S1.jpg", synopsis: ``},
            {title: "Saison 2", image:"../img/LaVoieDuTablier/S2.jpg", synopsis: ``},
        ],
    }],
    ["Orange",{
        support:"anime",
        title: "Orange",
        originalTitle: "オレンジ",
        otherTitle: false,
        type:  "Série",
        class: "Shojo",
        genre: ["Drame","Romance","Science-Fiction","Slice of Life","Surnaturel"],
        theme: ["Amitié","Amour","École","Futur","Mystère","Poésie","Quotidien","School Life","Tragique"],
        episodes: 13,
        saisons: 1,
        status: "Terminé",
        date: "Eté 2016",
        studio: "Telecom Animation Film - TMS Entertainment",
        diffusion: "Viki",
        synopsis: `Un jour de printemps, Naho Takamiya, âgée de 16 ans, reçoit une étrange lettre signée de son propre nom, datant de dix ans dans le futur. Elle croit d'abord bien sûr à une plaisanterie. Cependant, en commençant à lire la lettre et les détails qui y sont écrits, elle se rend compte au fur et à mesure que des évènements relatés se sont réalisés tels que l'arrivée du nouvel étudiant, Kakeru Naruse, qui est assis à côté d'elle en classe.
Dans la lettre, la Naho du futur parle de ses nombreux regrets, sous-entendant à la Naho du présent de prendre de meilleures décisions, en particulier concernant Kakeru. En effet, le jeune garçon n'est plus de ce monde dans le futur. La Naho du futur lui demande donc de veiller sur lui...`,
        image: "../img/Orange/S1.jpg",
        background:"../img/Orange/Bg.jpg",
        listSaisons: false,
    }],
    ["KingsGame",{
        support:"anime",
        title: `King's Game "The Animation"`,
        originalTitle: "王様ゲーム The Animation",
        otherTitle: "Ō-sama The Animation",
        type:  "Série",
        class: "Seinen",
        genre: ["Drame","Horreur","Surnaturel","Thriller"],
        theme: ["Mystère","Survival game"],
        episodes: 12,
        saisons: 1,
        status: "Terminé",
        date: "Automne 2017",
        studio: "Seven",
        diffusion: "Crunchyroll",
        synopsis: `L'histoire se centre sur une classe entière de 32 lycéens qui reçoivent un étrange message venant d'une personne se faisant appeler le "Roi". Le message contient des ordres que les lycéens doivent accomplir sous peine de mourir.
Au fur et à mesure que les jours passent, les ordres du "Roi" deviennent de plus en plus extrêmes ...`,
        image: "../img/KingsGame/S1.jpg",
        background:"../img/KingsGame/Bg.jpg",
        listSaisons: false,
    }],
    ["NazoNoKanojoX",{
        support:"anime",
        title: "Nazo no Kanojo X",
        originalTitle: "謎の彼女X",
        otherTitle: "Mysterious Girlfriend X",
        type:  "Série",
        class: "Seinen",
        genre: ["Ecchi","Romance","Surnaturel"],
        theme: ["École","Mystère","School Life"],
        episodes: 13,
        saisons: 1,
        status: "Terminé",
        date: "Printemps 2012",
        studio: "Hoods Entertainment",
        diffusion: "?",
        synopsis: `TSUBAKI Akira, un lycéen, voit débarquer une nouvelle élève dans sa classe : la mystérieuse URABE Mikoto. Dès son arrivée, celle-ci ne manque pas de se faire remarquer, par son caractère discret et son attitude atypique. Après les cours, alors que la jeune fille est affalée sur son bureau, Akira la tire de son sommeil, et se rend compte que Mikoto, en dormant, a laissé une trace de sa salive sur son pupitre. Quand celle-ci rentre chez elle, une idée pour le moins étrange traverse l'esprit du garçon, qui se met alors à goûter sa salive. Peu après, il tombe malade, et Mikoto lui rend visite chez lui pour lui expliquer qu'il est devenu... accro à sa salive ! Selon elle, il est amoureux, et pour éviter que le jeune homme ne fasse d'autres crises de manque, il doit goûter un peu de celle-ci chaque jour. C'est ainsi que Akira, réellement sous son charme, est amené à sortir avec Mikoto. S'ensuivent alors de drôles d'aventures liées par le "fil" de la salive...`,
        image: "../img/NazoNoKanojoX/S1.jpg",
        background:"../img/NazoNoKanojoX/Bg.jpg",
        listSaisons: false,
    }],
    ["MiraiNikki",{
        support:"anime",
        title: "Mirai Nikki",
        originalTitle: "未来日記",
        otherTitle: "Mirai Nikki, Le journal du futur - Future Diary",
        type:  "Série",
        class: "Shonen",
        genre: ["Action","Fantastique","Horreur","Psychologique","Romance"],
        theme: ["Assassinat","Crime","Détective","Gore","Mort","Survival game","Terrorisme","Vengeance","Voyage temporel"],
        episodes: 26,
        saisons: 1,
        status: "Terminé",
        date: "Automne 2011",
        studio: "asread",
        diffusion: "Crunchyroll",
        synopsis: `L'histoire nous entraîne dans le quotidien de Yukiteru Amano un jeune adolescent solitaire se renfermant sur lui-même détaché de la réalité. Il préfère se réfugier dans son monde avec ses amis imaginaires plutôt que de s'en faire de vrais dans la réalité.
Seulement un jour, sa vie va basculer, lorsque Deus l'une de ses nombreuses créations se révèle être plus qu'un être imaginaire. Deus offre alors à Yukiteru la possibilité de voir dans le "futur" seulement, Deus est un dieu qui décide de céder sa place à celui qui survivra à un jeu de survie impitoyable.`,
        image: "../img/MiraiNikki/S1.jpg",
        background:"../img/MiraiNikki/Bg.jpg",
        listSaisons: false,
    }],
    ["MushokuTensei",{
        support:"anime",
        title: "Mushoku Tensei",
        originalTitle: "無職転生 ～異世界行ったら本気だす～",
        otherTitle: "Mushoku Tensei, Isekai Ittara Honki Dasu - Mushoku Tensei, Jobless Reincarnation",
        type:  "Série",
        class: "Seinen",
        genre: ["Action","Ecchi","Fantastique","Isekai","Romance","Slice of Life"],
        theme: ["Autre monde","Harem","Magie","Réincarnation"],
        episodes: 63,
        saisons: 3,
        status: "En cours",
        date: "Hiver 2021",
        studio: "Studio Bind",
        diffusion: "Crunchyroll - Netflix",
        synopsis: `L'histoire nous entraîne dans le quotidien d'un NEET qui vient d'être chassé de chez ses parents. Ayant le moral au plus bas, il pense au suicide. Jusqu'au jour où il aperçoit une ancienne camarade de classe sur le point de se faire renverser. D'un geste héroïque, il la pousse et se fait renverser à sa place. Suite à ça, il meurt puis se retrouve réincarné dans un monde fantaisiste.
Il se réincarne dans le corps d'un enfant du nom de Rudeus Greyrat. Il est le fils d'un épéiste nommé Paul Greyrat et d'une ancienne aventurière nommée Zenith Greyrat.
Bien décidé à faire quelque chose de sa nouvelle vie en tant que Rudeus, il va essayer de devenir le plus grand magicien de l'histoire.`,
        image: "../img/MushokuTensei/S1.jpg",
        background:"../img/MushokuTensei/Bg.jpg",
        listSaisons: [
            {title: "Saison 1", image:"../img/MushokuTensei/S1.jpg", synopsis: ``},
            {title: "Saison 2", image:"../img/MushokuTensei/S2.jpg", synopsis: ``},
            {title: "Saison 2", image:"../img/MushokuTensei/S3.jpg", synopsis: ``},
        ],
    }],
];


// -------------------------------------- Trier le tableau par ordre alphabétique --------------------------------

const animeOrdered = animeList.sort((a, b) =>
    a[0].localeCompare(b[0], undefined, {
        sensitivity: "base"
    })
);