const animeList=[
    ["swordArtOnline",{
        support:"anime",
        date: 20200919,
        title: "Sword Art Online",
        originalTitle: "ソードアート・オンライン",
        otherTitle: false,
        type: "Série",
        class: "Shonen",
        genre: ["Action","Aventure","Comédie","Isekai","Romance","Science-Fiction"],
        theme: ["Adolescence","Amour","Jeux-vidéo","Monde virtuel"],
        episodes: 76,
        saisons: 3,
        status: "En cours",
        sortie: "Eté 2012",
        studio: ["A-1 Pictures"],
        diffusion: ["ADN"],
        synopsis: `Cette série raconte les aventures de Kirito qui se retrouve piégé dans un jeu massivement multi-joueurs, Sword Art Online. En 2022, l'humanité a réussi à créer une réalité virtuelle. Grâce à un casque, les humains peuvent se plonger entièrement dans le monde virtuel en étant comme déconnectés de la réalité, et Sword Art Online est le premier MMORPG a utiliser ce système. Mais voila que le premier jour de jeu, 10 000 personnes se retrouvent piégées dans cette réalité virtuelle par son créateur : Akihiko Kayaba. Le seul moyen d'en sortir est de finir le jeu. Mais ce ne sera pas facile de sortir de ce monde virtuel puisque si un joueur perd la partie, il meurt également dans la vraie vie. Kirito décide alors de partir à la conquête du jeu en solo, avec pour avantage le fait de faire partie des 1 000 ex-bêta-testeurs, mais arrivera-t-il à terminer les 99 donjons et leurs boss ? "Même si cela semble être un jeu vidéo, ce n'est pas un jeu" Akihiko Kayaba - Créateur de "Sword Art Online"`,
        image: "../img/SwordArtOnline/S1.jpg",
        background:"../img/SwordArtOnline/Bg.jpg",
        listSaisons:[
            {title: "Saison 1" , image: "../img/SwordArtOnline/S1.jpg" , synopsis: `En 2022, Sword Art Online devient le premier MMORPG utilisant une technologie de réalité virtuelle permettant une immersion totale. Mais dès son lancement, 10 000 joueurs se retrouvent piégés par son créateur, Akihiko Kayaba. Pour retrouver leur liberté, ils devront terminer le jeu, avec une terrible règle : mourir dans SAO signifie mourir dans la réalité. Kirito, ancien bêta-testeur, décide de partir seul à la conquête des 100 étages d'Aincrad et de leurs redoutables boss. Parviendra-t-il à terminer le jeu et à libérer tous les joueurs ?`},
            {title: "Saison 2" , image: "../img/SwordArtOnline/S2.jpg" , synopsis: `Après sa victoire face à Sugou Nobuyuki, Kirito retrouve enfin sa paisible vie de lycéen. Mais plusieurs morts mystérieuses viennent bientôt troubler son quotidien : des joueurs de Gun Gale Online seraient décédés dans la réalité après avoir été abattus dans le jeu. Sollicité par Kikuoka Seijirô pour enquêter, Kirito plonge dans ce nouvel univers dominé par les armes à feu. Il devra participer au tournoi Bullet of Bullets et retrouver Death Gun, un mystérieux joueur qui semble capable de tuer ses victimes à travers le monde virtuel.`},
            {title: "Saison 3 - Alicization" , image: "../img/SwordArtOnline/S3.jpg" , synopsis: `À la demande de Seijirô Kikuoka, Kazuto teste le Soul Translator, une nouvelle technologie développée par Rath qui lui permet d'accéder à l'Underworld. Il y rencontre Eugeo et Alice, deux enfants avec lesquels il se lie d'amitié, avant qu'Alice ne soit emmenée pour avoir enfreint les lois de ce monde. Plus tard, Kazuto est grièvement blessé dans la réalité par un ancien membre de Laughing Coffin. Pour le sauver, il est plongé dans l'Underworld, où plusieurs années se sont écoulées et où il retrouve Eugeo, désormais devenu un jeune homme.`},            
        ],
    }],
    ["TonikakuKawaii",{
        support:"anime",
        date: 20230823,
        title: "Tonikaku Kawaii",
        originalTitle: "トニカクカワイイ",
        otherTitle: "Fly Me to The Moon",
        type: "Série",
        class: "Shonen",
        genre: ["Comédie","Romance","Slice of Life"],
        theme: ["Adolescence","Amour","Mariage","Mystère"],
        episodes: 24,
        saisons: 2,
        status: "En cours",
        sortie: "Automne 2020",
        studio: ["SEVEN·ARCS"],
        diffusion: ["Crunchyroll"],
        synopsis: `Le prénom de Nasa Yuzaki, un collégien studieux, s'écrit avec le kanji de «Nuit étoilée», mais il se prononce «Nasa». Pour ne plus que l'on se moque de son nom étrange, il s'est juré de devenir une personne importante.
Durant une nuit enneigée, il aperçoit une jeune fille dont il tombe tout de suite amoureux. Cependant, alors qu'il ne fait plus attention à la route, il se fait renverser par un camion.
Tsukasa, la jeune fille qu'il regardait, le sauve et Nasa profite de cette situation pour lui avouer ses sentiments. La jeune fille accepte de sortir avec lui mais à une seule condition : ils doivent se marier !
Plusieurs années après cet événement, Tsukasa vient sonner chez Nasa pour tenir la promesse qu'elle a faite. Ainsi commence la vie à deux de nos jeunes mariés !`,
        image: "../img/TonikakuKawaii/S1.jpg",
        background:"../img/TonikakuKawaii/Bg.jpg",
        listSaisons: [
            {title: "Saison 1", image: "../img/TonikakuKawaii/S1.jpg", synopsis: `Après avoir frôlé la mort dans un accident, Nasa rencontre Tsukasa, une mystérieuse jeune fille dont il tombe immédiatement amoureux. Lorsqu'il lui avoue ses sentiments, celle-ci accepte de sortir avec lui à une seule condition : qu'ils se marient. Quelques années plus tard, Tsukasa réapparaît à sa porte et tient sa promesse. À peine réunis, les deux jeunes mariés découvrent alors ensemble les joies et les embarras de la vie de couple, tandis que Nasa cherche encore à percer les nombreux mystères qui entourent sa nouvelle épouse.`},
            {title: "Saison 2", image: "../img/TonikakuKawaii/S2.jpg", synopsis: `Désormais bien installés dans leur vie de jeunes mariés, Nasa et Tsukasa continuent de découvrir les petits bonheurs du quotidien à deux. Entre rendez-vous amoureux, nouvelles rencontres et moments passés avec leurs proches, leur relation devient peu à peu plus profonde. La question d'une cérémonie de mariage commence également à se poser. Mais derrière cette vie paisible, Tsukasa conserve encore des secrets sur son passé, tandis que Nasa réalise chaque jour un peu plus ce que signifie partager sa vie avec celle qu'il aime.`},
            {title: "High School Days", image: "../img/TonikakuKawaii/S2.5.jpg", synopsis: `Il s'agit d'une série d'ONA basés sur la série Tonikaku Kawaii. L'histoire est inédite. Nasa va donner un cours dans un lycée pour fille, ce qui inquiète Tsukasa.`},
        ],
    }],
    ["DeathNote",{
        support:"anime",
        date: 20070627,
        title: "Death Note",
        originalTitle: "デスノート",
        otherTitle: false,
        type: "Série",
        class: "Seinen",
        genre: ["Drame","Psychologique","Surnaturel","Thriller"],
        theme: ["Détective","Mort","Police","Shinigami","Mystère","Tragique"],
        episodes: 37,
        saisons: 1,
        status: "Terminé",
        sortie: "Automne 2006",
        studio: ["Madhouse"],
        diffusion: ["YouTube","Netflix","Crunchyroll"],
        synopsis: `Light Yagami, un jeune étudiant surdoué, ramasse un jour le "Death Note", un carnet tenu auparavant par un shinigami (Dieu de la mort), Ryuk, qui apparemment s'ennuyait dans son monde.
Il suffit d'écrire le nom d'une personne dans ce carnet, et celle-ci meurt (selon certaines conditions que le shinigami expliquera à Light lors de leur rencontre).
C'est ainsi qu'avec le "Death Note" entre les mains, Light décide de débarrasser la planète de tous les criminels pour en faire un monde juste, un monde parfait.
Cependant, qui est-il pour juger les gens ? Il devient donc le pire criminel recherché de toute la planète...`,
        image: "../img/DeathNote/S1.jpg",
        background:"../img/DeathNote/Bg.jpg",
        listSaisons: false,
    }],
    ["AccelWorld",{
        support:"anime",
        date: 20120922,
        title: "Accel World",
        originalTitle: "アクセル・ワールド",
        otherTitle: false,
        type: "Série",
        class: "Shonen",
        genre: ["Action","Drame","Romance","School Life","Science-fiction"],
        theme: ["Adolescence","Amour","Jeux-vidéo","Monde virtuel"],
        episodes: 24,
        saisons: 1,
        status: "Terminé",
        sortie: "printemps 2012",
        studio: ["SUNRISE"],
        diffusion: ["?"],
        synopsis: `L'histoire se passe au cours de l'année 2046, dans un monde où le virtuel est omniprésent, notamment grâce aux "neuro-linkers".
Le personnage principal se nomme Haruyuki, ou plus simplement Haru pour ses proches, et est le souffre douleur des caïds de son lycée. Son seul plaisir est un jeu virtuel ressemblant au squash, dans lequel il excelle... jusqu'au jour où il est battu par une mystérieuse jeune fille. Cette dernière s'avère être Kuroyukihime, une des membres du Conseil des élèves.
Si elle a battu son score, c'est pour lui demander de l'aide. Haru étant quelque peu hésitant, elle lui présente un curieux jeu, "Brain Burst", qui s'avère être bien plus qu'un simple jeu.
En effet, ceux qui possèdent ce logiciel sont capables de se transférer dans un monde virtuel où 1 seconde du monde réel correspond à 16 minutes et 40 secondes. Cela s'appelle "accélérer".
Mais pour conserver ce pouvoir, il faut combattre, et gagner des points. L'aventure de Haru dans ce nouveau monde ne fait que commencer.`,
        image: "../img/AccelWorld/S1.jpg",
        background:"../img/AccelWorld/Bg.jpg",
        listSaisons: false,
    }],
    ["LookBack",{
        support:"anime",
        date: 20240628,
        title: "Look Back",
        originalTitle: "ルックバック",
        otherTitle: false,
        type: "Film",
        class: "Shonen",
        genre: ["Drame","Slice of Life"],
        theme: ["Adolescence","Amitié","Solitude","School Life"],
        episodes: 1,
        saisons: 1,
        status: "Terminé",
        sortie: "Eté 2024",
        studio: ["Studio Durian"],
        diffusion: ["Amazon Prime Video"],
        synopsis: `Fujino est une adolescente qui dessine des manga pour le journal de l'école. Son art fait d'elle la star de sa classe mais un jour, elle apprend que Kyomoto, une élève qui refuse de venir à l'école, aimerait elle aussi soumettre un manga pour le journal...`,
        image: "../img/LookBack/Film.jpg",
        background:"../img/LookBack/Bg.jpg",
        listSaisons: false,
    }],
    ["TheAncientMagusBride",{
        support:"anime",
        date: 20230622,
        title: "The Ancient Magus Bride",
        originalTitle: "魔法使いの嫁",
        otherTitle:  "Mahō Tsukai no Yome",
        type: "Série",
        class: "Shonen",
        genre: ["Aventure","Drame","Fantastique","Slice of Life"],
        theme: ["Dragons","Magie","Sorcellerie","Mystère"],
        episodes: 48,
        saisons: 2,
        status: "Terminé",
        sortie: "automne 2017",
        studio: ["Wit Studio"],
        diffusion: ["Crunchyroll"],
        synopsis: `Fujino est une adolescente qui dessine des manga pour le journal de l'école. Son art fait d'elle la star de sa classe mais un jour, elle apprend que Kyomoto, une élève qui refuse de venir à l'école, aimerait elle aussi soumettre un manga pour le journal...`,
        image: "../img/TheAncientMagusBride/S1.jpg",
        background:"../img/TheAncientMagusBride/Bg.jpg",
        listSaisons: [
            {title: "Saison 1", image: "../img/TheAncientMagusBride/S1.jpg", synopsis: `Il s'agit d'une série animée se basant sur le manga Mahou Tsukai no Yome de Yamazaki Koré. Chise Hatori est une esclave jusqu'au jour où sa route croise celle du Magus Elias Ainsworth. Ce dernier décèle en elle un don certain pour la magie et décide de l'acheter pour faire d'elle son apprentie. Elle devra également l'épouser dans le futur.`},
            {title: "Saison 2", image: "../img/TheAncientMagusBride/S2.jpg", synopsis: `Grâce à Elias et tous ceux qu'elle a rencontré, Chise continue d'appréhender le monde magique dans lequel elle évolue désormais, parfois avec difficultés.`},
        ],
    }],
    ["SPYxFAMILY",{
        support:"anime",
        date: 20251227,
        title: "SPY×FAMILY",
        originalTitle: "スパイファミリー",
        otherTitle:  false,
        type: "Série",
        class: "Shonen",
        genre: ["Action","Aventure","Comédie"],
        theme: ["Assassinat","Espionnage","Famille","Guerre","Mensonges","Mystère","Organisations secrètes","Politique","Super pouvoirs","Terrorisme"],
        episodes: 50,
        saisons: 3,
        status: "Terminé",
        sortie: "Printemps 2022",
        studio: ["CloverWorks","Wit Studio"],
        diffusion: ["Crunchyroll","Netflix","Amazon Prime Video"],
        synopsis: `Sauvez le monde avec l'élite des agents (très) spéciaux : la famille Forger ! Une comédie d'espionnage pétillante ! Twilight, le plus grand espion du monde, doit pour sa nouvelle mission créer une famille de toutes pièces afin de pouvoir s'introduire dans la plus prestigieuse école de l'aristocratie. Totalement dépourvu d'expérience familiale, il va adopter une petite fille en ignorant qu'elle est télépathe, et s'associer à une jeune femme timide, sans se douter qu'elle est une redoutable tueuse à gages. Ce trio atypique va devoir composer pour passer inaperçu, tout en découvrant les vraies valeurs d'une famille unie et aimante.`,
        image: "../img/SPYxFAMILY/S1.jpg",
        background:"../img/SPYxFAMILY/Bg.jpg",
        listSaisons: [
            {title: "Saison 1", image: "../img/SPYxFAMILY/S1.jpg", synopsis: `Afin de préserver la paix entre Westalis et Ostania, l'espion Twilight reçoit une mission capitale : approcher Donovan Desmond. Sous l'identité de Loid Forger, il doit fonder une famille et inscrire son enfant à la prestigieuse académie Eden. Il adopte alors Anya et épouse Yor, sans savoir que la première est télépathe et que la seconde est une redoutable tueuse à gages. Chacun cachant sa véritable identité, cette famille improvisée va devoir apprendre à vivre ensemble tandis que Loid poursuit secrètement l'opération Strix.`},
            {title: "Saison 2", image: "../img/SPYxFAMILY/S2.jpg", synopsis: `La famille Forger poursuit son quotidien mouvementé tandis que Loid continue l'opération Strix et qu'Anya tente de se rapprocher de Damian à l'académie Eden. De son côté, Yor commence à s'interroger sur sa double vie lorsqu'une nouvelle mission lui est confiée : protéger une femme et son enfant traqués par de nombreux assassins à bord d'un luxueux paquebot. Par un incroyable hasard, Loid et Anya embarquent eux aussi pour la croisière. Yor devra alors accomplir sa mission sans révéler à sa famille qu'elle est la redoutable Princesse Ibara.`},
            {title: "Saison 3", image: "../img/SPYxFAMILY/S3.jpg", synopsis: `L'opération Strix se poursuit et Anya doit toujours gagner suffisamment d'Étoiles Stella pour permettre à Loid d'approcher Donovan Desmond. Mais le passé de Twilight refait surface, dévoilant les événements qui l'ont conduit à devenir espion et son désir de créer un monde où les enfants ne pleurent plus. Pendant ce temps, Anya se retrouve au cœur d'une situation autrement plus dangereuse lorsque son bus scolaire est détourné par le Cirque Rouge. Les Forger vont une nouvelle fois être confrontés aux tensions qui menacent la fragile paix entre les deux pays.`},
        ],
    }],
    ["SteinsGate",{
        support:"anime",
        date: 20110913,
        title: "Steins;gate",
        originalTitle: "シュタインズ ゲート",
        otherTitle:  false,
        type: "Série",
        class: "Seinen",
        genre: ["Drame","Sciences-Fiction"],
        theme: ["Mystère","Voyage temporel"],
        episodes: 24,
        saisons: 1,
        status: "Terminé",
        sortie: "Printemps 2011",
        studio: ["WHITE FOX"],
        diffusion: ["Amazon Prime Video","ADN"],
        synopsis: `Dans le quartier Otaku qu'est Akihabara, un groupe d'amis modifient leur micro-ondes de manière à en faire un dispositif qui leur permet d'envoyer des emails dans le passé.
Une organisation, la SERN, a mené différentes recherches à propos des voyages temporels. 
À présent, le groupe, ayant effectué plusieurs expériences diverses, doit absolument éviter de se faire capturer par cette organisation qui les perturbe en les traquant...`,
        image: "../img/SteinsGate/S1.jpg",
        background:"../img/SteinsGate/Bg.jpg",
        listSaisons: false,
    }],
    ["BlueBox",{
        support:"anime",
        date: 20250327,
        title: "Blue Box",
        originalTitle: "アオのハコ",
        otherTitle:  "Ao no Hako",
        type: "Série",
        class: "Shonen",
        genre: ["Comédie","Romance","Slice of Life"],
        theme: ["Adolescence","Amitié","Amour","Badminton","Basketball","Club","School life","Sport"],
        episodes: 25,
        saisons: 1,
        status: "En cours",
        sortie: "Automne 2024",
        studio: ["Telecom Animation Film"],
        diffusion: ["Netflix"],
        synopsis: `Taiki Inomata, membre du club de badminton, a eu le coup de foudre pour Chinatsu Kano, la star du club de basket de son établissement. Il s'entraîne à ses côtés tous les matin. Sa relation avec Chinatsu va prendre un tournant totalement inédit lorsqu'un jour de printemps, une nouvelle des plus déconcertantes va lui offrir une opportunité inespérée de conquérir sa belle.`,
        image: "../img/BlueBox/S1.jpg",
        background:"../img/BlueBox/Bg.jpg",
        listSaisons: false,
    }],
    ["Bloom",{
        support:"anime",
        date: 20250927,
        title: "Bloom",
        originalTitle: "薫る花は凛と咲く",
        otherTitle:  "Kaoru Hana wa Rin to Saku - The Fragrant Flower Blooms With Dignity - Kaoruhana",
        type: "Série",
       class: "Shonen",
        genre: ["Romance","Slice of Life"],
        theme: ["Amour","Gastronomie","École","School life"],
        episodes: 13,
        saisons: 1,
        status: "En cours",
        sortie: "Eté 2025",
        studio: ["CloverWorks"],
        diffusion: ["Netflix"],
        synopsis: `L'histoire se déroule dans une ville où deux écoles sont tristement célèbres pour être en conflit permanent. D'un côté, il y a le lycée Chidori, une école pour garçons fréquentée principalement par des élèves aux notes accablantes et de l'autre, le lycée pour filles Kikyo dont la plupart des étudiantes sont issues de familles riches et prestigieuses.Un jour, alors que Rintaro Tsumugi, élève du lycée Chidori à l'allure imposante aide à la pâtisserie de sa famille, il fait la rencontre d'une cliente nommée Kaoruko Waguri. Rintaro apprécie le temps qu'il passe avec Kaoruko car elle ne le juge pas pour son apparence. Cependant, Rintaro découvre rapidement que Kaoruko est en réalité une étudiante de Kikyo. Cette révélation marque le début d'une histoire mouvementée pour les deux jeunes gens, qui doivent lutter contre les obstacles imposés par leur école et leur entourage pour tenter de trouver leur propre voie !`,
        image: "../img/Bloom/S1.jpg",
        background:"../img/Bloom/Bg.jpg",
        listSaisons: false,
    }],
    ["JunLaVoixDuCoeur",{
        support:"anime",
        date: 20170913,
        title: "Jun, la voix du cœur",
        originalTitle: "心が叫びたがってるんだ。",
        otherTitle:  "Kokoro ga Sakebitagatterun Da. -  The Anthem of the Heart - Beautiful Word, Beautiful World - Kokosake",
        type: "Film",
        class: "Shonen",
        genre: ["Drame","Romance","Slice of Life"],
        theme: ["Quotidien","École"],
        episodes: 1,
        saisons: 1,
        status: "Terminé",
        sortie: "Eté 2015",
        studio: ["A-1 Pictures"],
        diffusion: ["?"],
        synopsis: `Jun est une fille dont les mots ont été scellés. Avant, elle était une fille très heureuse, mais à cause d'une certaine chose qu'elle a dite lorsqu'elle était très jeune, sa famille s'est déchirée. Un jour, la fée des œufs est apparue devant elle et a scellé sa capacité à parler afin de l'empêcher de blesser autrui. Depuis cette expérience traumatisante, Jun vit dans l'ombre de la foule. Mais, un jour, elle est nommée pour devenir membre exécutif d'un groupe scolaire. Par-dessus le marché, Jun est aussi désignée pour jouer le rôle principal dans leur comédie musicale...`,
        image: "../img/JunLaVoixDuCoeur/Film.jpg",
        background:"../img/JunLaVoixDuCoeur/Bg.jpg",
        listSaisons: false,
    }],
    ["SaikiKusuoNoPsyNan",{
        support:"anime",
        date: 20161226,
        title: "Saiki Kusuo no Ψ Nan",
        originalTitle: " 斉木楠雄のサイ難",
        otherTitle: "Saiki Kusuo no PSY Nan - Saiki Kusuo no Sainan -  The Disastrous Life of Saiki K.",
        type:  "Série",
        class: "Shonen",
        genre: ["Comédie","Slice of Life","Surnaturel"],
        theme: ["Quotidien","École","Médium","School life","Super pouvoirs"],
        episodes: 48,
        saisons: 2,
        status: "Terminé",
        sortie: "Hiver 2018",
        studio: ["Egg Firm","J.C. Staff"],
        diffusion: ["Netflix"],
        synopsis: `Kusuo Saiki est un étudiant de 16 ans qui possède plusieurs dons surnaturels, dont la télépathie et la télékinésie. Des pouvoirs dont n'importe qui rêverait, mais qui cause à notre héros un certain nombres de problèmes... Kusuo tente malgré tout de mener une vie normale.`,
        image: "../img/SaikiKusuoNoPsyNan/S1.jpg",
        background:"../img/SaikiKusuoNoPsyNan/Bg.jpg",
        listSaisons: [
            {title: "Saison 1", image:"../img/SaikiKusuoNoPsyNan/S1.jpg", synopsis: `Kusuo Saiki est un lycéen doté de pouvoirs psychiques extraordinaires, qu'il cherche à garder secrets afin de mener une vie normale. Télépathie, télékinésie, téléportation… aucun pouvoir ne lui permet pourtant d'échapper aux situations absurdes provoquées par ses camarades, entre Nendô, Kaidô, Teruhashi et bien d'autres. Alors qu'il tente constamment de rester discret, son quotidien devient de plus en plus mouvementé.`},
            {title: "Saison 2", image:"../img/SaikiKusuoNoPsyNan/S2.jpg", synopsis: `Kusuo poursuit son quotidien de lycéen en espérant enfin vivre tranquillement, mais ses pouvoirs et ses camarades ne lui laissent aucun répit. Entre l'arrivée de nouveaux personnages, notamment une autre personne aux pouvoirs psychiques, et les nombreuses mésaventures de son entourage, Kusuo doit une nouvelle fois tout faire pour rester discret. Et cette fois, une menace bien plus importante pourrait mettre en danger l'avenir du Japon.`},
        ],
    }],
    ["RollOverAndDie",{
        support:"anime",
        date: 20260326,
        title: "Roll Over and Die",
        originalTitle: "「お前ごときが魔王に勝てると思うな」と勇者パーティを追放されたので、王都で気ままに暮らしたい",
        otherTitle: `Jamais tu ne vaincras le Roi démon ! - "Omae Gotoki ga Maō ni Kateru to Omou na" to Yūsha Party wo Tsuihō Sareta no de, Ōto de Kimama ni Kurashitai - ROLL OVER AND DIE: I Will Fight for an Ordinary Life with My Love and Cursed Sword!`,
        type:  "Série",
        class: "Shonen",
        genre: ["Action","Aventure","Drame","Fantastique","Slice of Life"],
        theme: ["Gore","Magie","Malédiction","Monstres","Shôjo-aï","Vengeance"],
        episodes: 12,
        saisons: 1,
        status: "En cours",
        sortie: "Hiver 2026",
        studio: ["A.C.G.T."],
        diffusion: ["Crunchyroll"],
        synopsis: `Flum Apricot n'a jamais été destinée à être une héroïne. Malgré des statistiques proches de zéro et un pouvoir qu'elle ne peut même pas utiliser, elle se retrouve membre d'un groupe de héros. Mais la vie de Flum sombre lorsque Jean Inteige, le célèbre sage du groupe, décide qu'elle est un poids mort et s'arrange pour qu'elle soit vendue comme esclave.
Jetée aux monstres pour qu'ils la dévorent afin de divertir son maître, Flum fait le choix désespéré de s'emparer d'une arme maudite... Suite à ce choix, quelque chose de nouveau s'éveille en elle. Ainsi débute le récit sombre sur la quête sanglante d'une femme pour retrouver sa vie !`,
        image: "../img/RollOverAndDie/S1.jpg",
        background:"../img/RollOverAndDie/Bg.jpg",
        listSaisons: false,
    }],
    ["Mashle",{
        support:"anime",
        date: 20240330,
        title: "Mashle",
        originalTitle: "マッシュル",
        otherTitle: "Mashle - Magic and Muscles",
        type:  "Série",
        class: "Shonen",
        genre: ["Action","Aventure","Comédie","Fantastique",],
        theme: ["Arts martiaux","Combats","Magie"],
        episodes: 24,
        saisons: 2,
        status: "En cours",
        sortie: "Printemps 2023",
        studio: ["A-1 Pictures"],
        diffusion: ["Crunchyroll"],
        synopsis: `L'histoire se déroule dans un royaume où la magie est omniprésente et est considérée comme un don divin. Dans cette société, le rang social est déterminé par le potentiel magique et ceux qui n'en disposent pas sont punis de mort.
Mash Burnedead est né sans pouvoirs magiques mais il a survécu caché dans une épaisse forêt. Le jour où son secret est découvert, il se voit proposer un marché : intégrer Easton, la prestigieuse académie de magie, et y obtenir le titre d'élu divin. Pour retrouver sa vie tranquille, Mash accepte.`,
        image: "../img/Mashle/S1.jpg",
        background:"../img/Mashle/Bg.jpg",
        listSaisons: [
            {title: "Saison 1", image:"../img/Mashle/S1.jpg", synopsis: ``},
            {title: "Saison 2", image:"../img/Mashle/S2.jpg", synopsis: ``},
        ],
    }],
    ["LaVoieDuTablier",{
        support:"anime",
        date: 20230101,
        title: "La Voie du Tablier",
        originalTitle: "極主夫道",
        otherTitle: "Gokushufudō - The Way of the Househusband",
        type:  "Série",
        class: "Seinen",
        genre: ["Comédie","Slice of Life"],
        theme: ["Gastronomie","Homme au foyer","Mariage","Yakuza"],
        episodes: 15,
        saisons: 2,
        status: "En cours",
        sortie: "Printemps 2021",
        studio: ["J.C. Staff"],
        diffusion: ["Netflix"],
        synopsis: `Tatsu, l'immortel, le légendaire yakuza qui a vaincu à lui seul un gang rival avec un tuyau de plomb, est connu pour autant effrayer les policiers endurcis que les criminels les plus vicieux. Peu de temps après sa disparition, il refait surface avec un léger changement de profession. Désormais équipé d'un tablier, Tatsu a renoncé à la violence et tente de gagner honnêtement sa vie en tant que mari au foyer.
Tout en s'adaptant aux tâches banales ménagères, Tatsu découvre qu'être un mari au foyer comporte ses propres défis, du champ de bataille connu sous le nom de ventes au supermarché aux échecs dans la cuisine. Bien qu'il vive paisiblement, les malentendus semblent le suivre à gauche et à droite.
Nous allons donc suivre le quotidien d'un ex-yakuza qui a laissé sa dangereuse vie derrière lui pour devenir un mari au foyer.`,
        image: "../img/LaVoieDuTablier/S1.jpg",
        background:"../img/LaVoieDuTablier/Bg.jpg",
        listSaisons: [
            {title: "Saison 1", image:"../img/LaVoieDuTablier/S1.jpg", synopsis: ``},
            {title: "Saison 2", image:"../img/LaVoieDuTablier/S2.jpg", synopsis: ``},
        ],
    }],
    ["Orange",{
        support:"anime",
        date: 20160925,
        title: "Orange",
        originalTitle: "オレンジ",
        otherTitle: false,
        type:  "Série",
        class: "Shojo",
        genre: ["Drame","Romance","Science-Fiction","Slice of Life","Surnaturel"],
        theme: ["Amitié","Amour","École","Futur","Mystère","Poésie","Quotidien","School Life","Tragique"],
        episodes: 13,
        saisons: 1,
        status: "Terminé",
        sortie: "Eté 2016",
        studio: ["Telecom Animation Film","TMS Entertainment"],
        diffusion: ["Viki"],
        synopsis: `Un jour de printemps, Naho Takamiya, âgée de 16 ans, reçoit une étrange lettre signée de son propre nom, datant de dix ans dans le futur. Elle croit d'abord bien sûr à une plaisanterie. Cependant, en commençant à lire la lettre et les détails qui y sont écrits, elle se rend compte au fur et à mesure que des évènements relatés se sont réalisés tels que l'arrivée du nouvel étudiant, Kakeru Naruse, qui est assis à côté d'elle en classe.
Dans la lettre, la Naho du futur parle de ses nombreux regrets, sous-entendant à la Naho du présent de prendre de meilleures décisions, en particulier concernant Kakeru. En effet, le jeune garçon n'est plus de ce monde dans le futur. La Naho du futur lui demande donc de veiller sur lui...`,
        image: "../img/Orange/S1.jpg",
        background:"../img/Orange/Bg.jpg",
        listSaisons: false,
    }],
    ["KingsGame",{
        support:"anime",
        date: 20171221,
        title: `King's Game "The Animation"`,
        originalTitle: "王様ゲーム The Animation",
        otherTitle: "Ō-sama The Animation",
        type:  "Série",
        class: "Seinen",
        genre: ["Drame","Horreur","Surnaturel","Thriller"],
        theme: ["Mystère","Survival game"],
        episodes: 12,
        saisons: 1,
        status: "Terminé",
        sortie: "Automne 2017",
        studio: ["Seven"],
        diffusion: ["Crunchyroll"],
        synopsis: `L'histoire se centre sur une classe entière de 32 lycéens qui reçoivent un étrange message venant d'une personne se faisant appeler le "Roi". Le message contient des ordres que les lycéens doivent accomplir sous peine de mourir.
Au fur et à mesure que les jours passent, les ordres du "Roi" deviennent de plus en plus extrêmes ...`,
        image: "../img/KingsGame/S1.jpg",
        background:"../img/KingsGame/Bg.jpg",
        listSaisons: false,
    }],
    ["NazoNoKanojoX",{
        support:"anime",
        date: 20120701,
        title: "Nazo no Kanojo X",
        originalTitle: "謎の彼女X",
        otherTitle: "Mysterious Girlfriend X",
        type:  "Série",
        class: "Seinen",
        genre: ["Ecchi","Romance","Surnaturel"],
        theme: ["École","Mystère","School Life"],
        episodes: 13,
        saisons: 1,
        status: "Terminé",
        sortie: "Printemps 2012",
        studio: ["Hoods Entertainment"],
        diffusion: ["?"],
        synopsis: `TSUBAKI Akira, un lycéen, voit débarquer une nouvelle élève dans sa classe : la mystérieuse URABE Mikoto. Dès son arrivée, celle-ci ne manque pas de se faire remarquer, par son caractère discret et son attitude atypique. Après les cours, alors que la jeune fille est affalée sur son bureau, Akira la tire de son sommeil, et se rend compte que Mikoto, en dormant, a laissé une trace de sa salive sur son pupitre. Quand celle-ci rentre chez elle, une idée pour le moins étrange traverse l'esprit du garçon, qui se met alors à goûter sa salive. Peu après, il tombe malade, et Mikoto lui rend visite chez lui pour lui expliquer qu'il est devenu... accro à sa salive ! Selon elle, il est amoureux, et pour éviter que le jeune homme ne fasse d'autres crises de manque, il doit goûter un peu de celle-ci chaque jour. C'est ainsi que Akira, réellement sous son charme, est amené à sortir avec Mikoto. S'ensuivent alors de drôles d'aventures liées par le "fil" de la salive...`,
        image: "../img/NazoNoKanojoX/S1.jpg",
        background:"../img/NazoNoKanojoX/Bg.jpg",
        listSaisons: false,
    }],
    ["MiraiNikki",{
        support:"anime",
        date: 20120415,
        title: "Mirai Nikki",
        originalTitle: "未来日記",
        otherTitle: "Mirai Nikki, Le journal du futur - Future Diary",
        type:  "Série",
        class: "Shonen",
        genre: ["Action","Fantastique","Horreur","Psychologique","Romance"],
        theme: ["Assassinat","Crime","Détective","Gore","Mort","Survival game","Terrorisme","Vengeance","Voyage temporel"],
        episodes: 26,
        saisons: 1,
        status: "Terminé",
        sortie: "Automne 2011",
        studio: ["asread"],
        diffusion: ["Crunchyroll"],
        synopsis: `L'histoire nous entraîne dans le quotidien de Yukiteru Amano un jeune adolescent solitaire se renfermant sur lui-même détaché de la réalité. Il préfère se réfugier dans son monde avec ses amis imaginaires plutôt que de s'en faire de vrais dans la réalité.
Seulement un jour, sa vie va basculer, lorsque Deus l'une de ses nombreuses créations se révèle être plus qu'un être imaginaire. Deus offre alors à Yukiteru la possibilité de voir dans le "futur" seulement, Deus est un dieu qui décide de céder sa place à celui qui survivra à un jeu de survie impitoyable.`,
        image: "../img/MiraiNikki/S1.jpg",
        background:"../img/MiraiNikki/Bg.jpg",
        listSaisons: false,
    }],
    ["MushokuTensei",{
        support:"anime",
        date: 20260927,
        title: "Mushoku Tensei",
        originalTitle: "無職転生 ～異世界行ったら本気だす～",
        otherTitle: "Mushoku Tensei, Isekai Ittara Honki Dasu - Mushoku Tensei, Jobless Reincarnation",
        type:  "Série",
        class: "Seinen",
        genre: ["Action","Ecchi","Fantastique","Isekai","Romance","Slice of Life"],
        theme: ["Autre monde","Harem","Magie","Réincarnation"],
        episodes: 63,
        saisons: 3,
        status: "En cours",
        sortie: "Hiver 2021",
        studio: ["Studio Bind"],
        diffusion: ["Crunchyroll","Netflix"],
        synopsis: `L'histoire nous entraîne dans le quotidien d'un NEET qui vient d'être chassé de chez ses parents. Ayant le moral au plus bas, il pense au suicide. Jusqu'au jour où il aperçoit une ancienne camarade de classe sur le point de se faire renverser. D'un geste héroïque, il la pousse et se fait renverser à sa place. Suite à ça, il meurt puis se retrouve réincarné dans un monde fantaisiste.
Il se réincarne dans le corps d'un enfant du nom de Rudeus Greyrat. Il est le fils d'un épéiste nommé Paul Greyrat et d'une ancienne aventurière nommée Zenith Greyrat.
Bien décidé à faire quelque chose de sa nouvelle vie en tant que Rudeus, il va essayer de devenir le plus grand magicien de l'histoire.`,
        image: "../img/MushokuTensei/S1.jpg",
        background:"../img/MushokuTensei/Bg.jpg",
        listSaisons: [
            {title: "Saison 1", image:"../img/MushokuTensei/S1.jpg", synopsis: ``},
            {title: "Saison 2", image:"../img/MushokuTensei/S2.jpg", synopsis: ``},
            {title: "Saison 2", image:"../img/MushokuTensei/S3.jpg", synopsis: ``},
        ],
    }],
    ["SoImSpiderSoWhat",{
        support:"anime",
        date: 20210703,
        title: "So I'm a Spider, So What?",
        originalTitle: "蜘蛛ですが、なにか?",
        otherTitle: "Kumo Desu ga, Nani ka?",
        type:  "Série",
        class: "Seinen",
        genre: ["Action","Aventure","Comédie","Drame","Fantastique","Isekai","Surnaturel"],
        theme: ["Animaux","Autre monde","Magie","Réincarnation","Survie"],
        episodes: 24,
        saisons: 1,
        status: "En cours",
        sortie: "Hiver 2021",
        studio: ["Millepensee"],
        diffusion: ["Crunchyroll"],
        synopsis: `Dans un monde parallèle, le héros et le roi démon se livrent à un combat d'une telle violence, que leur magie s'est ressentie sur la Terre, allant même jusqu'à détruire une classe remplie d'élèves. Cependant, toute les personnes mortes dans cet incident sont réincarnées dans un monde fantastique, dans lequel ils vont pouvoir trouver une nouvelle forme.
L'histoire nous entraîne dans le quotidien d'une des victimes. Cette personne, ayant les plus mauvaises notes de la classe, se retrouve réincarnée en araignée.
Malgré sa position peu avantageuse, elle accepte sa nouvelle vie et va tout faire pour pouvoir survivre, par la seule force de la volonté.`,
        image: "../img/SoImSpiderSoWhat/S1.jpg",
        background:"../img/SoImSpiderSoWhat/Bg.jpg",
        listSaisons: false
    }],
    ["Horimiya",{
        support:"anime",
        date: 20230923,
        title: "Horimiya",
        originalTitle: "ホリミヤ",
        otherTitle:  "Hori-Miya",
        type:  "Série",
        class: "Shonen",
        genre: ["Comédie","Romance","Slice of Life"],
        theme: ["Adolescence","Amour","École","School life"],
        episodes: 26,
        saisons: 2,
        status: "Terminé",
        sortie: "Hiver 2021",
        studio: ["CloverWorks"],
        diffusion: ["Crunchyroll"],
        synopsis: `Bien qu'admirée à l'école pour sa gentillesse et ses prouesses académiques, Kyôko Hori est cependant différente chez elle. Avec ses parents souvent absents pour travailler, Hori doit s'occuper de son jeune frère et faire le ménage, l'empêchant ainsi de se socialiser en dehors de l'école.
Izumi Miyamura, un camarade de classe d'Hori, est considéré comme un otaku maussade avec ses grandes lunettes, ses longs cheveux et sa nature timide et calme. Cependant, il est en réalité une personne gentille et serviable possédant neuf piercings cachés derrière ses longs cheveux et un tatouage le long du dos et de l'épaule gauche.
Un jour, Hori et Miyamura se croisent en dehors de l'école par pur hasard. Comment ces deux personnes vont réagir en découvrant la face cachée de l'autre ?`,
        image: "../img/Horimiya/S1.jpg",
        background:"../img/Horimiya/Bg.jpg",
        listSaisons: [
            {title: "Saison 1", image:"../img/Horimiya/S1.jpg", synopsis: ``},
            {title: "The missing pieces", image:"../img/Horimiya/S2.jpg", synopsis: ``},
        ],
    }],
    ["SmokingBehindTheSupermarketWithYou",{
        support:"anime",
        date: 20260924,
        title: "Smoking Behind The Supermarket With You",
        originalTitle: "スーパーの裏でヤニ吸うふたり",
        otherTitle: "Super no Ura de Yani Sū Futari - Behind the supermarket, smoking with you.",
        type:  "Série",
        class: "Seinen",
        genre: ["Comédie","Romance","Slice of Life"],
        theme: ["Amour","Tabac","Travail"],
        episodes: 12,
        saisons: 1,
        status: "En cours",
        sortie: "Eté 2026",
        studio: ["Asahi Production"],
        diffusion: ["Crunchyroll"],
        synopsis: `À l'âge de 45 ans, Sasaki, employé de bureau, est fatigué par sa morne vie professionnelle. Son seul réconfort est la cigarette et le sourire amical de Yamada, la jeune caissière d'un supermarché où il a l'habitude de passer après son travail. Lorsque Sasaki ne trouve pas Yamada après une journée particulièrement éprouvante, il est interpellé par une femme charmante qui l'invite à fumer avec elle derrière le supermarché. Sasaki pense alors avoir trouvé une nouvelle compagne pour sa pause cigarette en la personne de Tayama, une femme cool et taquine, mais il ne se rend pas compte qu'il connaît peut-être déjà cette jeune femme...`,
        image: "../img/SmokingBehindTheSupermarketWithYou/S1.jpg",
        background:"../img/SmokingBehindTheSupermarketWithYou/Bg.jpg",
        listSaisons: false,
    }],
    ["Dandadan",{
        support:"anime",
        date: 20250918,
        title: "Dandadan",
        originalTitle: "ダンダダン",
        otherTitle: false,
        type:  "Série",
        class: "Shonen",
        genre: ["Action","Comédie","Horreur","Romance"],
        theme: ["Adolescence","Aliens / Extra-terrestres","Amour","Fantômes","Travail"],
        episodes: 24,
        saisons: 2,
        status: "En cours",
        sortie: "Automne 2024",
        studio: ["Science SARU"],
        diffusion: ["ADN","Crunchyroll","Netflix","Amazon Prime Video"],
        synopsis: `Momo Ayase et Ken Takakura sont deux lycéens que tout oppose. Tandis que la première ne croit qu'aux esprits, le second ne jure que par les extraterrestres. Incapables de se convaincre, ils se lancent alors un défi : Momo devra se rendre dans un hôpital où des créatures de l'espace sont censées se trouver et Ken dans un tunnel hanté... Or, chacun va faire une rencontre d'un autre genre qui va bouleverser leurs vies et lier leurs sorts. C'est le début d'une romance survoltée où l'occulte, le paranormal et le surnaturel se bousculent dans un chaos haletant !`,
        image: "../img/Dandadan/S1.jpg",
        background:"../img/Dandadan/Bg.jpg",
        listSaisons: [
            {title: "Saison 1", image:"../img/Dandadan/S1.jpg", synopsis: `Momo Ayase et Ken Takakura sont deux lycéens que tout oppose. Tandis que la première ne croit qu'aux esprits, le second ne jure que par les extraterrestres. Incapables de se convaincre, ils se lancent alors un défi : Momo devra se rendre dans un hôpital où des créatures de l'espace sont censées se trouver et Ken dans un tunnel hanté... Or, chacun va faire une rencontre d'un autre genre qui va bouleverser leurs vies et lier leurs sorts. C'est le début d'une romance survoltée où l'occulte, le paranormal et le surnaturel se bousculent dans un chaos haletant !`},
            {title: "Saison 2", image:"../img/Dandadan/S2.jpg", synopsis: `Il s'agit de la seconde saison de l'anime Dandadan. Elle débute avec l'adaptation de l'arc Cursed House. Momo et Okarun décident d'aider Jiji, l'ami d'enfance de Momo, à se débarrasser d'un esprit maléfique qui hante sa maison. Cependant, ils vont vite découvrir que cette mission ne se résume pas à un simple exorcisme.`},
        ],
    }],
    ["WhisperingYouALoveSong",{
        support:"anime",
        date: 20241228,
        title: "Whispering You a Love Song",
        originalTitle: "ささやくように恋を唄う",
        otherTitle: "Sasayaku Yō ni Koi wo Utau - Whisper Me A Love Song",
        type:  "Série",
        class: "Shojo",
        genre: ["Romance"],
        theme: ["Amour","Club","LGBT+","Musique","École","School life","Shôjo-aï","Yuri"],
        episodes: 12,
        saisons: 1,
        status: "En cours",
        sortie: "Printemps 2024",
        studio: ["CLOUDHEARTS","Yokohama Animation Lab"],
        diffusion: ["ADN"],
        synopsis: `La pétillante et énergique Himari, étudiante en première année de lycée, tombe amoureuse d'une grande et belle fille nommée Yori après avoir entendu son groupe jouer pendant la cérémonie de rentrée. Incapable de retenir son enthousiasme, Himari décide de déclarer ses sentiments à Yori et, à la surprise d'Himari, elle lui répond qu'elle l'aime aussi ! Mais lorsque Himari se rend compte qu'elle ne ressent pas le même amour que Yori, elle commence à se demander ce que "l'amour" signifie vraiment...`,
        image: "../img/WhisperingYouALoveSong/S1.jpg",
        background:"../img/WhisperingYouALoveSong/Bg.jpg",
        listSaisons: false,
    }],
    ["DrStone",{
        support:"anime",
        date: 20250925,
        title: "Dr.STONE",
        originalTitle: "ドクターストーン",
        otherTitle: false,
        type:  "Série",
        class: "Shonen",
        genre: ["Action","Aventure","Fantastique","Isekai","Science-Fiction"],
        theme: ["Drame","Post-apocalyptique","Scientifique","Voyage temporel"],
        episodes: 95,
        saisons: 4,
        status: "Terminé",
        sortie: "Eté 2019",
        studio: ["TMS Entertainment"],
        diffusion: ["Crunchyroll","Netflix","Amazon Prime Video"],
        synopsis: `Un jour, une lumière brillante apparaît subitement dans le ciel pétrifiant en une fraction de seconde l'humanité entière. Des millénaires plus tard, Taiju parvient à briser son enveloppe de pierre et découvre un monde où le genre humain a disparu de la surface de la terre. Avec son ami Senku, ils décident de récréer la civilisation à partir de zéro !`,
        image: "../img/DrStone/S1.jpg",
        background:"../img/DrStone/Bg.jpg",
       listSaisons: [
            {title: "Saison 1", image:"../img/DrStone/S1.jpg", synopsis: `Un jour, une lumière brillante apparaît subitement dans le ciel pétrifiant en une fraction de seconde l'humanité entière. Des millénaires plus tard, Taiju parvient à briser son enveloppe de pierre et découvre un monde où le genre humain a disparu de la surface de la terre. Avec son ami Senku, ils décident de récréer la civilisation à partir de zéro !`},
            {title: "S2 : Stone wars", image:"../img/DrStone/S2.jpg", synopsis: `Senkû et les villageois ont réussi à terminer la construction du premier téléphone portable avant le début du printemps. Grâce à ce dernier, ils vont pouvoir contacter Taiju et Yuzuriha qui se sont infiltrés dans l'empire de Tsukasa depuis déjà un an. Ainsi, la guerre opposant le royaume de la science à l'empire de Tsukasa est sur le point de débuter !`},
            {title: "S3 : New World", image:"../img/DrStone/S3.jpg", synopsis: `Le Royaume de la science, avec l'aide de Ryûsui, construit un navire pour aller à l'origine du rayon de pétrification qui frappé la Terre il y a 3700 ans. Senkû décide de faire route vers l'ile où a atterri la capsule Soyouz pour récupérer les matériaux laissés par Byakuya, mais elle se révèle être habitée...`},
            {title: "S4 : Science future", image:"../img/DrStone/S4.jpg", synopsis: `Après avoir défait les plans d'Ibara, Senkû et ses compagnons se rendent sur le continent américain à la recherche de plants de maïs. Mais un scientifique de renom ayant une mentalité opposée à celle de Senkû décide de l'affronter. Débute alors une bataille 100% scientifique !`},
        ],    
    }],
    ["Parasite",{
        support:"anime",
        date: 20150325,
        title: "Parasite : La maxime",
        originalTitle: "寄生獣",
        otherTitle: "Kiseijū : Sei no Kakuritsu -  Parasyte : the maxim - Parasitic Beasts, Parasyte",
        type:  "Série",
        class: "Seinen",
        genre: ["Action","Horreur","Science-Fiction"],
        theme: ["Aliens / Extra-terrestres","Combats","Crime","Gore","Guerre","Scientifique"],
        episodes: 24,
        saisons: 1,
        status: "Terminé",
        sortie: "Automne 2014",
        studio: ["Madhouse"],
        diffusion: ["ADN","Netflix"],
        synopsis: `Depuis des milliers d'années, l'Homme se trouve au sommet de la chaîne alimentaire. Jusqu'à ce jour où de mystérieuses sphères, abritant d'étranges parasites, se répandent un peu partout sur Terre. Rapidement, les entités prennent possession de certains habitants. Nul ne sait d'où elles viennent, mais ce qui semble certain, c'est qu'elles sont là pour débarrasser le monde de l'espèce humaine.
Shinichi, jeune lycéen, est un « hôte » dont le cerveau a miraculeusement été épargné : et pour cause, Migi, son parasite, a pris possession de son bras droit ! Ce cas exceptionnel va déboucher sur une singulière cohabitation. Car au-delà de la fusion physique opérée entre Migi et Shinichi, qui partagent désormais le même corps et la même vie, va se développer un lien d'attachement particulier où les deux êtres vont apprendre chacun l'un de l'autre. Alors que Shinichi se découvre doté d'incroyables facultés physiques, il prend aussi conscience de la menace qui plane sur ses proches... et sur l'humanité tout entière.`,
        image: "../img/Parasite/S1.jpg",
        background:"../img/Parasite/Bg.jpg",
       listSaisons: false,
    }],
    ["Citrus",{
        support:"anime",
        date: 20180324,
        title: "Citrus",
        originalTitle: "シトラス",
        otherTitle: false,
        type:  "Série",
        class: "Shojo",
        genre: ["Romance"],
        theme: ["Amour","Famille","LGBT+","École","School Life","Shôjo-aï","Yuri"],
        episodes: 12,
        saisons: 1,
        status: "Terminé",
        sortie: "Hiver 2018",
        studio: ["Passione","Graphinica"],
        diffusion: ["Crunchyroll"],
        synopsis: `Suite au remariage de sa mère, Yuzu apprend qu'elle va devoir changer de lycée pour aller dans un établissement réservé aux filles, lycée dans lequel se trouve également Mei, sa nouvelle demi-sœur. Si au début leur relation est relativement tendue à cause du sérieux de Mei, les choses vont bien changer entre elles quand cette dernière va montrer plus de signes d'affection envers Yuzu...`,
        image: "../img/Citrus/S1.jpg",
        background:"../img/Citrus/Bg.jpg",
       listSaisons: false,
    }],
    ["LoveHina",{
        support:"anime",
        date: 20000927,
        title: "Love Hina",
        originalTitle: "ラブひな",
        otherTitle: "Kiseijū - Parasyte",
        type:  "Série",
        class: "Shonen",
        genre: ["Comédie","Romance","Slice of Life"],
        theme: ["Harem","École"],
        episodes: 24,
        saisons: 1,
        status: "Terminé",
        sortie: "Eté 2000",
        studio: ["Déclic Images"],
        diffusion: ["?"],
        synopsis: `À 20 ans, Keitarô Urashima s'accroche et tente d'entrer à Todai, la prestigieuse université de Tokyo. Il a déjà raté le concours d'admission par deux fois. Mais son principal souci est de trouver un logement pour ne pas retourner vivre avec ses parents, qui le poussent à abandonner Todai. Il se rend à la pension Hinata, qui appartient à sa grand-mère. Dans cette pension pour jeunes filles, les locataires le prennent pour un voyeur et lui en font voir de toutes les couleurs. Il est sauvé par sa tante, Haruka, qui habite près de la pension et vient voir les pensionnaires, en l'absence de la grand-mère partie faire le tour du monde.`,
        image: "../img/LoveHina/S1.jpg",
        background:"../img/LoveHina/Bg.jpg",
       listSaisons: false,
    }],
    ["RealGirl",{
        support:"anime",
        date: 20190327,
        title: "Real Girl",
        originalTitle: "3D彼女",
        otherTitle: "3D Kanojo - 3D Girlfriend",
        type:  "Série",
        class: "Shojo",
        genre: ["Comédie","Romance","Slice of Life"],
        theme: ["Adolescence","Amitié","Amour","Drame","École","Otaku","School life"],
        episodes: 24,
        saisons: 2,
        status: "Terminé",
        sortie: "Printemps 2018",
        studio: ["Hoods Entertainment"],
        diffusion: ["ADN"],
        synopsis: `Hikari Tsutsui est un otaku tout ce qu'il y a de plus basique. Il déteste avoir affaire avec les autres et tout particulièrement avec sa classe. À cause de cela, il est moqué par ses camarades. Un jour, il doit nettoyer la piscine en compagnie d'Iroha Igarashi, une jolie fille. Elle est d'ailleurs tout ce qu'il déteste chez les vraies filles ; elle sèche les cours, n'a aucune amies du sexe féminin et bien plus encore. Pourtant, elle est gentille avec lui et l'aidera même quand il sera de nouveau embêté par des élèves. Iroha pourrait bien changer la vie monotone d'Hikari...`,
        image: "../img/RealGirl/S1.jpg",
        background:"../img/RealGirl/Bg.jpg",
        listSaisons: [
            {title: "Saison 1", image:"../img/RealGirl/S1.jpg", synopsis: `Hikari Tsutsui est un otaku tout ce qu'il y a de plus basique. Il déteste avoir affaire avec les autres et tout particulièrement avec sa classe. À cause de cela, il est moqué par ses camarades. Un jour, il doit nettoyer la piscine en compagnie d'Iroha Igarashi, une jolie fille. Elle est d'ailleurs tout ce qu'il déteste chez les vraies filles ; elle sèche les cours, n'a aucune amies du sexe féminin et bien plus encore. Pourtant, elle est gentille avec lui et l'aidera même quand il sera de nouveau embêté par des élèves. Iroha pourrait bien changer la vie monotone d'Hikari...`},
            {title: "Saison 2", image:"../img/RealGirl/S2.jpg", synopsis: `Seconde saison de 3D Kanojo - Real Girl.`},
        ],   
    }],
    ["FairyTail",{
        support:"anime",
        date: 20250105,
        title: "Fairy Tail",
        originalTitle: "フェアリーテイル",
        otherTitle: false,
        type:  "Série",
        class: "Shonen",
        genre: ["Action","Aventure","Comédie","Fantastique","Nekketsu"],
        theme: ["Amitié","Combat","Dragons","Esprit","Magie"],
        episodes: 353,
        saisons: 10, 
        status: "En cours",
        sortie: "Automne 2009",
        studio: ["A-1 Pictures","Satelight"],
        diffusion: ["ADN","Amazon Prime Video"],
        synopsis: `Lucy est une jeune magicienne qui désire par dessus tout entrer dans une guilde magique.
Elle décide de se rendre à Harujion afin d'obtenir des infos sur les guildes, particulièrement la guilde Fairy Tail.
Lors de ses recherches, elle rencontre le mystérieux Salamander, membre de la célèbre guilde Fairy Tail.
Malheureusement ce dernier n'est qu'un charlatan qui utilise des enchantements pour envoûter des femmes et ainsi les revendre au marché d'esclaves !
Alors que Lucy se trouve sous l'envoûtement de Salamander, un garçon mystérieux du nom de Natsu accompagné d'un chat bleu pouvant parler appelé Happy, la percute et rompt le sortilège de Salamander. Pour remercier Natsu et Happy, elle décide de les inviter au restaurant. Plus tard, Salamander lui fait une proposition : si elle vient à la fête sur le bateau, qu'il organise, il la fera entrer chez Fairy Tail. Lucy accepte et s'y rend. A la fête, elle se rend compte que Salamander n'est qu'un escroc et qu'il ne fait même pas partie de Fairy Tail. Elle veut fuir mais, alors qu'elle est sur le point de se faire kidnapper, Natsu et Happy arrivent et la sauvent. C'est alors qu'elle découvre qu'ils sont des mages et qu'ils font partie de Fairy Tail.
C'est le début des aventures de Natsu et Lucy au sein du monde magique de Fairy Tail !`,
        image: "../img/FairyTail/S1.jpg",
        background:"../img/FairyTail/Bg.jpg",
        listSaisons: [
            {title: "Saison 1", image:"../img/FairyTail/S1.jpg", synopsis: `Lucy, jeune constellationniste rêvant d’intégrer Fairy Tail, rencontre Natsu et Happy et rejoint enfin la célèbre guilde. Avec Grey et Erza, elle enchaîne les missions et affronte de nombreux ennemis. Entre l’île de Galuna, la guerre contre Phantom Lord, la Tour du Paradis et les conflits internes de la guilde, Lucy découvre peu à peu une véritable famille.`},
            {title: "Saison 2", image:"../img/FairyTail/S2.jpg", synopsis: `Fairy Tail s’allie à plusieurs guildes pour affronter Oración Seis, une puissante guilde noire cherchant à s’emparer de Nirvana, une magie antique extrêmement dangereuse. Natsu et ses compagnons rencontrent alors Wendy, une jeune chasseuse de dragons. Après cette bataille, de nouvelles aventures attendent la guilde, notamment autour de la mystérieuse Daphné.`},
            {title: "Saison 3", image:"../img/FairyTail/S3.jpg", synopsis: `Natsu, Wendy, Happy et Carla découvrent Edolas, un monde parallèle où la magie disparaît peu à peu et où existent d’étranges doubles de leurs amis. De retour à Earthland, les membres de Fairy Tail se rendent sur l’île de Tenrô pour l’examen de rang S. Mais l’arrivée de Grimoire Heart, de Zeleph puis d’Acnologia transforme l’épreuve en combat pour leur survie.`},
            {title: "Saison 4", image:"../img/FairyTail/S4.jpg", synopsis: `Après sept années d’absence, les membres disparus sur l’île de Tenrô retrouvent une Fairy Tail affaiblie et dépassée par ses anciennes rivales. Alors qu’ils tentent de reprendre leur place, Lucy reçoit un mystérieux souvenir de son père. Celui-ci les entraîne sur la piste des pièces d’une ancienne horloge, convoitées par une organisation dont les projets menacent tout le royaume.`},
            {title: "Saison 5", image:"../img/FairyTail/S5.jpg", synopsis: `Fairy Tail participe aux Grands Jeux intermagiques afin de retrouver sa réputation et redevenir la meilleure guilde de Fiore. Natsu, Lucy, Grey, Erza et leurs compagnons affrontent les mages les plus puissants du royaume, notamment ceux de Saber Tooth. Mais derrière le tournoi se cache un complot inquiétant impliquant Lucy, une mystérieuse porte et des événements venus du futur.`},
            {title: "Saison 6", image:"../img/FairyTail/S6.jpg", synopsis: `Les Grands Jeux intermagiques prennent une tournure dramatique lorsque le projet Éclipse ouvre la voie à une invasion de dragons. Fairy Tail et ses alliés doivent unir leurs forces pour sauver le royaume. Après cette bataille, une étrange perturbation touche les esprits stellaires de Lucy : libérés de leurs contrats, ils se retournent contre leurs anciens maîtres et cherchent une liberté définitive.`},
            {title: "Saison 7", image:"../img/FairyTail/S7.jpg", synopsis: `près plusieurs aventures, Natsu et ses compagnons découvrent le Village du Soleil, dont les habitants ont été mystérieusement pétrifiés. Mais une menace bien plus importante apparaît bientôt : Tartaros. Cette guilde noire composée de démons liés à Zeleph lance une offensive contre le monde magique. Fairy Tail se retrouve engagée dans l’une des batailles les plus éprouvantes de son histoire.`},
            {title: "Saison 8", image:"../img/FairyTail/S8.jpg", synopsis: `Bien avant les aventures de Natsu et Lucy, Mavis Vermillion vit sur l’île de Tenrô. Sa rencontre avec Yuri Dreyar, Precht et Warrod l’entraîne dans une aventure qui conduira à la naissance de Fairy Tail et à sa rencontre avec Zeleph. Des années plus tard, après la dissolution de la guilde, Natsu et Happy reviennent de leur entraînement avec l’intention de retrouver leurs anciens compagnons.`},
            {title: "Saison 9", image:"../img/FairyTail/S9.jpg", synopsis: `Natsu et Lucy partent retrouver les anciens membres de Fairy Tail afin de reformer leur guilde. Après leur confrontation avec Avatar, une menace sans précédent approche : l’Empire Alvarez de Zeleph envahit Fiore avec les redoutables Spriggan 12. Une guerre décisive commence, révélant les secrets de Natsu, Mavis et Zeleph, tandis qu’Acnologia menace à son tour l’avenir du monde.`},
            {title: "100 Years Quest", image:"../img/FairyTail/S10.jpg", synopsis: `Après avoir surmonté la menace du dragon Acnologia et du mage noir Zeleph, Fairy Tail est devenue plus forte et plus énergique que jamais. Malgré cette victoire, certains membres de la guilde ont décidé de participer à la fameuse Quête de 100 ans qu'aucun mage n'a réussi à achever au cours de ces derniers siècles. Même Gildarts, le mage le plus puissant de la guilde, a échoué. Mais Natsu en est sûr : il réussira, car il n'y va pas seul mais avec ses compagnons. Natsu et ses compagnons réussiront-ils à achever cette quête alors que même les plus grands ont échoué ?`},
        ],   
    }],
    ["Btooom",{
        support:"anime",
        date: 20121220,
        title: "Btooom!",
        originalTitle: "ブトゥーム",
        otherTitle: "Btooom",
        type:  "Série",
        class: "Seinen",
        genre: ["Action","Fantastique"],
        theme: ["Jeux-vidéo","Survival game"],
        episodes: 12,
        saisons: 1, 
        status: "Terminé",
        sortie: "Automne 2012",
        studio: ["Madhouse"],
        diffusion: ["ADN"],
        synopsis: `BTOOOM! est un jeu online au succès mondial. Celui-ci consiste à battre l'équipe adverse avec des bombes pour seules armes.
Ryouta Sakamoto, 22 ans et sans emploi, est l'un de ces nombreux joueurs qui passent leur temps dessus. Qui plus est, il peut se targuer d'apparemment faire partie des meilleurs. Mais lorsqu'il se réveille sur une île inconnue, loin du confort de sa chambre, la réalité le rattrape vite quand il se rend compte qu'il va devoir jouer à BTOOOM! en vrai, sous peine d'y laisser sa vie.`,
        image: "../img/Btooom/S1.jpg",
        background:"../img/Btooom/Bg.jpg",
        listSaisons: false,   
    }],
    ["Charlotte",{
        support:"anime",
        date: 20150926,
        title: "Charlotte",
        originalTitle: "シャーロット",
        otherTitle: false,
        type:  "Série",
        class: "Shonen",
        genre: ["Comédie","Romance","Surnaturel"],
        theme: ["Drame","École","Pouvoirs psychiques","School life","Super pouvoirs"],
        episodes: 13,
        saisons: 1, 
        status: "Terminé",
        sortie: "Été 2015",
        studio: ["P.A. Works"],
        diffusion: ["?"],
        synopsis: `L'histoire nous entraîne dans un monde où certains enfants, durant la puberté, développent des pouvoirs spéciaux. Ces enfants sont nommés ESPers. Yuu Otosaka, l'un d'eux, semble être en apparence un simple lycéen. Cependant ce dernier à la capacité de pouvoir se glisser et de contrôler entièrement le corps d'une personne, mais seulement durant cinq secondes. Yuu a utilisé cette compétence durant des années pour atteindre ses objectifs, ce qui lui a permis de pouvoir rentrer dans un lycée prestigieux.
Un jour, il est pris la main dans le sac par l'énigmatique, Nao Tomori. Ne pouvant plus reculer, lui et sa sœur Ayumi sont contraints d'être transférés à l'Académie Hoshi-no-umi, un établissement pour des étudiants aux capacités surnaturelles.
Le Bureau des Élèves (BDE) de cette école, mené par la fameuse Nao, est chargé de traquer les adolescents abusant de leurs pouvoirs. Ainsi, Yuu se retrouve obligé de rejoindre le BDE, qui jours après jours, va le mener sur la vérité qui attend tous les détenteurs de ces capacités surnaturelles : les ESPers...`,
        image: "../img/Charlotte/S1.jpg",
        background:"../img/Charlotte/Bg.jpg",
        listSaisons: false,   
    }],
    ["HiScoreGirl",{
        support:"anime",
        date: 20191221,
        title: "Hi Score Girl",
        originalTitle: "ハイスコアガール",
        otherTitle: "High Score Girl",
        type:  "Série",
        class: "Seinen",
        genre: ["Comédie","Romance","Slice of Life"],
        theme: ["Arcade","Compétition","École","Jeux-vidéo"],
        episodes: 24,
        saisons: 3, 
        status: "Terminé",
        sortie: ["Été 2018"],
        studio: ["J.C. Staff","Shogakukan Music & Digital Entertainment"],
        diffusion: ["Netflix"],
        synopsis: `L'histoire se déroule au Japon, en 1991. Haruo Yaguchi est un élève de primaire passionné par les jeux vidéo. Il passe d'ailleurs une bonne partie de son temps dans les salles d'arcades.
Un jour, il croise par hasard une de ses camarades de classe, la populaire Akira Ôno. Ensemble, ils jouent à Street Fighter II et, contre toute attente, Akira bat Haruo à plate couture. Le lendemain, décidé à ne pas revivre ça, le jeune garçon change de salle... et se retrouve à nouveau nez à nez avec Akira.`,
        image: "../img/HiScoreGirl/S1.jpg",
        background:"../img/HiScoreGirl/Bg.jpg",
        listSaisons: [
            {title: "Saison 1", image:"../img/HiScoreGirl/S1.jpg", synopsis: `L'histoire se déroule au Japon, en 1991. Haruo Yaguchi est un élève de primaire passionné par les jeux vidéo. Il passe d'ailleurs une bonne partie de son temps dans les salles d'arcades. Un jour, il croise par hasard une de ses camarades de classe, la populaire Akira Ôno. Ensemble, ils jouent à Street Fighter II et, contre toute attente, Akira bat Haruo à plate couture. Le lendemain, décidé à ne pas revivre ça, le jeune garçon change de salle... et se retrouve à nouveau nez à nez avec Akira.`},
            {title: "Saison 2", image:"../img/HiScoreGirl/S2.jpg", synopsis: `Il s'agit de la saison 2 de l'anime High Score Girl.`},
            {title: "Extra stage", image:"../img/HiScoreGirl/S3.jpg", synopsis: `Il s'agit de la suite de l'anime High Score Girl`},
        ],      
    }],
    ["BNA",{
        support:"anime",
        date: 20200624,
        title: "BNA",
        originalTitle: "ビー・エヌ・エー",
        otherTitle: "Brand New Animal",
        type:  "Série",
        class: "Shonen",
        genre: ["Action","Comédie","Fantastique"],
        theme: ["Animaux","Homme-Bête","Mystère","Société"],
        episodes: 12,
        saisons: 1,     
        status: "Terminé",
        sortie: "Printemps 2020",
        studio: ["Trigger"],
        diffusion: ["Netflix"],
        synopsis: `Au XXIè siècle, alors que leur existence avait toujours été cachée, surgissent de l'ombre des animaux anthropomorphiques. Michiru, une jeune humaine, se transforme un jour en tanuki : choquée par sa nouvelle forme, elle se réfugie à Anima City, un gigantesque complexe créé il y a 10 ans dans l'optique d'accueillir les animaux-humains. Là, elle fait la rencontre de Shirou, un homme-loup qui dit détester les humains. À son contact, Michiru commence doucement à comprendre tous les enjeux qui entourent le mystère des hommes-animaux. Mais une énigme persiste : pourquoi s'est-elle transformée en tanuki, alors qu'elle avait toujours été humaine jusqu'ici ? Michiru la femme-tanuki et Shirou l'homme-loup se retrouvent bientôt happés au cœur d'un incident de grande envergure...`,
        image: "../img/BNA/S1.jpg",
        background:"../img/BNA/Bg.jpg",
        listSaisons: false,      
    }],
    ["Gleipnir",{
        support:"anime",
        date: 20200628,
        title: "Gleipnir",
        originalTitle: "グレイプニル",
        otherTitle: false,
        type:  "Série",
        class: "Seinen",
        genre: ["Action","Comédie","Drame","Ecchi","Horreur","Psychologique","Romance","Surnaturel"],
        theme: ["Combat","École","Monstres","Mystère","Transformation"],
        episodes: 13,
        saisons: 1,     
        status: "Terminé",
        sortie: "Printemps 2020",
        studio: ["PINE JAM"],
        diffusion: ["Crunchyroll"],
        synopsis: `Shûichi Kagaya, un lycéen jusqu'ici sans histoires devient subitement capable de se transformer en un gigantesque "monstre" aux capacités hors normes. Il sauve ainsi la vie de Claire coincée dans une maison en feu. Mais Claire découvre son secret et également qu'elle a la possibilité de se faufiler, par le biais d'une fermeture éclair, dans la mascotte incarnée par Shuîchi. Et si Shuîchi n'était pas le seul dans ce cas !? Qu'est-ce qui attend ces deux lycéens désormais liés par le destin !? Leur plus grand combat est sur le point de commencer !! Ne faisons plus qu'un... à la vie, à la mort !`,
        image: "../img/Gleipnir/S1.jpg",
        background:"../img/Gleipnir/Bg.jpg",
        listSaisons: false,      
        mangaLié: ["Gleipnir"],
        AnimeLié: false,   
    }],
    ["MigiEtDali",{
        support:"anime",
        date: 20200628,
        title: "Migi Et Dali",
        originalTitle: "ミギとダリ",
        otherTitle: "Migi & Dali - Migi to Dari",
        type:  "Série",
        class: "Seinen",
        genre: ["Comédie","Slice of Life"],
        theme: ["Famille","Secrets"],
        episodes: 13,
        saisons: 1,     
        status: "Terminé",
        sortie: "Automne 2023",
        studio: ["CompTown","Geek Toys" ],
        diffusion: ["Crunchyroll"],
        synopsis: `L'histoire nous entraîne au cœur du quotidien d'un couple d'âge moyen qui, ne pouvant faire d'enfant, décide d'adopter. Ils recueillent Hitori, un jeune garçon particulièrement beau mais qui, pour protéger sa famille, lui cache un secret important : il a un jumeau !`,
        image: "../img/MigiEtDali/S1.jpg",
        background:"../img/MigiEtDali/Bg.jpg",
        listSaisons: false,   
        mangaLié: ["MigiEtDali"],
        AnimeLié: false,   
    }],
    ["ChainsawMan",{
        support:"anime",
        date: 20221227,
        title: "Chainsaw Man",
        originalTitle: "チェンソーマン",
        otherTitle: false,
        type:  "Série",
        class: "Shonen",
        genre: ["Action","Aventure","Horreur","Surnaturel"],
        theme: ["Combats","Démons","Détective","Mature","Organnisations secrètes"],
        episodes: 12,
        saisons: 1,     
        status: "Terminé",
        sortie: "Automne 2022",
        studio: ["MAPPA"],
        diffusion: ["Crunchyroll"],
        synopsis: `Pour rembourser ses dettes, Denji, jeune homme dans la dèche la plus totale, est exploité en tant que Devil Hunter avec son chien-démon-tronçonneuse, "Pochita". Mais suite à une cruelle trahison, il voit enfin une possibilité de se tirer des bas-fonds où il croupit ! Devenu surpuissant après sa fusion avec Pochita, Denji est recruté par une organisation et part à la chasse aux démons...`,
        image: "../img/ChainsawMan/S1.jpg",
        background:"../img/ChainsawMan/Bg.jpg",
        listSaisons: false,   
        animeLié: ["ChainsawManRezeHen"],
        mangaLié: ["ChainsawMan"],   
    }],
    ["ChainsawManRezeHen",{
        support:"anime",
        date: 20251022,
        title: "Chainsaw Man – Le Film : L'arc de Reze",
        originalTitle: "チェンソーマン",
        otherTitle: "Gekijō-ban Chainsaw Man : Reze-hen - Chainsaw Man, The Movie : Reze Arc",
        type:  "Film",
        class: "Shonen",
        genre: ["Action","Aventure","Horreur","Surnaturel"],
        theme: ["Combats","Démons","Détective","Mature","Organnisations secrètes"],
        episodes: 1,
        saisons: 1,     
        status: "Terminé",
        sortie: "Été 2025",
        studio: ["MAPPA"],
        diffusion: ["Sony Pictures Entertainment"],
        synopsis: `Pour rembourser ses dettes, Denji, jeune homme dans la dèche la plus totale, est exploité en tant que Devil Hunter avec son chien-démon-tronçonneuse, "Pochita". Mais suite à une cruelle trahison, il voit enfin une possibilité de se tirer des bas-fonds où il croupit ! Devenu surpuissant après sa fusion avec Pochita, Denji est recruté par une organisation et part à la chasse aux démons...`,
        image: "../img/ChainsawMan/RezeHen.jpg",
        background:"../img/ChainsawMan/Bg.jpg",
        listSaisons: false,   
        animeLié: ["ChainsawMan"],
        mangaLié: ["ChainsawMan"],   
    }],
    ["OtakuOtaku",{
        support:"anime",
        date: 20180622,
        title: "Otaku Otaku",
        originalTitle: "ヲタクに恋は難しい",
        otherTitle: "Wotaku ni Koi wa Muzukashii - Otaku ni Koi wa Muzukashii - It's Difficult to Love an Otaku - Wotakoi: Love is Hard for Otaku",
        type:  "Série",
        class: "Josei",
        genre: ["Comédie","Romance","Slice of Life"],
        theme: ["Amour","Jeux-vidéo","Otaku","Short stories","Travail"],
        episodes: 11,
        saisons: 1,     
        status: "Terminé",
        sortie: "Printemps 2018",
        studio: ["A-1 Pictures"],
        diffusion: ["Amazon Prime Video"],
        synopsis: `L'histoire nous entraîne dans le quotidien de Narumi, une employée de bureau qui fait tout pour cacher son côté fujoshi et de son ami d'enfance, Hirotaka, un hardcore gamer. Ces deux personnes travaillant dans la même entreprise semblent fait l'un pour l'autre, cependant, l'amour est quelque chose de très compliqué.`,
        image: "../img/OtakuOtaku/S1.jpg",
        background:"../img/OtakuOtaku/Bg.jpg",
        listSaisons: false,   
        animeLié: ["OtakuOtakuOAV"],
        mangaLié: ["OtakuOtaku"],   
    }],
    ["OtakuOtakuOAV",{
        support:"anime",
        date: 20180622,
        title: "Otaku Otaku OAV",
        originalTitle: "ヲタクに恋は難しい",
        otherTitle: "Wotaku ni Koi wa Muzukashii - Otaku ni Koi wa Muzukashii - It's Difficult to Love an Otaku - Wotakoi: Love is Hard for Otaku",
        type:  "OAV",
        class: "Josei",
        genre: ["Comédie","Romance","Slice of Life"],
        theme: ["Amour","Jeux-vidéo","Otaku","Short stories","Travail"],
        episodes: 3,
        saisons: 3,     
        status: "Terminé",
        sortie: "Printemps 2019",
        studio: ["A-1 Pictures","Lapintrack"],
        diffusion: ["?"],
        synopsis: `OAV`,
        image: "../img/OtakuOtaku/OAV1.jpg",
        background:"../img/OtakuOtaku/Bg.jpg",
        listSaisons: [
            {title: "OAV 1", image: "../img/OtakuOtaku/OAV1.jpg", synopsis: `Tarou Kabakura, un étudiant en Terminale et capitaine de l'équipe masculine de volleyball, se fait constamment harceler par Hanako Koyanagi, la personne en charge de l'équipe féminine. Koyanagi veut avoir accès au terrain étant donné que son équipe va disputer un match dans peu de temps. Cependant, lorsque Kabakura refuse, elle sort des preuves exposant son hobby. Ne voulant pas que son hobby soit exposé aux yeux de son équipe, il cède le terrain à l'équipe féminine, tout en donnant des cours privés à Koyanagi. Au fur et à mesure que le temps passe, ils vont commencer à forger un lien éternel.`},
            {title: "OAV 2", image: "../img/OtakuOtaku/OAV2.jpg", synopsis: `Cet épisode se centre sur Naoya Nifuji et Kou Sakuragi.`},
            {title: "OAV 3", image: "../img/OtakuOtaku/OAV3.jpg", synopsis: ``},
        ],   
        animeLié: ["OtakuOtaku"],
        mangaLié: ["OtakuOtaku"],   
    }],
];


// -------------------------------------- Trier le tableau par ordre alphabétique --------------------------------

const animeOrdered = animeList.sort((a, b) =>
    a[0].localeCompare(b[0], undefined, {
        sensitivity: "base"
    })
);