const classifs = ["Shonen","Seinen","Shojo","Josei","Kodomo"];

const genres = [
    ["Action","../img/genres/action.jpg"],
    ["Aventure","../img/genres/aventure.png"],
    ["Comédie","../img/genres/comedie.jpg"],
    ["Drame","../img/genres/drame.jpg"],
    ["Ecchi","../img/genres/ecchi.jpg"],
    ["Fantastique","../img/genres/fantasy.jpg"],
    ["Horreur","../img/genres/horreur.jpg"],
    ["Isekai","../img/genres/isekai.jpg"],
    ["Nekketsu","../img/genres/nekketsu.jpg"],
    ["Psychologique","../img/genres/psychologique.jpg"],
    ["Romance","../img/genres/romance.jpg"],
    ["Slice of Life","../img/genres/sliceOfLife.jpg"],
    ["Science-Fiction","../img/genres/sciencesFiction.jpg"],
    ["Surnaturel","../img/genres/surnaturel.jpg"],
    ["Thriller","../img/genres/thriller.jpg"]
];

const themes = [
    "Adolescence","Aliens / Extra-terrestres","Amitié","Amour","Animaux","Arcade","Arts martiaux","Assassinat","Autre monde",
    "Badminton","Bains","Basketball",
    "Club","Combats","Comédie musicale","Compétition","Crime","Cross-play",
    "Détective","Dragons",
    "École","Espionnage",
    "Famille","Fantômes","Futur",
    "Gastronomie","Gore","Guerre",
    "Harem","Homme au foyer","Homme-Bête",
    "Identité","Jeux-vidéo","LGBT+",
    "Magie","Maid","Malédiction","Mariage","Médium","Mensonges","Monde virtuel","Mort","Monstres","Musique","Mystère",
    "Organnisations secrètes","Otaku",
    "Poésie","Police","Politique","Post-apocalyptique","Pouvoirs psychiques",
    "Réincarnation",
    "School life","Scientifique","Shinigami","Shôjo-aï","Solitude","Sorcellerie","Société","Sources chaudes","Sport","Super pouvoirs","Survie","Survival game",
    "Tabac","Terrorisme","Tragique","Transformation","Travail",
    "Vengeance","Voyage temporel",
    "Yakuza","Yuri",
];

const auteurs = [
// A
    {nom: "Aigamo Hiroyuki", image: "../img/auteurs/AigamoHiroyuki.jpg", historique: `Hiroyuki Aigamo est une illustratrice et mangaka japonaise . Bien qu'il s'agisse d'un pseudonyme masculin, elle est une femme. Elle était auparavant affiliée au groupe SNE et, depuis octobre 2020, elle en est membre associée. [ 1 ] Elle est la fondatrice et associée principale du collectif de créateurs DucQrews LLC . [ 2 ]
Parmi ses œuvres figure l'adaptation en bande dessinée d'Accel World ".`, link: `https://ja.wikipedia.org/wiki/%E5%90%88%E9%B4%A8%E3%81%B2%E3%82%8D%E3%82%86%E3%81%8D`},
// B
    {nom: "Baba Okina", image: "../img/auteurs/BabaOkina.jpg", historique: `L'auteur de la série Kumo Desu ga, Nani Ka? On ne sait pas grand-chose à son sujet. Il se décrivait comme un hikikomori. Sa véritable apparence est inconnue du public, mais elle est apparue sous forme de peluches Kumoko lors d'interviews, d'événements en direct et de conventions.`, link: `https://kumodesu.fandom.com/wiki/Okina_Baba`},
    {nom: "Boichi", image: "../img/auteurs/Boichi.jpg", historique: `Boichi est le dessinateur de Dr. Stone, et également l'auteur et dessinateur des mangas Sun-Ken Rock et Origin. Boichi (ボイチ Boichi) est le nom d'artiste de Mujik Park (박무직), un mangaka (ou manhwaga) sud-coréen né le 29 janvier 1973 à Séoul vivant au Japon. Il est principalement connu pour être l'auteur et dessinateur du manga Sun-Ken Rock et le dessinateur du manga Dr Stone.`, link: ``},
// E
    {nom: "Endo Tatsuya", image: "../img/auteurs/EndoTatsuya.jpg", historique: `Tatsuya Endo (遠藤達哉, Endō Tatsuya ), né le 23 juillet 1980 dans la préfecture d'Ibaraki au Japon, est un mangaka japonais. Il est le créateur du manga SPY x FAMILY. Endo a travaillé comme assistant sur les mangas Blue Exorcist , Fire Punch et Attack on Titan . En 2000, il a remporté le 5e prix Story King (ストーリーキング, Sutōrī Kingu ) pour son one-shot, Seibu Yugi , dans la catégorie Nom.`, link: `https://animanga.fandom.com/wiki/Tatsuya_Endo`},
// F
    {nom: "Fujikawa Yuka", image: "../img/auteurs/blank.jpg", historique: `Yuka Fujikawa est une artiste manga et illustratrice japonaise .
Ancien pseudonyme : Yuusano (à l'époque de sa publication dans l'anthologie de bandes dessinées de jeux Stencil Gangan).`, link: `https://ja.wikipedia.org/wiki/%E8%97%A4%E5%B7%9D%E7%A5%90%E8%8F%AF`},    
    {nom: "Fujimoto Tatsuki", image: "../img/auteurs/FujimotoTatsuki.jpg", historique: `Tatsuki Fujimoto est l'auteur japonais du manga one-shot Look Back , paru en 2021. Il est surtout connu pour son manga d'action et de dark fantasy Chainsaw Man .`, link: `https://look-back.fandom.com/wiki/Tatsuki_Fujimoto`},
// G
    {nom: "Gunchi Kiri", image: "../img/auteurs/blank.jpg", historique: `Kiri Gunchi est l'auteur et dessinateur du manga Sentaku no Toki (2017), son premier manga.`, link: `https://www.nautiljon.com/people/gunchi+kiri.html`},
// H
    {nom: "Hagiwara Daisuke", image: "../img/auteurs/HagiwaraDaisuke.jpg", historique: `Daisuke Hagiwara (萩原ダイスケHagiwara Daisuke ? ) est l'artiste de la série de mangas Horimiya en cours , publiée en série dans Monthly GFantasy et travaille aux côtés de HERO , l'écrivain. Le manga est un spin-off du webcomic de HERO, Hori-san to Miyamura-kun .`, link: `https://horimiya.fandom.com/wiki/Daisuke_Hagiwara`},
    {nom: "Hata Kenjiro", image: "../img/auteurs/HataKenjiro.jpg", historique: `Kenjiro Hata est l'auteur de Tonikaku Kawaii. Il est surtout connu pour sa série Hayate no Gotoku !
Il a travaillé comme assistant de Koji Kumeta . Il est marié à la comédienne de doublage Masumi Asano, qui a ensuite prêté sa voix à Kanoka Yuzaki .
Sa première œuvre était un one-shot, sorti en 2002 - God's Rocket Punch !.`, link: `https://tonikaku-kawaii.fandom.com/wiki/Hata_Kenjiro`},
    {nom: "HERO", image: "../img/auteurs/HERO.jpg", historique: `Hiroki Adachi (安達浩樹Adachi Hiroki ) , également connue sous le pseudonyme de HERO , est l'auteure originale de Hori-san to Miyamura-kun . Elle a publié ce webcomic de 2007 à 2011, en assurant à la fois le scénario et les illustrations. Le webcomic a ensuite été adapté en manga, prépublié dans le magazine Monthly GFantasy sous le titre Horimiya . HERO est de retour au scénario et Daisuke Hagiwara aux illustrations.`, link: `https://horimiya.fandom.com/wiki/HERO`},
// I
    {nom: "Inagaki Riichiro", image: "../img/auteurs/InagakiRiichiro.jpg", historique: `Riichiro Inagaki ( en japonais :稲垣 理一郎, Hepburn : Inagaki Riichirō ; né le 20 juin 1976) est un mangaka japonais originaire de Tokyo . Il a débuté sa carrière en 2001 en publiant des œuvres dans le magazine Big Comic Spirits de Shogakukan . Après trois one-shots , il a rejoint le Weekly Shōnen Jump de Shueisha , où il a lancé l'œuvre qui l'a rendu célèbre, Eyeshield 21. En collaboration avec le dessinateur Yusuke Murata , Eyeshield 21 a été prépublié dans le Weekly Shōnen Jump de juillet 2002 à juin 2009. Entre 2010 et 2015, Inagaki a collaboré avec plusieurs artistes, dont Bonjae, Katsunori Matsui et Ryoichi Ikegami , et a publié des one-shots dans différents magazines. Il a lancé une nouvelle série intitulée Dr. Stone dans le Weekly Shōnen Jump en 2017, en collaboration avec Boichi . Il a trois enfants avec Orie Kimoto .`, link: `https://wikiland.org/fr/Riichiro_Inagaki`},
    {nom: "Inoue Junya", image: "../img/auteurs/InoueJunya.jpg", historique: `Junya Inoue (井上淳哉, Inoue Junya, également connu sous le nom de Joker Jun ) est l'auteur de la série manga Btooom ! Junya Inoue est né le 18 octobre 1971. Il a travaillé pendant dix ans comme directeur graphique dans l'industrie du jeu vidéo. Parallèlement, il a été assistant sur le manga Chrono Crusade . Il a fait ses débuts comme mangaka en 2001 avec son œuvre Otogi Matsuri (おとぎ奉り, litt. Offrande des Ténèbres ). Sa dernière œuvre, Btooom!, est prépubliée depuis 2009 et est toujours en cours.`, link: `https://btooom.fandom.com/wiki/Junya_Inoue`},
// J
    {nom: "Jinushi", image: "../img/auteurs/Jinushi.jpg", historique: `Jinushi (地主Jinushi , également connu sous le nom de Tochikurui (とちくるい) ) est un mangaka japonais et l'auteur de la série de mangas Smoking Behind the Supermarket with You , publiée en série dans le magazine Monthly Big Gangan de Square Enix en août 2022. On ne dispose pas de beaucoup d'informations sur le mangaka, si ce n'est qu'il est l'auteur de « Smoking Behind the Supermarket with You » et de deux autres œuvres.`, link: `https://yanisuu.fandom.com/wiki/Jinushi`},
// K
    {nom: "Kakashi Asahiro", image: "../img/auteurs/KakashiAsahiro.jpg", historique: `Asahiro Kakashi (né en 1974 ) est un mangaka japonais . Il est originaire de la préfecture d'Akita . Il est de sexe masculin et diplômé de l'Académie d'animation de Yoyogi .
Après avoir été l'assistant d' Eichi En , il a fait ses débuts en 1997 avec « Ero-ken », publié dans « Comic Dolphin » ( Tsukasa Shobo ). Depuis « Abarenbo Shonagon », paru en feuilleton dans « Comic Gum » ( Wani Books ) , il écrit en parallèle des œuvres destinées à un large public et d'autres pour adultes.`, link: `https://ja.wikipedia.org/wiki/%E3%81%8B%E3%81%8B%E3%81%97%E6%9C%9D%E6%B5%A9`},
    {nom: "Kanazawa Nobuaki", image: "../img/auteurs/KanazawaNobuaki.jpg", historique: `Nobuaki Kanazawa est un auteur et scénariste japonais. Son nom de plume est Pakkuncho (ぱっくんちょ). Il est l'auteur du célèbre roman pour portable Ôsama Game, qui a été adapté en film par Norio Tsuruta et en manga par Renda Hitori courant 2011.`, link: `https://www.nautiljon.com/people/kanazawa+nobuaki.html`},
    {nom: "Kawahara Reki", image: "../img/auteurs/KawaharaReki.jpg", historique: `Reki Kawahara a écrit le premier volume de Sword Art Online en 2002 et l'a présenté au Prix du roman de jeu Dengeki (電撃ゲーム小説大賞, Dengeki Game Shōsetsu Taishō?, désormais appelé Grand prix du roman Dengeki) mais le projet a été refusé car il dépassait le nombre de pages limite. Il l'a alors publié sur Internet sous le pseudonyme Fumio Kunori. En 2008, il participe de nouveau à la compétition avec son roman Accel World et a gagné le Grand prix. En plus de ce roman, l'éditeur ASCII Media Works a demandé à Reki Kawahara de reprendre son ancien projet, Sword Art Online, ce qu'il a accepté. La publication a alors commencé en avril 2009. L'auteur a également publié une série dérivée nommée Sword Art Online: Progressive.
En 2012, ses deux séries ont été adaptées en anime, Accel World à partir du 6 avril 2012 et Sword Art Online à partir du 7 juillet 2012. Reki double le personnage Tin Writer dans l’anime Accel World.
En 2014 est publié Zettai Naru Kodoku (Absolute Solitude), un light novel que l'auteur publiait sur son site personnel tout comme Sword Art Online.`, link: `https://fr.wikipedia.org/wiki/Reki_Kawahara`},
    {nom: "kiki", image: "../img/auteurs/kiki.jpg", historique: `kiki est une auteure japonaise. De 2015 à 2019, elle publie sur Internet une vingtaine d'histoires d'isekai et de mondes de fantasy.
La plus importante, 「Omae Gotoki ga Maou ni Kateru to Omou na」to Yuusha Party wo Tsuihou Sareta no de, Outo de Kimama ni Kurashitai, est publié en format light novel depuis 2018.`, link: `https://manga-encyclopedie.fandom.com/fr/wiki/Kiki_(auteure)`},   
    {nom: "Kinta", image: "../img/auteurs/Kinta.jpg", historique: `Kinta est un(e) illustrateur(trice) japonais(e).`, link: `https://manga-encyclopedie.fandom.com/fr/wiki/Kinta`},
    {nom: "Kiryu Tsukasa", image: "../img/auteurs/KiryuTsukasa.jpg", historique: `Tsukasa Kiryuu (輝竜司) est une illustratrice de light novels surtout connue pour son travail sur So I'm a Spider, So What?`, link: `https://dengeki.fandom.com/wiki/Tsukasa_Kiryuu`},
    {nom: "Komoto Hajime", image: "../img/auteurs/KomotoHajime.jpg", historique: `Hajime Komoto ( ? )甲こ本もと 一はじめ est l'auteur de Mashle . On ne dispose actuellement que de peu d'informations à son sujet, hormis l'image d'un champignon qu'il utilise dans les commentaires d'auteur du magazine Shonen Jump .`, link: `https://mashle.fandom.com/wiki/Hajime_Komoto`},
// M
    {nom: "Mashima Hiro", image: "../img/auteurs/MashimaHiro.jpg", historique: `Hiro Mashima (真島 ヒロ, Mashima Hiro?), né le 3 mai 1977 à Nagano au Japon, est un mangaka. Il est principalement connu pour être l’auteur des mangas Rave, publié dans le Weekly Shōnen Magazine de Kōdansha de 1999 à 2005, puis Fairy Tail publié de 2006 à 2017, Edens Zero publié de 2018 à 2024 et Dead Rock depuis 2023.`, link: `https://fr.wikipedia.org/wiki/Hiro_Mashima`},
    {nom: "Mikami Saka", image: "../img/auteurs/MikamiSaka.jpg", historique: `Saka Mikami (サカMikami Saka ? )三み香か見み est l'auteur et illustrateur de la série de mangas Kaoru Hana wa Rin to Saku. Enfant, Saka découvrit le manga Shugo Chara! de PEACH-PIT, une série shôjo, et lut de nombreux mangas shôjo publiés dans le magazine « Nakayoshi ». Profondément inspirée par L'Attaque des Titans de Hajime Isayama et sa fin douce-amère, elle décida de devenir mangaka. Elle soumit sa première œuvre en troisième année de lycée et exprima un goût prononcé pour les récits de la vie quotidienne.`, link: `https://kaoruhana.fandom.com/wiki/Saka_Mikami`},
    {nom: "Minakata Sunao", image: "../img/auteurs/MinakataSunao.jpg", historique: `Minakata Sunao est un(e) character designer, dessinateur(trice) et mangaka japonais(e).`, link: `https://manga-encyclopedie.fandom.com/fr/wiki/Minakata_Sunao`},    
    {nom: "Miura Koji", image: "../img/auteurs/MiuraKoji.jpg", historique: `Kouji Miura (三浦 糀, Miura Kōji ; née le 28 mars 1995) est une mangaka japonaise , principalement connue pour ses séries Blue Box et I Love You, My Teacher . Elle a reçu une mention spéciale pour les nouveaux talents lors de la 90e édition des Weekly Shōnen Magazine Awards en 2013, ainsi qu'une seconde mention lors de la 91e édition la même année. En 2017, son one-shot I Love You, My Teacher a remporté le Magazine Pocket One-Shot Award. Son one-shot Parasol Alliance a quant à lui remporté le Garyokin Pro Drawing King Award en 2019, et Blue Box a reçu le Prix Mondial aux Next Manga Awards 2021 .
Elle a utilisé les pseudonymes Satoshi Yūki et Amami au cours de sa carrière de mangaka.`, link: `https://en.wikipedia.org/wiki/Kouji_Miura`},    
// N
    {nom: "Nakamura Tamako", image: "../img/auteurs/blank.jpg", historique: `Tamako Nakamura est une mangaka japonaise.`, link: `https://www.nautiljon.com/people/nakamura+tamako.html`},
    {nom: "Nanami Mao", image: "../img/auteurs/NanamiMao.jpg", historique: `Mao Nanami est une mangaka spécialisée dans le shojo.`, link: `https://www.nautiljon.com/people/nanami+mao.html`},
// O
    {nom: "Oono Kosuke", image: "../img/auteurs/OonoKosuke.jpg", historique: `Kousuke Oono est un mangaka japonais. Il a travaillé comme assistant pendant 9 ans. Il adore les chiens de races shiba et beagle.`, link: `https://www.bedetheque.com/auteur-53796-BD-Oono-Kousuke.html`},
    {nom: "Oshikiri Rensuke", image: "../img/auteurs/OshikiriRensuke.jpg", historique: `Oshikiri Rensuke (押切蓮介), vrai nom : Kanzaki Ryōta (神崎良太), né le 19 septembre 1979 à Meguro, Tokyo, est un mangaka japonais et créateur de High Score Girl , Pupipō! , Misu Misō et quelques autres mangas.`, link: `https://hiscoregirl.fandom.com/wiki/Oshikiri_Rensuke`},
// R
    {nom: "Renda Hitori", image: "../img/auteurs/blank.jpg", historique: `Hitori Renda est un mangaka qui a fait ses débuts en 2010 avec la série Ôsama Game, dont il assure le dessin (Kanazawa Nobuaki en est le scénariste). Il est spécialisé dans le seinen manga.`, link: `https://www.nautiljon.com/people/renda+hitori.html`},
    {nom: "Rifujin na Magonote", image: "../img/auteurs/RifujinnaMagonote.jpg", historique: `Rifujin na Magonote ( japonais :理不尽な孫の手; lit. Unreasonable Backscratcher ) est le nom de plume d'un romancier japonais surtout connu pour la série de romans Mushoku Tensei .`, link: `https://en.wikipedia.org/wiki/Rifujin_na_Magonote`},
// S
    {nom: "Saburouta", image: "../img/auteurs/Saburouta.jpg", historique: `Saburouta (née le 21 février) est une mangaka et dessinatrice de doujinshi japonaise. =Elle est originaire de la préfecture de Kanagawa. Son groupe sanguin est A. La publication de « citrus » dans le magazine Comic Yuri Hime a débuté lorsqu'elle a présenté un doujinshi de « Futari wa Pretty Cure » ​​au stand d'Ichijinsha lors de l'événement « Traveling Manga Editorial Department » à Comitia. Elle publie des illustrations commémoratives sur Twitter à l'occasion d'événements tels que les anniversaires des personnages de « citrus » et Noël.`, link: `https://ja.wikipedia.org/wiki/%E3%82%B5%E3%83%96%E3%83%AD%E3%82%A6%E3%82%BF`},
    {nom: "Sarachi Yomi", image: "../img/auteurs/SarachiYomi.jpg", historique: `Yomi Sarachi (さ ら ち よ み, Sarachi Yomi , né le 12 novembre dans la préfecture de Nagoya) est un mangaka japonais et le principal illustrateur de la franchise Arcana Famiglia -La storia della Arcana Famiglia- .`, link: `https://arcanafamiglia.fandom.com/wiki/Yomi_Sarachi`},
// T
    {nom: "Takano Ichigo", image: "../img/auteurs/TakanoIchigo.jpg", historique: `Ichigo Takano est une mangaka née à Nagano et est du signe du Capricorne. Elle est du groupe sanguin B.`, link: `https://www.nautiljon.com/people/takano+ichigo.html`},
    {nom: "Takeda Sun", image: "../img/auteurs/TakedaSun.jpg", historique: `Sun Takeda est un/e mangaka qui n'écrit que des seinen. Signe du zodiaque : Scorpion - Lieu de résidence : Préfecture d'Akita`, link: `https://www.nautiljon.com/people/takeda+sun.html`},
    {nom: "Takeshima Eku", image: "../img/auteurs/TakeshimaEku.jpg", historique: `Eku Takeshima (竹嶋 えくTakeshima Eku ) est un mangaka. Il est connu pour avoir créé la série de mangas Whisper Me a Love Song et vit dans la préfecture d'Okayama , au Japon.`, link: `https://sasayaku-you-ni-koi-wo-utau.fandom.com/wiki/Eku_Takeshima`},
    {nom: "Tatsu Yukinobu", image: "../img/auteurs/TatsuYukinobu.jpg", historique: `Yukinobu Tatsu (龍 幸伸Tatsu Yukinobu ? ) est un mangaka japonais et l'auteur de la série de mangas Dandadan .`, link: `https://dandadan.fandom.com/wiki/Yukinobu_Tatsu`},
    {nom: "Tonogai Yoshiki", image: "../img/auteurs/TonogaiYoshiki.jpg", historique: `Yoshiki Tonogai est un mangaka né un 14 mars.
Il vient de Shiga. Il est notamment l'illustrateur de Himatsubushi-hen C'est également l'auteur du manga Doubt, qui est sorti le 27 août 2009 en France. Une nouvelle série du nom de Judge est en court de publication qui sortira le 30 juin 2011 pour la 12 éditions de la Japan Expo. Yoshiki Tonogai est un invité Ki-oon par la même occasion.`, link: `https://www.nautiljon.com/people/tonogai+yoshiki.html`},
// Y
    {nom: "Yamazaki Kore", image: "../img/auteurs/YamazakiKore.jpg", historique: `Kore Yamazaki (ヤマザキコレ, Yamazaki Kore?) est une mangaka japonaise née le 10 juin 1990 à Hokkaidō, au Japon. Elle est connue pour être l'auteure du manga The Ancient Magus Bride (魔法使いの嫁, Mahō tsukai no yome?).`, link: `https://fr.wikipedia.org/wiki/Kore_Yamazaki`},
    // {nom: "", image: "../img/auteurs/.jpg", historique: ``, link: ``},
    // {nom: "", image: "../img/auteurs/.jpg", historique: ``, link: ``},
    // {nom: "", image: "../img/auteurs/.jpg", historique: ``, link: ``},
];

const editeurs = [
// A
    {nom: "Akata", image: "../img/editeurs/Akata.jpg", historique: `Akata est une société française spécialisée dans l'adaptation et l'importation en français d'œuvres asiatiques, filiale des Éditions Leduc depuis 2022.
Fondée en 2001, elle est liée à Delcourt jusqu'en mars 2013. Elle est indépendante jusqu'en 2022, date de son rachat. `, link: `https://fr.wikipedia.org/wiki/Akata`},
// C
    {nom: "Crunchyroll", image: "../img/editeurs/Crunchyroll.jpg", historique: `À l'origine Kazé est un éditeur d'animation, spécialisé dans les dessins animés japonais présent sur le marché depuis 1994. Il se lance dans l'édition de manga en 2007 par le rachat de la société Daipen qui possédait les éditions Asuka. En 2009, il fait évoluer son secteur "manga papier" en annonçant son nouveau label "Kazé manga" et introduisant de nouvelles séries porteuses à son catalogue. Il est racheté en 2022 par Crunchyroll dont il prend désormais le nom.`, link: `https://www.bdfugue.com/editeur/crunchyroll?srsltid=AfmBOoqP8fStvlbfRgrNpZaJoegOgJq_caKK_EcUuNlUTbBbC1R8kThl`},
// D
    {nom: "Delcourt/Tonkam", image: "../img/editeurs/Delcourt-Tonkam.jpg", historique: `En 2001, Delcourt s'associe avec la maison d'édition Akata pour créer une collection manga sous le label « Delcourt/Akata ».
En 2013, les éditeurs Delcourt et Akata séparent leur catalogue. La collection manga de Delcourt est alors renommée « Delcourt Mangas ».
En 2014, Delcourt rachète la maison d'édition Tonkam, qui devient une collection manga publiée parallèlement à celle de l'éditeur.
En 2016, les deux collections manga de Delcourt, « Tonkam » et « Delcourt Mangas », fusionnent sous le titre « Delcourt/Tonkam ».
Delcourt possède également la collection Soleil Manga de l'éditeur Soleil Productions depuis le rachat de ce dernier en 2011.`, link: `https://fr.wikipedia.org/wiki/Delcourt/Tonkam`},
    {nom: "Doki-Doki", image: "../img/editeurs/Doki-Doki.jpg", historique: `Doki-Doki est une collection manga créée en avril 2006 par la maison d'édition de bande dessinée Bamboo Édition.
Doki-Doki est l'onomatopée utilisée en japonais pour exprimer le cœur qui s’emballe, terme qui correspond aux coups de cœur publiés par l'éditeur`, link: `https://fr.wikipedia.org/wiki/Doki-Doki`},
// G
    {nom: "Glénat", image: "../img/editeurs/Glénat.jpg", historique: `Glénat Éditions est une maison d'édition française présente dans le domaine de la bande dessinée, du comics, du manga, du beau-livre et du livre jeunesse. Elle a été fondée en 1969 à Grenoble par Jacques Glénat.`, link: `https://fr.wikipedia.org/wiki/Gl%C3%A9nat`},
// K
    {nom: "Kana", image: "../img/editeurs/Kana.jpg", historique: `Kana est une maison d'édition filiale du groupe Dargaud créée en 1996 comme un label spécialisé[1] dans l'édition de manga. Son adresse est 15-27 rue Moussorgski 75018 Paris.`, link: `https://fr.wikipedia.org/wiki/Kana_(maison_d%27%C3%A9dition)`},
    {nom: "Kazé", image: "../img/editeurs/Kazé.jpg", historique: `Kazé ou Kaze est un éditeur français spécialisé dans les mangas et anciennement dans l'animation japonaise. Fondé en 1994, par Cédric Littardi, que le premier label français d'animation japonaise commence son activité éditoriale en publiant Les Chroniques de la guerre de Lodoss en VHS.
Après être devenu actionnaire majoritaire en 2019, Crunchyroll renomme les labels manga et anime Kazé en 2022. HarperCollins rachète la maison d'édition le 10 décembre 2025. Crunchyroll Manga redevient Kazé en avril 2026.`, link: `https://fr.wikipedia.org/wiki/Kaz%C3%A9`},
    {nom: "Ki-oon", image: "../img/editeurs/Ki-oon.jpg", historique: `Ki-oon est une maison d'édition française spécialisée dans le manga fondée en octobre 2003. Ki-oon est fondée en octobre 2003 par Cécile Pournin et Ahmed Agne, qui se sont connus sur les bancs de la faculté, en étudiant le japonais. Le nom « Ki-oon » vient de l'onomatopée qui signifie « avoir le cœur gonflé d'émotion ».`, link: `https://fr.wikipedia.org/wiki/Ki-oon`},
    {nom: "komikku", image: "../img/editeurs/komikku.jpg", historique: `Komikku Éditions est une maison d'édition française créée en 2012 et spécialisée dans l'édition de mangas.
Elle appartient à la société Eilean Books Paris 15e en redressement judiciaire depuis le 24 juin 2026.`, link: `https://fr.wikipedia.org/wiki/Komikku_%C3%89ditions`},
    {nom: "Kurokawa", image: "../img/editeurs/Kurokawa.jpg", historique: `Kurokawa (« Fleuve Noir », en japonais) est une maison d'édition française spécialisée dans le manga créée en septembre 2005. Kurokawa est le label d'Univers Poche spécialisé dans l'édition de mangas, de light novels, d'artbooks, et de livres. Elle propose une quarantaine de séries différentes, dans les univers shōnen, shōjo et seinen.`, link: `https://fr.wikipedia.org/wiki/Kurokawa`},
// M
    {nom: "Mahô Éditions", image: "../img/editeurs/MahôÉditions.jpg", historique: `Mahô Éditions, fondée en novembre 2019, est une maison d’édition de manga et de light novels. Lancée officiellement en juin 2020 par Aurélien Martinez et Jérémy Touzet, la première publication est un light novel dans l’univers de la légende du Roi Arthur : Les enfants de Gorre.
À partir de 2020, Mahô Éditions établit un partenariat avec la plateforme de lecture en ligne Mangas.io, et y propose une partie de son catalogue.
Le 16 juillet 2020, Mahô Éditions se joint à un grand nombre de ses pairs et concurrents en relayant le hashtag #WeLoveManga. Mahô participe ainsi au mouvement WeLoveManga, et manifeste sa volonté de voir des solutions de lecture de manga en ligne légales se développer en France, ainsi que l'arrêt du piratage de masse de mangas en ligne.
Le 10 janvier 2023, ils fusionnent avec la maison d'édition Maned, qui édite des mangas chinois et coréen, Maned devenant une collection à part entière de Mahô.`, link: `https://everybodywiki.com/%C3%89ditions_Mah%C3%B4`},
    {nom: "Mana Books", image: "../img/editeurs/ManaBooks.jpg", historique: `Mana Books est une maison d'édition française créée en 2017, spécialisée dans la publication d'ouvrages liés à des licences de pop culture : jeux vidéo, mangas et séries télé. C'est une filiale du groupe AC Media. Mana Books est une maison d’édition de pop culture française, principalement dédiée aux œuvres en rapport avec le jeu vidéo. Elle publie également des manga, classés selon 5 collections lancées en 2023.`, link: `https://fr.wikipedia.org/wiki/Mana_Books`},
// N    
    {nom: "nobi nobi!", image: "../img/editeurs/nobinobi!.jpg", historique: `nobi nobi ! est une maison d’édition française de livres jeunesse spécialisée sur le Japon lancée en mars 2010 avec la traduction d’albums illustrés japonais ou la création d’albums originaux inspirés par le Japon.
Le catalogue manga de nobi nobi ! rejoint celui de Pika Édition lors de son acquisition par Hachette Livre en 2016. nobi nobi ! est créé administrativement en juin 2009 par Olivier Pacciani, ancien directeur artistique d'une maison d’édition de manga, et Pierre-Alain Dufour, ancien ingénieur et responsable culturel du festival Japan Expo.
En 2016, Hachette Livre fait l'acquisition du catalogue de nobi nobi !, qui fusionne avec celui de sa collection manga, Pika Édition. « nobi nobi » est une onomatopée japonaise que l'on peut traduire par « être à l'aise »`, link: `https://fr.wikipedia.org/wiki/Nobi_nobi_!`},
    {nom: "noeve grafx", image: "../img/editeurs/noevegrafx.jpg", historique: `Noeve Grafx est une collection de la maison d'édition Noeve, lancée en 2020. Elle est spécialisée dans l'édition de livres d'art et de mangas, avant d'être placée en redressement judiciaire et de stopper ses activités en 2024. Le 23 juin 2025, la maison d'édition publie une annonce sur X annonçant leur retour et la reprise de leur catalogue.`, link: `https://fr.wikipedia.org/wiki/Noeve_Grafx`},
// O
    {nom: "Ototo", image: "../img/editeurs/Ototo.jpg", historique: `Ototo est une maison d'édition française spécialisée dans le manga. Elle est créée en novembre 2011 par la société Euphor pour assurer la publication des mangas shōjo, shōnen et seinen, laissant les titres yaoi, yuri et hentai à Taifu Comics. Elle édite notamment plusieurs adaptations manga de light novel comme Sword Art Online ou Re:Zero.`, link: `https://fr.wikipedia.org/wiki/Ototo`},
// P
    {nom: "Pika", image: "../img/editeurs/Pika.jpg", historique: `Pika Édition est une maison d'édition française spécialisée dans le manga fondée en 2000. `, link: `https://fr.wikipedia.org/wiki/Pika_%C3%89dition`},
// S
    {nom: "Shueisha", image: "../img/editeurs/Shueisha.jpg", historique: `Shūeisha Inc. (株式会社集英社, Kabushiki gaisha Shūeisha?) est une maison d'édition japonaise fondée en 1925 publiant principalement des magazines consacrés aux mangas. Elle possède notamment les magazines Weekly Shōnen Jump, magazine de prépublication de manga le plus populaire au monde avec ses séries telles que Black Clover, Dragon Ball, Naruto ou One Piece, mais également les magazines Monthly Shōnen Jump, Ultra Jump, Weekly Young Jump, Ribon et You.
Shūeisha décerne chaque année le Prix Tezuka et le Prix Akatsuka. Son importance sur le marché est d'environ 139,9 milliards de yens (± 1,15 milliard d'euros) et son effectif éditorial est de 749 personnes.`, link: `https://fr.wikipedia.org/wiki/Sh%C5%ABeisha`},
// T
    {nom: "Taifu Comics", image: "../img/editeurs/TaifuComics.jpg", historique: `Taifu Comics est une maison d'édition de manga française créée en 2004. C'est une marque commerciale de la société Euphor. Taifu Comics est créé en 2004 par les fondateurs de la Japan Expo et Yves Huchez ; au départ l'éditeur s'appelle Punch Comics mais change rapidement de nom pour Taifu Comics à cause d'un litige avec une autre maison d'édition portant un nom similaire. Les titres de lancement de l'éditeur sont GO And GO de Takao Koyano, No-bra de Kenjiro Kawatsu, et Gonta ! de Katsutoshi Morita et Tarô Nami, tous trois publiés à partir du 15 Décembre 2004. Fin 2006, Yves Huchez devient l'unique dirigeant.
À partir de février 2012, Taifu Comics cesse d'être un éditeur généraliste et se spécialise dans les titres pour adultes, c'est-à-dire en Boys Love/yaoi (principalement), yuri et hentai. Euphor crée un nouvel éditeur Ototo se chargeant de commercialiser les nouvelles acquisitions de mangas de type Shōnen, Shōjo et Seinen.`, link: `https://fr.wikipedia.org/wiki/Taifu_Comics`},
    // {nom: "", image: "../img/editeurs/.jpg", historique: ``, link: ``},
    // {nom: "", image: "../img/editeurs/.jpg", historique: ``, link: ``},
];

const studios = [
    {nom: "A-1 Pictures", image: "../img/studios/A-1Pictures.jpg", historique: `A-1 Pictures Inc. (株式会社エー・ワン・ピクチャーズ, Kabushiki gaisha Ē Wan Pikuchāzu?) est un studio d'animation japonaise, filiale d'Aniplex, fondé en mai 2005.`, link: `https://fr.wikipedia.org/wiki/A-1_Pictures`},
    {nom: "A.C.G.T.", image: "../img/studios/ACGT.jpg", historique: `A.C.G.T (エー・シー・ジー・ティー(A·C·G·T)?) est un studio d'animation japonais fondé le 19 décembre 2000. Le studio a participé à de nombreux développements, principalement en collaboration avec d'autres studios et adapte principalement des œuvres tirées de visual novel.
C'est une filiale d'OB Planning. A.C.G.T travaille régulièrement avec Genco, qui est généralement le producteur exécutif alors qu'A.C.G.T complète la production anime.`, link: `https://fr.wikipedia.org/wiki/A.C.G.T`},
    {nom: "Asahi Production", image: "../img/studios/AsahiProduction.jpg", historique: `Asahi Production a été fondée en 1973 et s'est initialement établie comme studio de tournage spécialisé et société de production de films promotionnels. À ses débuts, Sunrise Inc. (aujourd'hui intégrée à Bandai Namco Filmworks ) et Tokyo Movie Shinsha (aujourd'hui TMS Entertainment ) étaient ses premières filiales. La production de vidéos promotionnelles pour de grandes entreprises et des organisations sectorielles, telles que l'Association japonaise des assurances et Asahi Chemical, constituait l'activité principale du studio.`, link: `https://en.wikipedia.org/wiki/Asahi_Production`},
// C
    {nom: "CLOUDHEARTS", image: "../img/studios/CLOUDHEARTS.jpg", historique: `Cloud Hearts Co., Ltd. ( japonais :株式会社クラウドハーツ, Hepburn : Kabushiki-gaisha Cloud Hearts ) était un studio d'animation japonais basé à Suginami , Tokyo. Le studio existait initialement comme une branche de Yokohama Animation Lab au milieu des années 2010, sous le nom de « YAL/CHst » (acronyme de « Yokohama Animation Lab / CloudHearts studio »), avant d'être officiellement constitué en entité juridique distincte (tout en restant au sein du groupe du studio) le 1er juin 2021 par le producteur Satoshi Nakatani. Depuis mai 2024, le studio a été radié de la cote de sa société mère en raison de sa fermeture apparente. Le 18 décembre 2024, la société a officiellement entamé une procédure de faillite.`, link: `https://en.wikipedia.org/wiki/Cloud_Hearts`},
    {nom: "CloverWorks", image: "../img/studios/CloverWorks.jpg", historique: `CloverWorks, Inc. (japonais :株式会社CloverWorks , Hepburn : Kabushiki-gaisha KurōbāWākusu) est un studio d'animation japonais , anciennement Kōenji Studio (A-1 Pictures). Il s'agit d'une filiale d' Aniplex, société de production d'anime appartenant à Sony Music Entertainment Japan.`, link: `https://en.wikipedia.org/wiki/CloverWorks`},
// G
    {nom: "Graphinica", image: "../img/studios/Graphinica.jpg", historique: `Graphinica Co., Ltd. ( japonais :株式会社​Graphinica , Hepburn : Kabushiki-gaisha Gurafinika ) , est un studio d'animation japonais fondé en avril 2009, axé sur l'animation 3DCG et 2D. La société a été créée le 30 avril 2009, après que le studio Gonzo ait décidé de vendre sa division vidéo numérique à Q-TEC, qui a ensuite créé la société avec les ressources acquises, ainsi que 25 employés qui travaillaient avec la société précédente qui sont ensuite devenus une partie de Graphinica, avec un total initial de 60 employés lors de sa création.`, link: `https://en.wikipedia.org/wiki/Graphinica`},
// H
    {nom: "Hoods Entertainment", image: "../img/studios/HoodsEntertainment.jpg", historique: `Hoods Entertainment inc. (フッズエンタテインメント株式会社, Fuzzu Entateinmento Kabushiki-gaisha?) est un studio d'animation japonaise fondé en février 2009. Hoods Entertainment a été fondée en février 2009 par Satoshi Nagai, qui a travaillé auparavant comme producteur pour le studio d'animation Gonzo. Les deux studios ont ainsi cohabité temporairement dans le même bâtiment à Nerima, avant que le siège social ne soit déplacé à Suginami.`, link: `https://fr.wikipedia.org/wiki/Hoods_Entertainment`},
// J
    {nom: "J.C. Staff", image: "../img/studios/J.C.Staff.jpg", historique: `J. C. Staff Co., Ltd. (株式会社ジェー・シー・スタッフ, Kabushiki gaisha Jē Shī Sutaffu?, J et C signifiant « Japan Creative ») est un studio d'animation japonaise situé à Musashino dans la préfecture de Tokyo, au Japon, fondé en janvier 1986. Il a produit un grand nombre d'anime à succès, tels Food wars! Utena, la fillette révolutionnaire, Excel Saga, Shingetsutan Tsukihime, Shakugan no Shana, Honey and Clover, Azumanga Daioh, et la franchise des A Certain Magical Index.`, link: `https://fr.wikipedia.org/wiki/J._C._Staff`},
// M
    {nom: "Millepensee", image: "../img/studios/Millepensee.jpg", historique: `Millepensee, Co., Ltd. ( japonais :株式会社ミルパンセ, Hepburn : Kabushiki-gaisha Mirupanse ) est un studio d'animation japonais fondé en 2013 et basé à Nerima , Tokyo .
Le 10 février 2020, il a été annoncé que Millepensee avait formé un partenariat avec Sanzigen pour former le studio d'animation 3DCG lXlXl. Le studio a été fondé en 2013 par la productrice Naoko Shiraishi. Le réalisateur Shin Itagaki a participé à toutes les productions principales du studio depuis sa création, à l'exception des films Wake Up, Girls!! Itagaki et Shiraishi sont mariés. `, link: `https://en.wikipedia.org/wiki/Millepensee`},
// P
    {nom: "Passione", image: "../img/studios/Passione.jpg", historique: `Passione Co., Ltd. (パッショーネ株式会社, Passhōne Kabushiki-gaisha?) est une entreprise de production et studio d'animation japonaise.`, link: `https://fr.wikipedia.org/wiki/Passione_%28studio%29`},
    {nom: "PINE JAM", image: "../img/studios/PINEJAM.jpg", historique: `Pine Jam Co., Ltd. (株式会社パインジャム, Kabushiki-gaisha Pain Jamu ) est un studio d'animation japonais créé le 3 juillet 2015 par l'ancien producteur de Eight Bit Kazuyoshi Mukaitouge.`, link: `https://en.wikipedia.org/wiki/Pine_Jam`},
// S
    {nom: "Science SARU", image: "../img/studios/ScienceSARU.jpg", historique: `Science SARU (株式会社サイエンスSARU, Kabushiki gaisha Saiensu SARU?) est un studio d'animation japonaise fondé le 4 février 2013 par Masaaki Yuasa et Eunyoung Choi. En 2024, le studio est racheté par le producteur et distributeur Tōhō.`, link: `https://fr.wikipedia.org/wiki/Science_SARU`},
    {nom: "SEVEN·ARCS", image: "../img/studios/SEVEN·ARCS.jpg", historique: `Seven Arcs Co., Ltd. (株式会社, Seven Arcs ; Hepburn : Kabushiki-gaisha Sebun Ākusu ) est une société de production d'anime japonaise, anciennement studio, fondée le 31 mai 2002 par d'anciens membres de Pierrot et du Studio Kikan, qui avaient créé le studio Arcturus en 2000 dans le but de produire des séries animées. Le studio a réalisé sa première série télévisée d'animation, Magical Girl Lyrical Nanoha , en 2004. Depuis, la société a produit de nombreuses autres séries télévisées et films d'animation. `, link: `https://en.wikipedia.org/wiki/Seven_Arcs`},
    {nom: "Shogakukan Music & Digital Entertainment", image: "../img/studios/ShogakukanMusic&DigitalEntertainment.jpg", historique: `Shogakukan Music & Digital Entertainment Co. , Ltd. nom : Shogakukan Music & Digital Entertainment Co., Ltd. [ 2 ] ) est une société japonaise dont le siège est à Chiyoda-ku , Tokyo , dont les principales activités comprennent la production et la vente d'enregistrements master de logiciels musicaux tels que des CD et des disques, la gestion des droits d'auteur musicaux et la planification, la production et la vente de logiciels vidéo . Il appartient au groupe Hitotsubashi . Elle est membre à part entière de la Société japonaise pour les droits des auteurs , compositeurs et éditeurs (JASRAC) et membre associé de l'Association japonaise de l'animation .`, link: `https://ja.wikipedia.org/wiki/%E5%B0%8F%E5%AD%A6%E9%A4%A8%E3%83%9F%E3%83%A5%E3%83%BC%E3%82%B8%E3%83%83%E3%82%AF%26%E3%83%87%E3%82%B8%E3%82%BF%E3%83%AB_%E3%82%A8%E3%83%B3%E3%82%BF%E3%83%86%E3%82%A4%E3%83%A1%E3%83%B3%E3%83%88`},
    {nom: "Studio Bind", image: "../img/studios/StudioBind.jpg", historique: `Studio Bind est un studio d'animation japonais fondé en novembre 2018 grâce à un investissement conjoint de WHITE FOX et d' EGG FIRM . Son président est Ōtomo Hisaya, anciennement de 8-bit, et son siège social est situé dans l'arrondissement de Suginami, à Tokyo, avec un capital social de 5 millions de yens. La société a été créée dans le but de systématiser la promotion du projet d'adaptation en anime du light novel populaire « Mushoku Tensei : Réincarnation en chômeur ». En intégrant l'expérience de production de WHITE FOX et les capacités de planification d'EGG FIRM, elle vise à établir un système de production à long terme axé sur une seule propriété intellectuelle, s'efforçant ainsi de garantir la qualité des œuvres face à la tendance à la production de masse dans l'industrie de l'animation.`, link: `https://baike.baidu.com/fr/item/Studio%20Bind/1281941`},
    {nom: "Studio Durian", image: "../img/studios/StudioDurian.jpg", historique: `Il s'agit d'une société de production d'animation japonaise fondée par Kiyotaka Oshiyama . Son siège social est situé à Suginami, dans la préfecture de Tokyo. La production des courts métrages était principalement sous-traitée à des structures comme le studio de dessin et de design personnel de Kiyotaka Oshiyama . Bien que d'autres indépendants soient parfois engagés, Oshiyama précise qu'il n'y a que deux employés : lui-même et le producteur Yuki Nagano. Il indique qu'il n'y a pas d'avancement de production et que lui et le producteur réalisent la majeure partie du travail. Il explique que, ce type de structure ne pouvant pas gérer un grand nombre de personnes, ils produisent avec une équipe réduite. C'est pourquoi la réalisation et le dessin d'Oshiyama sont essentiels. En 2024, la production du premier long métrage original , Look Back, a débuté . Conformément aux souhaits d'Oshiyama, de nombreux animateurs web ont été employés.`, link: `https://en.namu.wiki/w/%EC%8A%A4%ED%8A%9C%EB%94%94%EC%98%A4%20%EB%91%90%EB%A6%AC%EC%95%88`},
    {nom: "SUNRISE", image: "../img/studios/Sunrise.jpg", historique: `Sunrise (サンライズ, Sanraizu?) est un studio d'animation japonaise, fondé en septembre 1972 et filiale depuis 1994 de Bandai.
Le studio a produit et animé de nombreuses séries comme Nicky Larson, Vision d'Escaflowne, Cowboy Bebop, Inu-Yasha, Gintama, Code Geass mais est aussi à l'origine de la grande saga des Gundam.`, link: `https://fr.wikipedia.org/wiki/Sunrise_(studio)`},
    {nom: "Satelight", image: "../img/studios/Satelight.jpg", historique: `Le studio est fondé en décembre 1995 à Sapporo, sur l'île d'Hokkaidō. Il est à l'époque une filiale de l'entreprise d'informatique B.U.G. Le nom du studio Satelight s'explique de la façon suivante : « S » pour Sapporo, « A » pour Animate, « T » pour Technology et « E » pour Entertainement.`, link: `https://manga-encyclopedie.fandom.com/fr/wiki/Satelight`},
// T
    {nom: "Telecom Animation Film", image: "../img/studios/TelecomAnimationFilm.jpg", historique: `Kabushiki-gaisha Terekomu Animēshon Firumu ) est un studio d'animation japonais fondé le 19 mai 1975. [1] Le studio est une filiale de TMS Entertainment et est situé dans le bâtiment du siège social de la société mère.`, link: `https://wikiland.org/wiki/Telecom_Animation_Film`},
    {nom: "TMS Entertainment", image: "../img/studios/TMSEntertainment.jpg", historique: `TMS Entertainment, Ltd. , également connue sous les noms de Tōkyō Movie Shinsha et TMS-Kyokuichi Corporation, est l'un des plus anciens et des plus célèbres studios d'animation japonaise. Mondialement reconnue pour son souci du détail et la qualité de son animation, l'œuvre de TMS est très appréciée des fans et des producteurs.`, link: `https://dcau.fandom.com/wiki/TMS_Entertainment,_Ltd.`},
    {nom: "Trigger", image: "../img/studios/Trigger.jpg", historique: `Trigger Inc. (株式会社トリガー, Kabushiki gaisha Torigā?), aussi connu sous le nom Studio Trigger, est un studio d'animation japonaise situé à Suginami dans la préfecture de Tokyo, au Japon, fondé en août 2011 par des anciens membres du studio Gainax, Hiroyuki Imaishi et Masahiko Ōtsuka.`, link: `https://fr.wikipedia.org/wiki/Trigger_%28studio%29`},
// W
    {nom: "Wit Studio", image: "../img/studios/WitStudio.jpg", historique: `Wit Studio, Inc. ( en japonais :株式会社ウィットスタジオ, Hepburn : Kabushiki-gaisha Witto Sutajio ) , stylisé WIT Studio , est un studio d'animation japonais fondé le 1er juin 2012 par des producteurs de Production IG , en tant que filiale d' IG Port . Son siège social est situé à Musashino , à Tokyo . George Wada, producteur chez Production IG, en est le président, et Tetsuya Nakatake, également producteur chez Production IG, en est le directeur. Le studio s'est fait connaître grâce à la production de L'Attaque des Titans (les trois premières saisons), Great Pretender , Ranking of Kings , Spy × Family , Mon ami le cerf Nokotan , ainsi que des premières saisons de The Ancient Magus' Bride et de Vinland Saga .`, link: `https://en.wikipedia.org/wiki/Wit_Studio`},
// Y
    {nom: "Yokohama Animation Lab", image: "../img/studios/YokohamaAnimationLab.jpg", historique: `Yokohama Animation Laboratory ( japonais :株式会社横浜アニメーションラボ, Hepburn : Kabushiki-gaisha Yokohama Animēshon Rabo ) est un studio d'animation japonais basé à Naka-ku, Yokohama . Elle a été fondée en juillet 2015 par Yūma Ōue, ancien producteur de la division 7 de Production IG .
Le 5 septembre 2025, il a été annoncé que Yokohama Animation Laboratory avait été acquis par la société japonaise Frontier Works .`, link: `https://en.wikipedia.org/wiki/Yokohama_Animation_Laboratory`},
    // {nom: "", image: "../img/studios/.jpg", historique: ``, link: ``},
    // {nom: "", image: "../img/studios/.jpg", historique: ``, link: ``},
    // {nom: "", image: "../img/studios/.jpg", historique: ``, link: ``},
];

const diffusions = [
    {nom: "ADN", image: "../img/diffusions/ADN.jpg", historique: `Animation Digital Network, abrégé ADN, anciennement Anime Digital Network, est une plate-forme de VoD et simulcast née de la fusion entre KZPlay, appartenant à Kazé, et Genzai, appartenant à Kana Home Video, ayant pour thématique la diffusion de séries et longs métrages d'animation japonaise et franco-belge.`, link: `https://fr.wikipedia.org/wiki/Animation_Digital_Network`},
    {nom: "Amazon Prime Video", image: "../img/diffusions/AmazonPrimeVideo.jpg", historique: `Prime Video (Amazon Prime Video, anciennement commercialisé sous les noms Amazon Instant Video et Amazon Video on Demand) est un service de vidéo à la demande créé par Amazon et présent dans de nombreux pays. Concurrent de Netflix, il propose des films, des séries et émissions de télévision à la location ou à l'achat. Les titres sélectionnés sont offerts gratuitement aux clients qui ont un abonnement Amazon Prime, un geste commercial qui a irrité certains consommateurs du Royaume-Uni où il a été vendu avec une augmentation non négociable de 61 % du prix de l'abonnement. Comme ses concurrents, Amazon a recherché une quantité d'offres exclusives pour différencier son service.`, link: `https://fr.wikipedia.org/wiki/Prime_Video`},
    {nom: "Crunchyroll", image: "../img/diffusions/Crunchyroll.jpg", historique: `Crunchyroll est un service de vidéo à la demande américain par abonnement appartenant à Sony Corporation. Le service distribue principalement des films et des séries télévisées produits par des médias d'Asie de l'Est, y compris des dessins animés japonais. Crunchyroll édite également des mangas et des jeux mobiles. Lancé mi-2006 par un groupe d'étudiants diplômés de l'Université de Californie à Berkeley en 2006, les services de Crunchyroll se sont progressivement développés pour compter plus de 100 millions d'utilisateurs enregistrés, répartis dans plus de 200 pays ou territoires à travers le monde, dont quatre millions d'utilisateurs abonnés.`, link: `https://fr.wikipedia.org/wiki/Crunchyroll`},
    {nom: "Netflix", image: "../img/diffusions/Netflix.jpg", historique: `Netflix est une entreprise internationale américaine active dans le secteur de l'industrie du divertissement. Fondé en 1997 à Scotts Valley (Santa Cruz) par Reed Hastings et Marc Randolph, le groupe est spécialisé dans la distribution et l'exploitation d'œuvres cinématographiques et télévisuelles, notamment par le biais d'une plateforme destinée au service de vidéo à la demande. Son siège social se situe à Los Gatos en Californie. Initialement, l'entreprise est uniquement présente dans le secteur de l'exploitation commerciale, par la fourniture d'un service en ligne de location et d'achat de DVD, livrés à domicile. Elle propose ensuite la location de ces vidéos, moyennant un abonnement mensuel. Le service de vidéo à la demande par abonnement est lancé en 2007. Depuis, l'entreprise s'est lancée dans la distribution d'un grand nombre de films et de séries télévisées ainsi que de créations originales, auxquelles elle consacre des investissements importants.`, link: `https://fr.wikipedia.org/wiki/Netflix`},
    // {nom: "", image: "../img/diffusions/.jpg", historique: ``, link: ``},
    // {nom: "", image: "../img/diffusions/.jpg", historique: ``, link: ``},
];  