const classifs = ["Shonen","Seinen","Shojo","Josei","Kodomo"];

const genres = [
    ["Action","../img/genres/action.jpg"],
    ["Aventure","../img/genres/aventure.png"],
    ["Comédie","../img/genres/comedie.jpg"],
    ["Drame","../img/genres/drame.jpg"],
    ["Ecchi","../img/genres/ecchi.jpg"],
    ["Fantastique","../img/genres/fantasy.jpg"],
    ["Horreur","../img/genres/horreur.jpg"],
    ["Isekai","../img/genres/isekai.jpg"],
    ["Nekketsu","../img/genres/nekketsu.jpg"],
    ["Psychologique","../img/genres/psychologique.jpg"],
    ["Romance","../img/genres/romance.jpg"],
    ["Slice of Life","../img/genres/sliceOfLife.jpg"],
    ["Science-Fiction","../img/genres/sciencesFiction.jpg"],
    ["Surnaturel","../img/genres/surnaturel.jpg"],
    ["Thriller","../img/genres/thriller.jpg"]
];

const themes = [
    "Adolescence","Aliens / Extra-terrestres","Amitié","Amour","Animaux","Arcade","Arts martiaux","Assassinat","Autre monde",
    "Badminton","Bains","Basketball",
    "Club","Combats","Comédie musicale","Compétition","Crime","Cross-play",
    "Détective","Dragons",
    "École","Espionnage",
    "Famille","Fantômes","Futur",
    "Gastronomie","Gore","Guerre",
    "Harem","Homme au foyer","Homme-Bête",
    "Identité","Jeux-vidéo","LGBT+",
    "Magie","Maid","Malédiction","Mariage","Mature","Médium","Mensonges","Monde virtuel","Mort","Monstres","Musique","Mystère",
    "Organnisations secrètes","Otaku",
    "Poésie","Police","Politique","Post-apocalyptique","Pouvoirs psychiques",
    "Réincarnation",
    "School life","Scientifique","Shinigami","Shôjo-aï","Solitude","Sorcellerie","Société","Sources chaudes","Sport","Super pouvoirs","Survie","Survival game",
    "Tabac","Terrorisme","Tragique","Transformation","Travail",
    "Vengeance","Voyage temporel",
    "Yakuza","Yuri",
];

const auteurs = [ // ------------------------------------ Auteurs ------------------------------------------------------------------------------------
// A
    {nom: "Aigamo Hiroyuki", image: "../img/auteurs/AigamoHiroyuki.jpg", historique: `Hiroyuki Aigamo est une illustratrice et mangaka japonaise . Bien qu'il s'agisse d'un pseudonyme masculin, elle est une femme. Elle était auparavant affiliée au groupe SNE et, depuis octobre 2020, elle en est membre associée. [ 1 ] Elle est la fondatrice et associée principale du collectif de créateurs DucQrews LLC . [ 2 ]
Parmi ses œuvres figure l'adaptation en bande dessinée d'Accel World ".`, link: `https://ja.wikipedia.org/wiki/%E5%90%88%E9%B4%A8%E3%81%B2%E3%82%8D%E3%82%86%E3%81%8D`},
    {nom: "Akamatsu Ken", image: "../img/auteurs/AkamatsuKen.jpg", historique: `Ken Akamatsu est un mangaka japonais. Il est marié à Kanon Akamatsu, une chanteuse et idole qui lui a servi de modèle pour un de ses personnages, Asuna. Au lycée, il dirigeait un club d’informatique et a même créé un jeu vidéo qui a eu un certain succès. Il se destinait à devenir réalisateur mais il échoue au concours à l’entrée pour Todai. Il se rabat donc sur Chuo en littérature et intègre le club de mangas.
Il participe à des concours de jeunes talents où il se fait remarquer. Il reçoit le prix Shonen Jump grâce à sa première œuvre Kids : Game in Summer (1993).
Sa notoriété internationale démarra grâce à Love Hina.`, link: `https://manga-encyclopedie.fandom.com/fr/wiki/Ken_Akamatsu`},
    {nom: "Akashi Rokuro", image: "../img/auteurs/blank.jpg", historique: `Rokurô Akashi est un scénariste de light novel et de mangas.`, link: `https://www.nautiljon.com/people/akashi+rokuro.html`},
    {nom: "Akui Makoto", image: "../img/auteurs/blank.jpg", historique: `Makoto Akui (阿久井真, Akui Makoto?) is a Japanese mangaka who formerly studied under Ohtaka Shinobu, the mangaka known for her most popular series Sumomomo Momomo and Magi. Akui is best known for being the artist for the manga series Kokoro ga Sakebitagatterunda. or more commonly known as The Anthem of the Heart.`, link: `https://ao-no-orchestra.fandom.com/wiki/Makoto_Akui`},
    {nom: "Apple", image: "../img/auteurs/blank.jpg", historique: `Appe est un/e dessinateur(trice) de mangas.`, link: `https://www.nautiljon.com/people/appe.html`},
    {nom: "Asano", image: "../img/auteurs/Asano.jpg", historique: `Asano est un/e mangaka qui n'a écrit qu'un seinen pour le moment.`, link: `https://www.nautiljon.com/people/asano.html`},
    {nom: "Aso Shuichi", image: "../img/auteurs/AsoShuichi.jpg", historique: `Shuuichi Asou est un mangaka et l'auteur, artiste et écrivain du manga Saiki Kusuo no Sai Nan . Il dessine souvent des histoires de jeux de rôle. En 2013, il a commencé à dessiner des personnages sur son ordinateur.`, link: `https://saikikusuo-no-psinan.fandom.com/wiki/Asou_Shuuichi`},
// B
    {nom: "Baba Okina", image: "../img/auteurs/BabaOkina.jpg", historique: `L'auteur de la série Kumo Desu ga, Nani Ka? On ne sait pas grand-chose à son sujet. Il se décrivait comme un hikikomori. Sa véritable apparence est inconnue du public, mais elle est apparue sous forme de peluches Kumoko lors d'interviews, d'événements en direct et de conventions.`, link: `https://kumodesu.fandom.com/wiki/Okina_Baba`},
    {nom: "Boichi", image: "../img/auteurs/Boichi.jpg", historique: `Boichi est le dessinateur de Dr. Stone, et également l'auteur et dessinateur des mangas Sun-Ken Rock et Origin. Boichi (ボイチ Boichi) est le nom d'artiste de Mujik Park (박무직), un mangaka (ou manhwaga) sud-coréen né le 29 janvier 1973 à Séoul vivant au Japon. Il est principalement connu pour être l'auteur et dessinateur du manga Sun-Ken Rock et le dessinateur du manga Dr Stone.`, link: ``},
// E
    {nom: "Endo Tatsuya", image: "../img/auteurs/EndoTatsuya.jpg", historique: `Tatsuya Endo (遠藤達哉, Endō Tatsuya ), né le 23 juillet 1980 dans la préfecture d'Ibaraki au Japon, est un mangaka japonais. Il est le créateur du manga SPY x FAMILY. Endo a travaillé comme assistant sur les mangas Blue Exorcist , Fire Punch et Attack on Titan . En 2000, il a remporté le 5e prix Story King (ストーリーキング, Sutōrī Kingu ) pour son one-shot, Seibu Yugi , dans la catégorie Nom.`, link: `https://animanga.fandom.com/wiki/Tatsuya_Endo`},
// F
    {nom: "Fujikawa Yuka", image: "../img/auteurs/blank.jpg", historique: `Yuka Fujikawa est une artiste manga et illustratrice japonaise .
Ancien pseudonyme : Yuusano (à l'époque de sa publication dans l'anthologie de bandes dessinées de jeux Stencil Gangan).`, link: `https://ja.wikipedia.org/wiki/%E8%97%A4%E5%B7%9D%E7%A5%90%E8%8F%AF`},    
    {nom: "Fujimoto Tatsuki", image: "../img/auteurs/FujimotoTatsuki.jpg", historique: `Tatsuki Fujimoto est l'auteur japonais du manga one-shot Look Back , paru en 2021. Il est surtout connu pour son manga d'action et de dark fantasy Chainsaw Man .`, link: `https://look-back.fandom.com/wiki/Tatsuki_Fujimoto`},
// G
    {nom: "Gunchi Kiri", image: "../img/auteurs/blank.jpg", historique: `Kiri Gunchi est l'auteur et dessinateur du manga Sentaku no Toki (2017), son premier manga.`, link: `https://www.nautiljon.com/people/gunchi+kiri.html`},
// H
    {nom: "Hagiwara Daisuke", image: "../img/auteurs/HagiwaraDaisuke.jpg", historique: `Daisuke Hagiwara (萩原ダイスケHagiwara Daisuke ? ) est l'artiste de la série de mangas Horimiya en cours , publiée en série dans Monthly GFantasy et travaille aux côtés de HERO , l'écrivain. Le manga est un spin-off du webcomic de HERO, Hori-san to Miyamura-kun .`, link: `https://horimiya.fandom.com/wiki/Daisuke_Hagiwara`},
    {nom: "Hata Kenjiro", image: "../img/auteurs/HataKenjiro.jpg", historique: `Kenjiro Hata est l'auteur de Tonikaku Kawaii. Il est surtout connu pour sa série Hayate no Gotoku !
Il a travaillé comme assistant de Koji Kumeta . Il est marié à la comédienne de doublage Masumi Asano, qui a ensuite prêté sa voix à Kanoka Yuzaki .
Sa première œuvre était un one-shot, sorti en 2002 - God's Rocket Punch !.`, link: `https://tonikaku-kawaii.fandom.com/wiki/Hata_Kenjiro`},
    {nom: "HERO", image: "../img/auteurs/HERO.jpg", historique: `Hiroki Adachi (安達浩樹Adachi Hiroki ) , également connue sous le pseudonyme de HERO , est l'auteure originale de Hori-san to Miyamura-kun . Elle a publié ce webcomic de 2007 à 2011, en assurant à la fois le scénario et les illustrations. Le webcomic a ensuite été adapté en manga, prépublié dans le magazine Monthly GFantasy sous le titre Horimiya . HERO est de retour au scénario et Daisuke Hagiwara aux illustrations.`, link: `https://horimiya.fandom.com/wiki/HERO`},
// I
    {nom: "Ikezawa Shin", image: "../img/auteurs/blank.jpg", historique: `Ikezawa Shin  (池澤真, Shin Ikezawa ? ), travaillant également sous le nom de Chibimaru  (ちび丸? ), est un dessinateur et illustrateur japonais de bandes dessinées.`, link: `https://typemoon.fandom.com/wiki/Ikezawa_Shin`},
    {nom: "Inagaki Riichiro", image: "../img/auteurs/InagakiRiichiro.jpg", historique: `Riichiro Inagaki ( en japonais :稲垣 理一郎, Hepburn : Inagaki Riichirō ; né le 20 juin 1976) est un mangaka japonais originaire de Tokyo . Il a débuté sa carrière en 2001 en publiant des œuvres dans le magazine Big Comic Spirits de Shogakukan . Après trois one-shots , il a rejoint le Weekly Shōnen Jump de Shueisha , où il a lancé l'œuvre qui l'a rendu célèbre, Eyeshield 21. En collaboration avec le dessinateur Yusuke Murata , Eyeshield 21 a été prépublié dans le Weekly Shōnen Jump de juillet 2002 à juin 2009. Entre 2010 et 2015, Inagaki a collaboré avec plusieurs artistes, dont Bonjae, Katsunori Matsui et Ryoichi Ikegami , et a publié des one-shots dans différents magazines. Il a lancé une nouvelle série intitulée Dr. Stone dans le Weekly Shōnen Jump en 2017, en collaboration avec Boichi . Il a trois enfants avec Orie Kimoto .`, link: `https://wikiland.org/fr/Riichiro_Inagaki`},
    {nom: "Inoue Junya", image: "../img/auteurs/InoueJunya.jpg", historique: `Junya Inoue (井上淳哉, Inoue Junya, également connu sous le nom de Joker Jun ) est l'auteur de la série manga Btooom ! Junya Inoue est né le 18 octobre 1971. Il a travaillé pendant dix ans comme directeur graphique dans l'industrie du jeu vidéo. Parallèlement, il a été assistant sur le manga Chrono Crusade . Il a fait ses débuts comme mangaka en 2001 avec son œuvre Otogi Matsuri (おとぎ奉り, litt. Offrande des Ténèbres ). Sa dernière œuvre, Btooom!, est prépubliée depuis 2009 et est toujours en cours.`, link: `https://btooom.fandom.com/wiki/Junya_Inoue`},
    {nom: "Iwaaki Hitoshi", image: "../img/auteurs/IwaakiHitoshi.jpg", historique: `Hitoshi Iwaaki (岩明 均, Iwaaki Hitoshi ), né le 28 juillet 1960 à Tokyo au Japon, est un mangaka japonais. Il est l'écrivain et illustrateur de la série de science-fiction/horreur Kiseijuu . Au lycée, il lisait beaucoup de mangas d' Osamu Tezuka , ce qui l'a incité à se lancer lui-même dans le dessin de mangas. En 1984, il a travaillé comme assistant du mangaka Kazuo Kamimura. Plus tard, en 1985, sa nouvelle « Gomi no Umi » a remporté le prix Tetsuya Chiba du meilleur nouvel auteur et a été publiée dans un numéro spécial du magazine Morning . Il a ensuite travaillé pour le magazine Monthly Afternoon de Kodansha . 
En 1993, Iwaaki reçoit le Manga Award pour Parasyte . En 2010, Historie a remporté le grand prix de la division manga du Japan Media Arts Festival . Historie lui a également valu le Grand Prix du Prix culturel Tezuka Osamu 2012. Iwaaki a remporté le prix Saito Takao 2020 pour son travail sur Reiri .`, link: `https://parasyte.fandom.com/wiki/Hitoshi_Iwaaki`},
// J
    {nom: "Jinushi", image: "../img/auteurs/Jinushi.jpg", historique: `Jinushi (地主Jinushi , également connu sous le nom de Tochikurui (とちくるい) ) est un mangaka japonais et l'auteur de la série de mangas Smoking Behind the Supermarket with You , publiée en série dans le magazine Monthly Big Gangan de Square Enix en août 2022. On ne dispose pas de beaucoup d'informations sur le mangaka, si ce n'est qu'il est l'auteur de « Smoking Behind the Supermarket with You » et de deux autres œuvres.`, link: `https://yanisuu.fandom.com/wiki/Jinushi`},
// K
    {nom: "Kakashi Asahiro", image: "../img/auteurs/KakashiAsahiro.jpg", historique: `Asahiro Kakashi (né en 1974 ) est un mangaka japonais . Il est originaire de la préfecture d'Akita . Il est de sexe masculin et diplômé de l'Académie d'animation de Yoyogi .
Après avoir été l'assistant d' Eichi En , il a fait ses débuts en 1997 avec « Ero-ken », publié dans « Comic Dolphin » ( Tsukasa Shobo ). Depuis « Abarenbo Shonagon », paru en feuilleton dans « Comic Gum » ( Wani Books ) , il écrit en parallèle des œuvres destinées à un large public et d'autres pour adultes.`, link: `https://ja.wikipedia.org/wiki/%E3%81%8B%E3%81%8B%E3%81%97%E6%9C%9D%E6%B5%A9`},
    {nom: "Kanazawa Nobuaki", image: "../img/auteurs/KanazawaNobuaki.jpg", historique: `Nobuaki Kanazawa est un auteur et scénariste japonais. Son nom de plume est Pakkuncho (ぱっくんちょ). Il est l'auteur du célèbre roman pour portable Ôsama Game, qui a été adapté en film par Norio Tsuruta et en manga par Renda Hitori courant 2011.`, link: `https://www.nautiljon.com/people/kanazawa+nobuaki.html`},
    {nom: "Kawahara Reki", image: "../img/auteurs/KawaharaReki.jpg", historique: `Reki Kawahara a écrit le premier volume de Sword Art Online en 2002 et l'a présenté au Prix du roman de jeu Dengeki (電撃ゲーム小説大賞, Dengeki Game Shōsetsu Taishō?, désormais appelé Grand prix du roman Dengeki) mais le projet a été refusé car il dépassait le nombre de pages limite. Il l'a alors publié sur Internet sous le pseudonyme Fumio Kunori. En 2008, il participe de nouveau à la compétition avec son roman Accel World et a gagné le Grand prix. En plus de ce roman, l'éditeur ASCII Media Works a demandé à Reki Kawahara de reprendre son ancien projet, Sword Art Online, ce qu'il a accepté. La publication a alors commencé en avril 2009. L'auteur a également publié une série dérivée nommée Sword Art Online: Progressive.
En 2012, ses deux séries ont été adaptées en anime, Accel World à partir du 6 avril 2012 et Sword Art Online à partir du 7 juillet 2012. Reki double le personnage Tin Writer dans l’anime Accel World.
En 2014 est publié Zettai Naru Kodoku (Absolute Solitude), un light novel que l'auteur publiait sur son site personnel tout comme Sword Art Online.`, link: `https://fr.wikipedia.org/wiki/Reki_Kawahara`},
    {nom: "kiki", image: "../img/auteurs/kiki.jpg", historique: `kiki est une auteure japonaise. De 2015 à 2019, elle publie sur Internet une vingtaine d'histoires d'isekai et de mondes de fantasy.
La plus importante, 「Omae Gotoki ga Maou ni Kateru to Omou na」to Yuusha Party wo Tsuihou Sareta no de, Outo de Kimama ni Kurashitai, est publié en format light novel depuis 2018.`, link: `https://manga-encyclopedie.fandom.com/fr/wiki/Kiki_(auteure)`},   
    {nom: "Kinta", image: "../img/auteurs/Kinta.jpg", historique: `Kinta est un(e) illustrateur(trice) japonais(e).`, link: `https://manga-encyclopedie.fandom.com/fr/wiki/Kinta`},
    {nom: "Kiryu Tsukasa", image: "../img/auteurs/KiryuTsukasa.jpg", historique: `Tsukasa Kiryuu (輝竜司) est une illustratrice de light novels surtout connue pour son travail sur So I'm a Spider, So What?`, link: `https://dengeki.fandom.com/wiki/Tsukasa_Kiryuu`},
    {nom: "Komoto Hajime", image: "../img/auteurs/KomotoHajime.jpg", historique: `Hajime Komoto ( ? )甲こ本もと 一はじめ est l'auteur de Mashle . On ne dispose actuellement que de peu d'informations à son sujet, hormis l'image d'un champignon qu'il utilise dans les commentaires d'auteur du magazine Shonen Jump .`, link: `https://mashle.fandom.com/wiki/Hajime_Komoto`},
// M
    {nom: "Maeda Jun", image: "../img/auteurs/MaedaJun.jpg", historique: `Jun Maeda est un auteur japonais travaillant pour la compagnie de logiciel key; il a fortement contribué comme auteur de scénario, parolier et compositeur musical pour les romans visuels que la compagnie produit. Son nom de naissance en kanji a été écrit Maeda Jun (前田 純, bien qu'il n'y ait aucun changement dans la prononciation. Originaire de Mie au Japon, il a terminé ses études au collège Mie et plus tard à terminer ses études à l'Université Chukyo avec une license en psychologie. Avant la création de key, Maeda a travaillé pour la compagnie tactics où il avait une main dans la création de deux jeux pour cette compagnie, Moon et One : Kagayaku Kisetsu. Après la cration de key, Maeda a mis beaucoup de travail dans de tels titres réputés comme Kanon, Air et Clannad. Il est aussi l'auteur d'une série manga intitulé Hibiki's Magic.`, link: `https://www.nautiljon.com/people/maeda+jun+(compositeur).html`},
    {nom: "Mashima Hiro", image: "../img/auteurs/MashimaHiro.jpg", historique: `Hiro Mashima (真島 ヒロ, Mashima Hiro?), né le 3 mai 1977 à Nagano au Japon, est un mangaka. Il est principalement connu pour être l’auteur des mangas Rave, publié dans le Weekly Shōnen Magazine de Kōdansha de 1999 à 2005, puis Fairy Tail publié de 2006 à 2017, Edens Zero publié de 2018 à 2024 et Dead Rock depuis 2023.`, link: `https://fr.wikipedia.org/wiki/Hiro_Mashima`},
    {nom: "Mikami Saka", image: "../img/auteurs/MikamiSaka.jpg", historique: `Saka Mikami (サカMikami Saka ? )三み香か見み est l'auteur et illustrateur de la série de mangas Kaoru Hana wa Rin to Saku. Enfant, Saka découvrit le manga Shugo Chara! de PEACH-PIT, une série shôjo, et lut de nombreux mangas shôjo publiés dans le magazine « Nakayoshi ». Profondément inspirée par L'Attaque des Titans de Hajime Isayama et sa fin douce-amère, elle décida de devenir mangaka. Elle soumit sa première œuvre en troisième année de lycée et exprima un goût prononcé pour les récits de la vie quotidienne.`, link: `https://kaoruhana.fandom.com/wiki/Saka_Mikami`},
    {nom: "Minakata Sunao", image: "../img/auteurs/MinakataSunao.jpg", historique: `Minakata Sunao est un(e) character designer, dessinateur(trice) et mangaka japonais(e).`, link: `https://manga-encyclopedie.fandom.com/fr/wiki/Minakata_Sunao`},    
    {nom: "Miura Koji", image: "../img/auteurs/MiuraKoji.jpg", historique: `Kouji Miura (三浦 糀, Miura Kōji ; née le 28 mars 1995) est une mangaka japonaise , principalement connue pour ses séries Blue Box et I Love You, My Teacher . Elle a reçu une mention spéciale pour les nouveaux talents lors de la 90e édition des Weekly Shōnen Magazine Awards en 2013, ainsi qu'une seconde mention lors de la 91e édition la même année. En 2017, son one-shot I Love You, My Teacher a remporté le Magazine Pocket One-Shot Award. Son one-shot Parasol Alliance a quant à lui remporté le Garyokin Pro Drawing King Award en 2019, et Blue Box a reçu le Prix Mondial aux Next Manga Awards 2021 .
Elle a utilisé les pseudonymes Satoshi Yūki et Amami au cours de sa carrière de mangaka.`, link: `https://en.wikipedia.org/wiki/Kouji_Miura`},    
// N
    {nom: "Nakamura Tamako", image: "../img/auteurs/blank.jpg", historique: `Tamako Nakamura est une mangaka japonaise.`, link: `https://www.nautiljon.com/people/nakamura+tamako.html`},
    {nom: "Nanami Mao", image: "../img/auteurs/NanamiMao.jpg", historique: `Mao Nanami est une mangaka spécialisée dans le shojo.`, link: `https://www.nautiljon.com/people/nanami+mao.html`},
// O
    {nom: "Obata Takeshi", image: "../img/auteurs/ObataTakeshi.jpg", historique: `Takeshi Obata ( Obata Takeshi )小お畑ばた健たけし est un illustrateur connu pour son travail en tant qu'artiste de la série Show-ha Shoten !
Obata est connu pour son style de dessin et pour être l'un des créateurs de Death Note et de Bakuman . Outre son travail dans le manga, Obata a également conçu des personnages pour des films, des jeux vidéo et des romans.`, link: `https://showhashoten.fandom.com/wiki/Takeshi_Obata`},
    {nom: "Ohba Tsugumi", image: "../img/auteurs/OhbaTsugumi.jpg", historique: `Né à Tokyo, Tsugumi Ohba (大場 つぐみ, Ōba Tsugumi) est un auteur surtout connu pour le manga Death Note. Son identité (et son genre) restent un secret bien gardé. Certains fans pensent que Tsugumi Ohba n'est qu'un pseudonyme d'Hiroshi Gamō. Comme l'indique la fiche descriptive en début de chaque tome de Death Note, Ohba collectionne les tasses à thé et imagine ses scénarios en étant assis à genoux sur une chaise, une habitude similaire à celle de L, l'un des personnages principaux de la série.`, link: `https://bakuman.fandom.com/wiki/Tsugumi_Ohba`},
    {nom: "Oono Kosuke", image: "../img/auteurs/OonoKosuke.jpg", historique: `Kousuke Oono est un mangaka japonais. Il a travaillé comme assistant pendant 9 ans. Il adore les chiens de races shiba et beagle.`, link: `https://www.bedetheque.com/auteur-53796-BD-Oono-Kousuke.html`},
    {nom: "Oshikiri Rensuke", image: "../img/auteurs/OshikiriRensuke.jpg", historique: `Oshikiri Rensuke (押切蓮介), vrai nom : Kanzaki Ryōta (神崎良太), né le 19 septembre 1979 à Meguro, Tokyo, est un mangaka japonais et créateur de High Score Girl , Pupipō! , Misu Misō et quelques autres mangas.`, link: `https://hiscoregirl.fandom.com/wiki/Oshikiri_Rensuke`},
// R
    {nom: "Renda Hitori", image: "../img/auteurs/blank.jpg", historique: `Hitori Renda est un mangaka qui a fait ses débuts en 2010 avec la série Ôsama Game, dont il assure le dessin (Kanazawa Nobuaki en est le scénariste). Il est spécialisé dans le seinen manga.`, link: `https://www.nautiljon.com/people/renda+hitori.html`},
    {nom: "Rifujin na Magonote", image: "../img/auteurs/RifujinnaMagonote.jpg", historique: `Rifujin na Magonote ( japonais :理不尽な孫の手; lit. Unreasonable Backscratcher ) est le nom de plume d'un romancier japonais surtout connu pour la série de romans Mushoku Tensei .`, link: `https://en.wikipedia.org/wiki/Rifujin_na_Magonote`},
// S
    {nom: "Saburouta", image: "../img/auteurs/Saburouta.jpg", historique: `Saburouta (née le 21 février) est une mangaka et dessinatrice de doujinshi japonaise. =Elle est originaire de la préfecture de Kanagawa. Son groupe sanguin est A. La publication de « citrus » dans le magazine Comic Yuri Hime a débuté lorsqu'elle a présenté un doujinshi de « Futari wa Pretty Cure » ​​au stand d'Ichijinsha lors de l'événement « Traveling Manga Editorial Department » à Comitia. Elle publie des illustrations commémoratives sur Twitter à l'occasion d'événements tels que les anniversaires des personnages de « citrus » et Noël.`, link: `https://ja.wikipedia.org/wiki/%E3%82%B5%E3%83%96%E3%83%AD%E3%82%A6%E3%82%BF`},
    {nom: "Sano Nami", image: "../img/auteurs/SanoNami.jpg", historique: `Nami Sano (佐野 菜見Sano Nami ? ) était une mangaka originaire de la préfecture de Hyōgo, au Japon. Elle travaillait chez Enterbrain et était l'auteure, à la fois scénariste et illustratrice, de Migi to Dali . À 20 ans, Sano soumet ses bandes dessinées à trois éditeurs et reçoit une réponse du magazine Harta (anciennement Fellows!). Elle fait ses débuts en 2010 avec le one-shot Non-Sugar Coffee . En 2011, elle publie deux autres one-shots, Katahaba Hiroshi et Taylor's House , dans Fellows!. Son premier manga, Haven't You Heard? I'm Sakamoto (également connu sous le nom de Sakamoto desu ga? ), est prépublié dans le magazine Harta (Enterbrain) d'avril 2012 à décembre 2015, pour un total de 4 volumes. La série remporte le « Comic Natalie Grand Prize » en 2013. Son œuvre suivante est le manga Migi to Dali , prépublié dans Harta de juillet 2017 à novembre 2021, pour un total de 7 volumes. Sano a également été fortement impliquée dans la production de l'adaptation animée de Migi to Dali avant son décès le 5 août 2023.`, link: `https://migi-to-dali.fandom.com/wiki/Nami_Sano`},
    {nom: "Sarachi Yomi", image: "../img/auteurs/SarachiYomi.jpg", historique: `Yomi Sarachi (さ ら ち よ み, Sarachi Yomi , né le 12 novembre dans la préfecture de Nagoya) est un mangaka japonais et le principal illustrateur de la franchise Arcana Famiglia -La storia della Arcana Famiglia- .`, link: `https://arcanafamiglia.fandom.com/wiki/Yomi_Sarachi`},
    {nom: "Shirakomiso", image: "../img/auteurs/blank.jpg", historique: `Shirakomiso est un/e illustrateur(trice) de light novel.`, link: `https://www.nautiljon.com/people/shirakomiso.html`},
    {nom: "Souryuu", image: "../img/auteurs/Souryuu.jpg", historique: `Souryuu est un auteur, dessinateur et mangaka japonais. Il a commencé sa carrière en se spécialisant dans le hentai, jusqu'à ce qu'il publie sa première série, Machigatta ko wo Mahou Shoujo ni shite shimatta (Magical Girl Holy Shit), en 2016`, link: `https://www.nautiljon.com/people/souryuu+(mangaka).html`},
// T
    {nom: "Takamichi", image: "../img/auteurs/blank.jpg", historique: `Aucune information`, link: `https://www.nautiljon.com/people/takamichi.html`},
    {nom: "Takano Ichigo", image: "../img/auteurs/TakanoIchigo.jpg", historique: `Ichigo Takano est une mangaka née à Nagano et est du signe du Capricorne. Elle est du groupe sanguin B.`, link: `https://www.nautiljon.com/people/takano+ichigo.html`},
    {nom: "Takeda Sun", image: "../img/auteurs/TakedaSun.jpg", historique: `Sun Takeda est un/e mangaka qui n'écrit que des seinen. Signe du zodiaque : Scorpion - Lieu de résidence : Préfecture d'Akita`, link: `https://www.nautiljon.com/people/takeda+sun.html`},
    {nom: "Takeshima Eku", image: "../img/auteurs/TakeshimaEku.jpg", historique: `Eku Takeshima (竹嶋 えくTakeshima Eku ) est un mangaka. Il est connu pour avoir créé la série de mangas Whisper Me a Love Song et vit dans la préfecture d'Okayama , au Japon.`, link: `https://sasayaku-you-ni-koi-wo-utau.fandom.com/wiki/Eku_Takeshima`},
    {nom: "Tatsu Yukinobu", image: "../img/auteurs/TatsuYukinobu.jpg", historique: `Yukinobu Tatsu (龍 幸伸Tatsu Yukinobu ? ) est un mangaka japonais et l'auteur de la série de mangas Dandadan .`, link: `https://dandadan.fandom.com/wiki/Yukinobu_Tatsu`},
    {nom: "Tonogai Yoshiki", image: "../img/auteurs/TonogaiYoshiki.jpg", historique: `Yoshiki Tonogai est un mangaka né un 14 mars.
Il vient de Shiga. Il est notamment l'illustrateur de Himatsubushi-hen C'est également l'auteur du manga Doubt, qui est sorti le 27 août 2009 en France. Une nouvelle série du nom de Judge est en court de publication qui sortira le 30 juin 2011 pour la 12 éditions de la Japan Expo. Yoshiki Tonogai est un invité Ki-oon par la même occasion.`, link: `https://www.nautiljon.com/people/tonogai+yoshiki.html`},
    {nom: "Toru", image: "../img/auteurs/Toru.jpg", historique: `Tooru est un(e) mangaka japonais(e).`, link: `https://www.nautiljon.com/people/tooru+(mangaka).html`},
// U
    {nom: "Ueshiba Riichi", image: "../img/auteurs/UeshibaRiichi.jpg", historique: `Riichi Ueshiba (alias Reach Ueshiba) est un auteur et dessinateur de manga japonais né le 4 septembre 1969 (52 ans en février 2022).
Il est l'auteur et l'illustrateur de Yume Tsukai (Dream User) et de Nazo no Kanojo X ( Mysterious Girlfriend X ). Ces mangas ont ensuite été adaptés en séries animées. Des personnages de son œuvre précédente, Discommunication , font également une apparition dans le 14e épisode (OVA) de l'anime Mysterious Girlfriend X.`, link: `https://mysteriousgirlfriendx.fandom.com/wiki/Riichi_Ueshiba`},
// Y
    {nom: "Yamazaki Kore", image: "../img/auteurs/YamazakiKore.jpg", historique: `Kore Yamazaki (ヤマザキコレ, Yamazaki Kore?) est une mangaka japonaise née le 10 juin 1990 à Hokkaidō, au Japon. Elle est connue pour être l'auteure du manga The Ancient Magus Bride (魔法使いの嫁, Mahō tsukai no yome?).`, link: `https://fr.wikipedia.org/wiki/Kore_Yamazaki`},
    // {nom: "", image: "../img/auteurs/.jpg", historique: ``, link: ``},
];

const editeurs = [ // ------------------------------------- Editeurs -----------------------------------------------------------------------------
// A
    {nom: "Akata", image: "../img/editeurs/Akata.jpg", historique: `Akata est une société française spécialisée dans l'adaptation et l'importation en français d'œuvres asiatiques, filiale des Éditions Leduc depuis 2022.
Fondée en 2001, elle est liée à Delcourt jusqu'en mars 2013. Elle est indépendante jusqu'en 2022, date de son rachat. `, link: `https://fr.wikipedia.org/wiki/Akata`},
    {nom: "ASCII Media Works", image: "../img/editeurs/ASCIIMediaWorks.jpg", historique: `ASCII Media Works (アスキー・メディアワークス, Asukī Media Wākusu?), anciennement ASCII Media Works, Inc. (株式会社 アスキー メディア ワークス, Kabushiki kaisha Asukī Media Wākusu?), est une marque de la maison d'édition japonaise Kadokawa Future Publishing depuis le 1er octobre 2013. Elle était une maison d'édition située à Shinjuku créée le 1er avril 2008, à la suite de la fusion entre ASCII et MediaWorks, où ASCII a été légalement absorbée par MediaWorks. Néanmoins, l'ancien président ASCII, Kiyoshi Takano, devient président d'ASCII Media Works.`, link: `https://fr.wikipedia.org/wiki/ASCII_Media_Works`},
// C
    {nom: "Crunchyroll", image: "../img/editeurs/Crunchyroll.jpg", historique: `À l'origine Kazé est un éditeur d'animation, spécialisé dans les dessins animés japonais présent sur le marché depuis 1994. Il se lance dans l'édition de manga en 2007 par le rachat de la société Daipen qui possédait les éditions Asuka. En 2009, il fait évoluer son secteur "manga papier" en annonçant son nouveau label "Kazé manga" et introduisant de nouvelles séries porteuses à son catalogue. Il est racheté en 2022 par Crunchyroll dont il prend désormais le nom.`, link: `https://www.bdfugue.com/editeur/crunchyroll?srsltid=AfmBOoqP8fStvlbfRgrNpZaJoegOgJq_caKK_EcUuNlUTbBbC1R8kThl`},
// D
    {nom: "Delcourt/Tonkam", image: "../img/editeurs/Delcourt-Tonkam.jpg", historique: `En 2001, Delcourt s'associe avec la maison d'édition Akata pour créer une collection manga sous le label « Delcourt/Akata ».
En 2013, les éditeurs Delcourt et Akata séparent leur catalogue. La collection manga de Delcourt est alors renommée « Delcourt Mangas ».
En 2014, Delcourt rachète la maison d'édition Tonkam, qui devient une collection manga publiée parallèlement à celle de l'éditeur.
En 2016, les deux collections manga de Delcourt, « Tonkam » et « Delcourt Mangas », fusionnent sous le titre « Delcourt/Tonkam ».
Delcourt possède également la collection Soleil Manga de l'éditeur Soleil Productions depuis le rachat de ce dernier en 2011.`, link: `https://fr.wikipedia.org/wiki/Delcourt/Tonkam`},
    {nom: "Doki-Doki", image: "../img/editeurs/Doki-Doki.jpg", historique: `Doki-Doki est une collection manga créée en avril 2006 par la maison d'édition de bande dessinée Bamboo Édition.
Doki-Doki est l'onomatopée utilisée en japonais pour exprimer le cœur qui s’emballe, terme qui correspond aux coups de cœur publiés par l'éditeur`, link: `https://fr.wikipedia.org/wiki/Doki-Doki`},
// G
    {nom: "Glénat", image: "../img/editeurs/Glénat.jpg", historique: `Glénat Éditions est une maison d'édition française présente dans le domaine de la bande dessinée, du comics, du manga, du beau-livre et du livre jeunesse. Elle a été fondée en 1969 à Grenoble par Jacques Glénat.`, link: `https://fr.wikipedia.org/wiki/Gl%C3%A9nat`},
// K
    {nom: "Kana", image: "../img/editeurs/Kana.jpg", historique: `Kana est une maison d'édition filiale du groupe Dargaud créée en 1996 comme un label spécialisé[1] dans l'édition de manga. Son adresse est 15-27 rue Moussorgski 75018 Paris.`, link: `https://fr.wikipedia.org/wiki/Kana_(maison_d%27%C3%A9dition)`},
    {nom: "Kazé", image: "../img/editeurs/Kazé.jpg", historique: `Kazé ou Kaze est un éditeur français spécialisé dans les mangas et anciennement dans l'animation japonaise. Fondé en 1994, par Cédric Littardi, que le premier label français d'animation japonaise commence son activité éditoriale en publiant Les Chroniques de la guerre de Lodoss en VHS.
Après être devenu actionnaire majoritaire en 2019, Crunchyroll renomme les labels manga et anime Kazé en 2022. HarperCollins rachète la maison d'édition le 10 décembre 2025. Crunchyroll Manga redevient Kazé en avril 2026.`, link: `https://fr.wikipedia.org/wiki/Kaz%C3%A9`},
    {nom: "Ki-oon", image: "../img/editeurs/Ki-oon.jpg", historique: `Ki-oon est une maison d'édition française spécialisée dans le manga fondée en octobre 2003. Ki-oon est fondée en octobre 2003 par Cécile Pournin et Ahmed Agne, qui se sont connus sur les bancs de la faculté, en étudiant le japonais. Le nom « Ki-oon » vient de l'onomatopée qui signifie « avoir le cœur gonflé d'émotion ».`, link: `https://fr.wikipedia.org/wiki/Ki-oon`},
    {nom: "Kodansha", image: "../img/editeurs/Kodansha.jpg", historique: `Kodansha Ltd. ( en japonais :株式会社講談社, Hepburn : Kabushiki-gaisha Kōdansha ) est une maison d'édition et une société musicale japonaise privée, basée à Bunkyō , Tokyo . [ 2 ] Kodansha publie des magazines de manga tels que Nakayoshi , Morning , Afternoon , Evening , Weekly Young Magazine , Weekly Shōnen Magazine et Bessatsu Shōnen Magazine , ainsi que les revues littéraires Gunzō et Shūkan Gendai , et le dictionnaire japonais Nihongo Daijiten . Fondée par Seiji Noma en 1909, Kodansha est toujours détenue par sa famille, soit directement, soit par le biais de la Fondation culturelle Noma.`, link: `https://en.wikipedia.org/wiki/Kodansha`},
    {nom: "komikku", image: "../img/editeurs/komikku.jpg", historique: `Komikku Éditions est une maison d'édition française créée en 2012 et spécialisée dans l'édition de mangas.
Elle appartient à la société Eilean Books Paris 15e en redressement judiciaire depuis le 24 juin 2026.`, link: `https://fr.wikipedia.org/wiki/Komikku_%C3%89ditions`},
    {nom: "Kurokawa", image: "../img/editeurs/Kurokawa.jpg", historique: `Kurokawa (« Fleuve Noir », en japonais) est une maison d'édition française spécialisée dans le manga créée en septembre 2005. Kurokawa est le label d'Univers Poche spécialisé dans l'édition de mangas, de light novels, d'artbooks, et de livres. Elle propose une quarantaine de séries différentes, dans les univers shōnen, shōjo et seinen.`, link: `https://fr.wikipedia.org/wiki/Kurokawa`},
// M
    {nom: "Mag Garden", image: "../img/editeurs/MagGarden.jpg", historique: `Mag Garden (マッグガーデン, Maggu Gāden?) est une maison d'édition japonaise qui est centrée sur les publications liées aux mangas. La firme fut fondée en juin 2001 et fut en premier lieu un sous-traitant de Enix, chargé de la publication de leur manga, avant de s'en détacher et de se diversifier. Le fondateur et actuel président de Mag Garden est Yoshihiro Hosaka. L'entreprise est actuellement basée à Chiyoda dans la préfecture de Tokyo au Japon. La société a fusionné avec Production I.G le 1er décembre 2007 pour former la nouvelle société IG Port, devenant ainsi l'une des filiales d'IG Port aux côtés de Signal.MD et de Wit Studio.`, link: `https://fr.wikipedia.org/wiki/Mag_Garden`},
    {nom: "Mahô Éditions", image: "../img/editeurs/MahôÉditions.jpg", historique: `Mahô Éditions, fondée en novembre 2019, est une maison d’édition de manga et de light novels. Lancée officiellement en juin 2020 par Aurélien Martinez et Jérémy Touzet, la première publication est un light novel dans l’univers de la légende du Roi Arthur : Les enfants de Gorre.
À partir de 2020, Mahô Éditions établit un partenariat avec la plateforme de lecture en ligne Mangas.io, et y propose une partie de son catalogue.
Le 16 juillet 2020, Mahô Éditions se joint à un grand nombre de ses pairs et concurrents en relayant le hashtag #WeLoveManga. Mahô participe ainsi au mouvement WeLoveManga, et manifeste sa volonté de voir des solutions de lecture de manga en ligne légales se développer en France, ainsi que l'arrêt du piratage de masse de mangas en ligne.
Le 10 janvier 2023, ils fusionnent avec la maison d'édition Maned, qui édite des mangas chinois et coréen, Maned devenant une collection à part entière de Mahô.`, link: `https://everybodywiki.com/%C3%89ditions_Mah%C3%B4`},
    {nom: "Mana Books", image: "../img/editeurs/ManaBooks.jpg", historique: `Mana Books est une maison d'édition française créée en 2017, spécialisée dans la publication d'ouvrages liés à des licences de pop culture : jeux vidéo, mangas et séries télé. C'est une filiale du groupe AC Media. Mana Books est une maison d’édition de pop culture française, principalement dédiée aux œuvres en rapport avec le jeu vidéo. Elle publie également des manga, classés selon 5 collections lancées en 2023.`, link: `https://fr.wikipedia.org/wiki/Mana_Books`},
// N    
    {nom: "nobi nobi!", image: "../img/editeurs/nobinobi!.jpg", historique: `nobi nobi ! est une maison d’édition française de livres jeunesse spécialisée sur le Japon lancée en mars 2010 avec la traduction d’albums illustrés japonais ou la création d’albums originaux inspirés par le Japon.
Le catalogue manga de nobi nobi ! rejoint celui de Pika Édition lors de son acquisition par Hachette Livre en 2016. nobi nobi ! est créé administrativement en juin 2009 par Olivier Pacciani, ancien directeur artistique d'une maison d’édition de manga, et Pierre-Alain Dufour, ancien ingénieur et responsable culturel du festival Japan Expo.
En 2016, Hachette Livre fait l'acquisition du catalogue de nobi nobi !, qui fusionne avec celui de sa collection manga, Pika Édition. « nobi nobi » est une onomatopée japonaise que l'on peut traduire par « être à l'aise »`, link: `https://fr.wikipedia.org/wiki/Nobi_nobi_!`},
    {nom: "noeve grafx", image: "../img/editeurs/noevegrafx.jpg", historique: `Noeve Grafx est une collection de la maison d'édition Noeve, lancée en 2020. Elle est spécialisée dans l'édition de livres d'art et de mangas, avant d'être placée en redressement judiciaire et de stopper ses activités en 2024. Le 23 juin 2025, la maison d'édition publie une annonce sur X annonçant leur retour et la reprise de leur catalogue.`, link: `https://fr.wikipedia.org/wiki/Noeve_Grafx`},
// O
    {nom: "Ototo", image: "../img/editeurs/Ototo.jpg", historique: `Ototo est une maison d'édition française spécialisée dans le manga. Elle est créée en novembre 2011 par la société Euphor pour assurer la publication des mangas shōjo, shōnen et seinen, laissant les titres yaoi, yuri et hentai à Taifu Comics. Elle édite notamment plusieurs adaptations manga de light novel comme Sword Art Online ou Re:Zero.`, link: `https://fr.wikipedia.org/wiki/Ototo`},
// P
    {nom: "Pika", image: "../img/editeurs/Pika.jpg", historique: `Pika Édition est une maison d'édition française spécialisée dans le manga fondée en 2000. `, link: `https://fr.wikipedia.org/wiki/Pika_%C3%89dition`},
// S
    {nom: "Shogakukan", image: "../img/editeurs/Shogakukan.jpg", historique: `Shōgakukan (株式会社小学館, Kabushiki gaisha Shōgakukan?, litt. « hall de l'école primaire ») est une maison d'édition généraliste japonaise connue à l'étranger pour la publication de mangas, magazines et de dictionnaires linguistiques.
Shōgakukan a créé la maison d'édition Shūeisha en 1925, qui a elle-même créé ensuite Hakusensha en 1973. Ces entreprises, désormais indépendantes, forment aujourd'hui, avec une dizaine d'autres maisons d'édition, le keiretsu Hitotsubashi, l'un des plus grands acteurs du marché de l'édition au Japon.`, link: `https://fr.wikipedia.org/wiki/Sh%C5%8Dgakukan`},
    {nom: "Shueisha", image: "../img/editeurs/Shueisha.jpg", historique: `Shūeisha Inc. (株式会社集英社, Kabushiki gaisha Shūeisha?) est une maison d'édition japonaise fondée en 1925 publiant principalement des magazines consacrés aux mangas. Elle possède notamment les magazines Weekly Shōnen Jump, magazine de prépublication de manga le plus populaire au monde avec ses séries telles que Black Clover, Dragon Ball, Naruto ou One Piece, mais également les magazines Monthly Shōnen Jump, Ultra Jump, Weekly Young Jump, Ribon et You.
Shūeisha décerne chaque année le Prix Tezuka et le Prix Akatsuka. Son importance sur le marché est d'environ 139,9 milliards de yens (± 1,15 milliard d'euros) et son effectif éditorial est de 749 personnes.`, link: `https://fr.wikipedia.org/wiki/Sh%C5%ABeisha`},
    {nom: "Shufu to Seikatsu Sha", image: "../img/editeurs/ShufutoSeikatsuSha.jpg", historique: `Shufu to Seikatsu Sha Co., Ltd. est une société d'édition dont le siège est à Taito -ku , Tokyo , Japon .
La société édite des magazines tels que l' hebdomadaire féminin pionnier « Shukan Josei », le magazine masculin « LEON » et le magazine de divertissement « JUNON », ainsi que des médias en ligne tels que le site d'actualités « Shukan Josei PRIME ».`, link: `https://ja.wikipedia.org/wiki/%E4%B8%BB%E5%A9%A6%E3%81%A8%E7%94%9F%E6%B4%BB%E7%A4%BE`},
// T
    {nom: "Taifu Comics", image: "../img/editeurs/TaifuComics.jpg", historique: `Taifu Comics est une maison d'édition de manga française créée en 2004. C'est une marque commerciale de la société Euphor. Taifu Comics est créé en 2004 par les fondateurs de la Japan Expo et Yves Huchez ; au départ l'éditeur s'appelle Punch Comics mais change rapidement de nom pour Taifu Comics à cause d'un litige avec une autre maison d'édition portant un nom similaire. Les titres de lancement de l'éditeur sont GO And GO de Takao Koyano, No-bra de Kenjiro Kawatsu, et Gonta ! de Katsutoshi Morita et Tarô Nami, tous trois publiés à partir du 15 Décembre 2004. Fin 2006, Yves Huchez devient l'unique dirigeant.
À partir de février 2012, Taifu Comics cesse d'être un éditeur généraliste et se spécialise dans les titres pour adultes, c'est-à-dire en Boys Love/yaoi (principalement), yuri et hentai. Euphor crée un nouvel éditeur Ototo se chargeant de commercialiser les nouvelles acquisitions de mangas de type Shōnen, Shōjo et Seinen.`, link: `https://fr.wikipedia.org/wiki/Taifu_Comics`},
    // {nom: "", image: "../img/editeurs/.jpg", historique: ``, link: ``},
    // {nom: "", image: "../img/editeurs/.jpg", historique: ``, link: ``},
];

const studios = [ // ---------------------------------------- Studios -----------------------------------------------------------------
// A 
    {nom: "A-1 Pictures", image: "../img/studios/A-1Pictures.jpg", historique: `A-1 Pictures Inc. (株式会社エー・ワン・ピクチャーズ, Kabushiki gaisha Ē Wan Pikuchāzu?) est un studio d'animation japonaise, filiale d'Aniplex, fondé en mai 2005.`, link: `https://fr.wikipedia.org/wiki/A-1_Pictures`},
    {nom: "A.C.G.T.", image: "../img/studios/ACGT.jpg", historique: `A.C.G.T (エー・シー・ジー・ティー(A·C·G·T)?) est un studio d'animation japonais fondé le 19 décembre 2000. Le studio a participé à de nombreux développements, principalement en collaboration avec d'autres studios et adapte principalement des œuvres tirées de visual novel.
C'est une filiale d'OB Planning. A.C.G.T travaille régulièrement avec Genco, qui est généralement le producteur exécutif alors qu'A.C.G.T complète la production anime.`, link: `https://fr.wikipedia.org/wiki/A.C.G.T`},
    {nom: "Asahi Production", image: "../img/studios/AsahiProduction.jpg", historique: `Asahi Production a été fondée en 1973 et s'est initialement établie comme studio de tournage spécialisé et société de production de films promotionnels. À ses débuts, Sunrise Inc. (aujourd'hui intégrée à Bandai Namco Filmworks ) et Tokyo Movie Shinsha (aujourd'hui TMS Entertainment ) étaient ses premières filiales. La production de vidéos promotionnelles pour de grandes entreprises et des organisations sectorielles, telles que l'Association japonaise des assurances et Asahi Chemical, constituait l'activité principale du studio.`, link: `https://en.wikipedia.org/wiki/Asahi_Production`},
    {nom: "asread", image: "../img/studios/asread.jpg", historique: `Asread Co., Ltd (株式会社アスリード, Kabushiki-gaisha Asurīdo ) stylisé comme asread. est un studio d'animation japonais fondé en novembre 2003 par d'anciens membres de Xebec `, link: `https://en.wikipedia.org/wiki/Asread`},
// C
    {nom: "CLOUDHEARTS", image: "../img/studios/CLOUDHEARTS.jpg", historique: `Cloud Hearts Co., Ltd. ( japonais :株式会社クラウドハーツ, Hepburn : Kabushiki-gaisha Cloud Hearts ) était un studio d'animation japonais basé à Suginami , Tokyo. Le studio existait initialement comme une branche de Yokohama Animation Lab au milieu des années 2010, sous le nom de « YAL/CHst » (acronyme de « Yokohama Animation Lab / CloudHearts studio »), avant d'être officiellement constitué en entité juridique distincte (tout en restant au sein du groupe du studio) le 1er juin 2021 par le producteur Satoshi Nakatani. Depuis mai 2024, le studio a été radié de la cote de sa société mère en raison de sa fermeture apparente. Le 18 décembre 2024, la société a officiellement entamé une procédure de faillite.`, link: `https://en.wikipedia.org/wiki/Cloud_Hearts`},
    {nom: "CloverWorks", image: "../img/studios/CloverWorks.jpg", historique: `CloverWorks, Inc. (japonais :株式会社CloverWorks , Hepburn : Kabushiki-gaisha KurōbāWākusu) est un studio d'animation japonais , anciennement Kōenji Studio (A-1 Pictures). Il s'agit d'une filiale d' Aniplex, société de production d'anime appartenant à Sony Music Entertainment Japan.`, link: `https://en.wikipedia.org/wiki/CloverWorks`},
    {nom: "CompTown", image: "../img/studios/CompTown.jpg", historique: `Aucune information`, link: `https://www.nautiljon.com/societes/comptown,24740.html`},
// D
    {nom: "Déclic Images", image: "../img/studios/DéclicImages.jpg", historique: `Déclic Images est une entreprise de traduction-vente d'anime dans les pays francophones, créée en 1999 et disparue en 2012.`, link: `https://fr.wikipedia.org/wiki/D%C3%A9clic_Images`},
// E
    {nom: "Egg Firm", image: "../img/studios/EggFirm.jpg", historique: `Egg Firm, Inc. ( en japonais :株式会社EGG FIRM , Hepburn : Eggu Fāmu ) est une société japonaise spécialisée dans la production, la planification et la gestion d' anime . C'est une filiale à 100 % d' Aniplex .`, link: `https://en.wikipedia.org/wiki/Egg_Firm`},
// G
    {nom: "Geek Toys", image: "../img/studios/GeekToys.jpg", historique: `Geek Toys, Inc. ( japonais :株式会社ギークトイズ, Hepburn : Kabushiki-gaisha Gīku Toizu ) était un studio d'animation japonais basé à Nakano, Tokyo . Le studio a été fondé à South Kōenji , Tokyo en octobre 2017 par Tamotsu Kosano, au service d'une filiale de la société japonaise de médias Geek Pictures , avant de déménager à Nakano, Tokyo en février 2020.
Le 3 juillet 2023, Geek Toys a annoncé sa fusion avec sa société mère, Geek Pictures, le 1er juillet de la même année, Geek Pictures restant la société survivante tout en héritant des activités, droits et obligations de Geek Toys.`, link: `https://en.wikipedia.org/wiki/Geek_Toys`},
    {nom: "Graphinica", image: "../img/studios/Graphinica.jpg", historique: `Graphinica Co., Ltd. ( japonais :株式会社​Graphinica , Hepburn : Kabushiki-gaisha Gurafinika ) , est un studio d'animation japonais fondé en avril 2009, axé sur l'animation 3DCG et 2D. La société a été créée le 30 avril 2009, après que le studio Gonzo ait décidé de vendre sa division vidéo numérique à Q-TEC, qui a ensuite créé la société avec les ressources acquises, ainsi que 25 employés qui travaillaient avec la société précédente qui sont ensuite devenus une partie de Graphinica, avec un total initial de 60 employés lors de sa création.`, link: `https://en.wikipedia.org/wiki/Graphinica`},
// H
    {nom: "Hoods Entertainment", image: "../img/studios/HoodsEntertainment.jpg", historique: `Hoods Entertainment inc. (フッズエンタテインメント株式会社, Fuzzu Entateinmento Kabushiki-gaisha?) est un studio d'animation japonaise fondé en février 2009. Hoods Entertainment a été fondée en février 2009 par Satoshi Nagai, qui a travaillé auparavant comme producteur pour le studio d'animation Gonzo. Les deux studios ont ainsi cohabité temporairement dans le même bâtiment à Nerima, avant que le siège social ne soit déplacé à Suginami.`, link: `https://fr.wikipedia.org/wiki/Hoods_Entertainment`},
// J
    {nom: "J.C. Staff", image: "../img/studios/J.C.Staff.jpg", historique: `J. C. Staff Co., Ltd. (株式会社ジェー・シー・スタッフ, Kabushiki gaisha Jē Shī Sutaffu?, J et C signifiant « Japan Creative ») est un studio d'animation japonaise situé à Musashino dans la préfecture de Tokyo, au Japon, fondé en janvier 1986. Il a produit un grand nombre d'anime à succès, tels Food wars! Utena, la fillette révolutionnaire, Excel Saga, Shingetsutan Tsukihime, Shakugan no Shana, Honey and Clover, Azumanga Daioh, et la franchise des A Certain Magical Index.`, link: `https://fr.wikipedia.org/wiki/J._C._Staff`},
// M
    {nom: "Madhouse", image: "../img/studios/Madhouse.jpg", historique: `Madhouse Inc. (株式会社マッドハウス, Kabushiki kaisha Maddohausu?) est un studio de films et séries d'animation japonais fondé le 17 octobre 1972 par d'anciens employés de Mushi Production dont Masao Maruyama, Osamu Dezaki et Yoshiaki Kawajiri.
La première réalisation du studio est l'adaptation en anime de Ace o Nerae! en collaboration avec TMS. Depuis lors, le studio a travaillé sur de nombreux films à succès comme Ninja Scroll, Vampire Hunter D : Bloodlust, Perfect Blue ou La traversée du temps. Il a également travaillé sur de nombreuses séries télévisées comme Sakura chasseuse de cartes, Trigun, X, Paranoia agent, Death Note, Parasite ou encore le remake de Hunter × Hunter.`, link: `https://fr.wikipedia.org/wiki/Madhouse_(studio)`},
    {nom: "MAPPA", image: "../img/studios/MAPPA.jpg", historique: `MAPPA Co., Ltd. (株式会社MAPPA, Kabushiki gaisha MAPPA?) est un studio d'animation japonaise situé à Suginami dans la préfecture de Tokyo, au Japon, fondée en juin 2011 par l'ancien fondateur du studio Madhouse, Masao Maruyama. MAPPA est l'acronyme de « Maruyama Animation Produce Project Association ». À 70 ans, Masao Maruyama fonde le studio MAPPA après avoir pris sa retraite de Madhouse en juin 2011.
En avril 2016, Maruyama a démissionné de son poste de PDG et a fondé un nouveau studio, Studio M2. Le producteur Manabu Otsuka est ainsi devenu le nouveau PDG de la société.
Le premier long métrage d'animation produit par MAPPA, sans être une série télévisée, sorti en 2016, Dans un recoin de ce monde, a remporté le prix du meilleur film d'animation de la 40e édition des Japan Academy Prize.`, link: `https://fr.wikipedia.org/wiki/MAPPA`},
    {nom: "Millepensee", image: "../img/studios/Millepensee.jpg", historique: `Millepensee, Co., Ltd. ( japonais :株式会社ミルパンセ, Hepburn : Kabushiki-gaisha Mirupanse ) est un studio d'animation japonais fondé en 2013 et basé à Nerima , Tokyo .
Le 10 février 2020, il a été annoncé que Millepensee avait formé un partenariat avec Sanzigen pour former le studio d'animation 3DCG lXlXl. Le studio a été fondé en 2013 par la productrice Naoko Shiraishi. Le réalisateur Shin Itagaki a participé à toutes les productions principales du studio depuis sa création, à l'exception des films Wake Up, Girls!! Itagaki et Shiraishi sont mariés. `, link: `https://en.wikipedia.org/wiki/Millepensee`},
// P
    {nom: "Passione", image: "../img/studios/Passione.jpg", historique: `Passione Co., Ltd. (パッショーネ株式会社, Passhōne Kabushiki-gaisha?) est une entreprise de production et studio d'animation japonaise.`, link: `https://fr.wikipedia.org/wiki/Passione_%28studio%29`},
    {nom: "P.A. Works", image: "../img/studios/P.A.Works.jpg", historique: `P.A.Works (株式会社ピーエーワークス, Kabushiki gaisha Pī Ē Wākusu?) est un studio de films et séries d'animation japonais fondé le 10 novembre 2000 et situé à Nanto dans la préfecture de Toyama au Japon. Kenji Horikawa (en), producteur et membre du bureau de direction du studio Bee Train fonde le 10 novembre 2000 le studio Koshinaka Dōga Honpo Kabushiki gaisha (越中動画本舗株式会社?) à Jōhana, aujourd'hui intégré à la municipalité de Nanto, dans la préfecture de Toyama. Le premier janvier, le studio change de nom pour Kabushiki gaisha P.A.Works (株式会社ピーエーワークス?), P.A. pour Progressive Animation. Alors que l'animation et la CG se fait dans le studio de Nanto, la production est confiée au studio de Kodaira, dans la préfecture de Tōkyō.`, link: `https://fr.wikipedia.org/wiki/P.A.Works`},
    {nom: "PINE JAM", image: "../img/studios/PINEJAM.jpg", historique: `Pine Jam Co., Ltd. (株式会社パインジャム, Kabushiki-gaisha Pain Jamu ) est un studio d'animation japonais créé le 3 juillet 2015 par l'ancien producteur de Eight Bit Kazuyoshi Mukaitouge.`, link: `https://en.wikipedia.org/wiki/Pine_Jam`},
// S
    {nom: "Science SARU", image: "../img/studios/ScienceSARU.jpg", historique: `Science SARU (株式会社サイエンスSARU, Kabushiki gaisha Saiensu SARU?) est un studio d'animation japonaise fondé le 4 février 2013 par Masaaki Yuasa et Eunyoung Choi. En 2024, le studio est racheté par le producteur et distributeur Tōhō.`, link: `https://fr.wikipedia.org/wiki/Science_SARU`},
    {nom: "SEVEN·ARCS", image: "../img/studios/SEVEN·ARCS.jpg", historique: `Seven Arcs Co., Ltd. (株式会社, Seven Arcs ; Hepburn : Kabushiki-gaisha Sebun Ākusu ) est une société de production d'anime japonaise, anciennement studio, fondée le 31 mai 2002 par d'anciens membres de Pierrot et du Studio Kikan, qui avaient créé le studio Arcturus en 2000 dans le but de produire des séries animées. Le studio a réalisé sa première série télévisée d'animation, Magical Girl Lyrical Nanoha , en 2004. Depuis, la société a produit de nombreuses autres séries télévisées et films d'animation. `, link: `https://en.wikipedia.org/wiki/Seven_Arcs`},
    {nom: "Shogakukan Music & Digital Entertainment", image: "../img/studios/ShogakukanMusic&DigitalEntertainment.jpg", historique: `Shogakukan Music & Digital Entertainment Co. , Ltd. nom : Shogakukan Music & Digital Entertainment Co., Ltd. [ 2 ] ) est une société japonaise dont le siège est à Chiyoda-ku , Tokyo , dont les principales activités comprennent la production et la vente d'enregistrements master de logiciels musicaux tels que des CD et des disques, la gestion des droits d'auteur musicaux et la planification, la production et la vente de logiciels vidéo . Il appartient au groupe Hitotsubashi . Elle est membre à part entière de la Société japonaise pour les droits des auteurs , compositeurs et éditeurs (JASRAC) et membre associé de l'Association japonaise de l'animation .`, link: `https://ja.wikipedia.org/wiki/%E5%B0%8F%E5%AD%A6%E9%A4%A8%E3%83%9F%E3%83%A5%E3%83%BC%E3%82%B8%E3%83%83%E3%82%AF%26%E3%83%87%E3%82%B8%E3%82%BF%E3%83%AB_%E3%82%A8%E3%83%B3%E3%82%BF%E3%83%86%E3%82%A4%E3%83%A1%E3%83%B3%E3%83%88`},
    {nom: "Studio Bind", image: "../img/studios/StudioBind.jpg", historique: `Studio Bind est un studio d'animation japonais fondé en novembre 2018 grâce à un investissement conjoint de WHITE FOX et d' EGG FIRM . Son président est Ōtomo Hisaya, anciennement de 8-bit, et son siège social est situé dans l'arrondissement de Suginami, à Tokyo, avec un capital social de 5 millions de yens. La société a été créée dans le but de systématiser la promotion du projet d'adaptation en anime du light novel populaire « Mushoku Tensei : Réincarnation en chômeur ». En intégrant l'expérience de production de WHITE FOX et les capacités de planification d'EGG FIRM, elle vise à établir un système de production à long terme axé sur une seule propriété intellectuelle, s'efforçant ainsi de garantir la qualité des œuvres face à la tendance à la production de masse dans l'industrie de l'animation.`, link: `https://baike.baidu.com/fr/item/Studio%20Bind/1281941`},
    {nom: "Studio Durian", image: "../img/studios/StudioDurian.jpg", historique: `Il s'agit d'une société de production d'animation japonaise fondée par Kiyotaka Oshiyama . Son siège social est situé à Suginami, dans la préfecture de Tokyo. La production des courts métrages était principalement sous-traitée à des structures comme le studio de dessin et de design personnel de Kiyotaka Oshiyama . Bien que d'autres indépendants soient parfois engagés, Oshiyama précise qu'il n'y a que deux employés : lui-même et le producteur Yuki Nagano. Il indique qu'il n'y a pas d'avancement de production et que lui et le producteur réalisent la majeure partie du travail. Il explique que, ce type de structure ne pouvant pas gérer un grand nombre de personnes, ils produisent avec une équipe réduite. C'est pourquoi la réalisation et le dessin d'Oshiyama sont essentiels. En 2024, la production du premier long métrage original , Look Back, a débuté . Conformément aux souhaits d'Oshiyama, de nombreux animateurs web ont été employés.`, link: `https://en.namu.wiki/w/%EC%8A%A4%ED%8A%9C%EB%94%94%EC%98%A4%20%EB%91%90%EB%A6%AC%EC%95%88`},
    {nom: "SUNRISE", image: "../img/studios/Sunrise.jpg", historique: `Sunrise (サンライズ, Sanraizu?) est un studio d'animation japonaise, fondé en septembre 1972 et filiale depuis 1994 de Bandai.
Le studio a produit et animé de nombreuses séries comme Nicky Larson, Vision d'Escaflowne, Cowboy Bebop, Inu-Yasha, Gintama, Code Geass mais est aussi à l'origine de la grande saga des Gundam.`, link: `https://fr.wikipedia.org/wiki/Sunrise_(studio)`},
    {nom: "Satelight", image: "../img/studios/Satelight.jpg", historique: `Le studio est fondé en décembre 1995 à Sapporo, sur l'île d'Hokkaidō. Il est à l'époque une filiale de l'entreprise d'informatique B.U.G. Le nom du studio Satelight s'explique de la façon suivante : « S » pour Sapporo, « A » pour Animate, « T » pour Technology et « E » pour Entertainement.`, link: `https://manga-encyclopedie.fandom.com/fr/wiki/Satelight`},
// T
    {nom: "Telecom Animation Film", image: "../img/studios/TelecomAnimationFilm.jpg", historique: `Kabushiki-gaisha Terekomu Animēshon Firumu ) est un studio d'animation japonais fondé le 19 mai 1975. [1] Le studio est une filiale de TMS Entertainment et est situé dans le bâtiment du siège social de la société mère.`, link: `https://wikiland.org/wiki/Telecom_Animation_Film`},
    {nom: "TMS Entertainment", image: "../img/studios/TMSEntertainment.jpg", historique: `TMS Entertainment, Ltd. , également connue sous les noms de Tōkyō Movie Shinsha et TMS-Kyokuichi Corporation, est l'un des plus anciens et des plus célèbres studios d'animation japonaise. Mondialement reconnue pour son souci du détail et la qualité de son animation, l'œuvre de TMS est très appréciée des fans et des producteurs.`, link: `https://dcau.fandom.com/wiki/TMS_Entertainment,_Ltd.`},
    {nom: "Trigger", image: "../img/studios/Trigger.jpg", historique: `Trigger Inc. (株式会社トリガー, Kabushiki gaisha Torigā?), aussi connu sous le nom Studio Trigger, est un studio d'animation japonaise situé à Suginami dans la préfecture de Tokyo, au Japon, fondé en août 2011 par des anciens membres du studio Gainax, Hiroyuki Imaishi et Masahiko Ōtsuka.`, link: `https://fr.wikipedia.org/wiki/Trigger_%28studio%29`},
// W
    {nom: "WHITE FOX", image: "../img/studios/WHITEFOX.jpg", historique: `White Fox Co., Ltd. ( japonais :株式会社WHITE FOX , Hepburn : Kabushiki-gaisha Howaito Fokkusu ) , est un studio d'animation japonais fondé en avril 2007 par Gaku Iwasa. Les productions les plus réussies du studio incluent des adaptations de Steins;Gate , Re:Zero − Starting Life in Another World et Akame ga Kill! . Le studio a été fondé en avril 2007 par Gaku Iwasa et d'autres anciens membres de la Team Iwasa d' OLM , qu'Iwasa dirigeait. Leur première production fut la série animée Tears to Tiara . Depuis, White Fox a animé des séries telles que Steins;Gate , Re:Zero et Akame ga Kill !.
Le 31 juillet 2025, il a été annoncé que le studio avait été acquis par la société d'édition japonaise AlphaPolis.`, link: `https://en.wikipedia.org/wiki/White_Fox`},
    {nom: "Wit Studio", image: "../img/studios/WitStudio.jpg", historique: `Wit Studio, Inc. ( en japonais :株式会社ウィットスタジオ, Hepburn : Kabushiki-gaisha Witto Sutajio ) , stylisé WIT Studio , est un studio d'animation japonais fondé le 1er juin 2012 par des producteurs de Production IG , en tant que filiale d' IG Port . Son siège social est situé à Musashino , à Tokyo . George Wada, producteur chez Production IG, en est le président, et Tetsuya Nakatake, également producteur chez Production IG, en est le directeur. Le studio s'est fait connaître grâce à la production de L'Attaque des Titans (les trois premières saisons), Great Pretender , Ranking of Kings , Spy × Family , Mon ami le cerf Nokotan , ainsi que des premières saisons de The Ancient Magus' Bride et de Vinland Saga .`, link: `https://en.wikipedia.org/wiki/Wit_Studio`},
// Y
    {nom: "Yokohama Animation Lab", image: "../img/studios/YokohamaAnimationLab.jpg", historique: `Yokohama Animation Laboratory ( japonais :株式会社横浜アニメーションラボ, Hepburn : Kabushiki-gaisha Yokohama Animēshon Rabo ) est un studio d'animation japonais basé à Naka-ku, Yokohama . Elle a été fondée en juillet 2015 par Yūma Ōue, ancien producteur de la division 7 de Production IG .
Le 5 septembre 2025, il a été annoncé que Yokohama Animation Laboratory avait été acquis par la société japonaise Frontier Works .`, link: `https://en.wikipedia.org/wiki/Yokohama_Animation_Laboratory`},
    // {nom: "", image: "../img/studios/.jpg", historique: ``, link: ``},
    // {nom: "", image: "../img/studios/.jpg", historique: ``, link: ``},
];

const diffusions = [ // --------------------------------------------- Plateformes de diffusion -------------------------------------------------------------------
    {nom: "ADN", image: "../img/diffusions/ADN.jpg", historique: `Animation Digital Network, abrégé ADN, anciennement Anime Digital Network, est une plate-forme de VoD et simulcast née de la fusion entre KZPlay, appartenant à Kazé, et Genzai, appartenant à Kana Home Video, ayant pour thématique la diffusion de séries et longs métrages d'animation japonaise et franco-belge.`, link: `https://fr.wikipedia.org/wiki/Animation_Digital_Network`},
    {nom: "Amazon Prime Video", image: "../img/diffusions/AmazonPrimeVideo.jpg", historique: `Prime Video (Amazon Prime Video, anciennement commercialisé sous les noms Amazon Instant Video et Amazon Video on Demand) est un service de vidéo à la demande créé par Amazon et présent dans de nombreux pays. Concurrent de Netflix, il propose des films, des séries et émissions de télévision à la location ou à l'achat. Les titres sélectionnés sont offerts gratuitement aux clients qui ont un abonnement Amazon Prime, un geste commercial qui a irrité certains consommateurs du Royaume-Uni où il a été vendu avec une augmentation non négociable de 61 % du prix de l'abonnement. Comme ses concurrents, Amazon a recherché une quantité d'offres exclusives pour différencier son service.`, link: `https://fr.wikipedia.org/wiki/Prime_Video`},
    {nom: "Crunchyroll", image: "../img/diffusions/Crunchyroll.jpg", historique: `Crunchyroll est un service de vidéo à la demande américain par abonnement appartenant à Sony Corporation. Le service distribue principalement des films et des séries télévisées produits par des médias d'Asie de l'Est, y compris des dessins animés japonais. Crunchyroll édite également des mangas et des jeux mobiles. Lancé mi-2006 par un groupe d'étudiants diplômés de l'Université de Californie à Berkeley en 2006, les services de Crunchyroll se sont progressivement développés pour compter plus de 100 millions d'utilisateurs enregistrés, répartis dans plus de 200 pays ou territoires à travers le monde, dont quatre millions d'utilisateurs abonnés.`, link: `https://fr.wikipedia.org/wiki/Crunchyroll`},
    {nom: "Netflix", image: "../img/diffusions/Netflix.jpg", historique: `Netflix est une entreprise internationale américaine active dans le secteur de l'industrie du divertissement. Fondé en 1997 à Scotts Valley (Santa Cruz) par Reed Hastings et Marc Randolph, le groupe est spécialisé dans la distribution et l'exploitation d'œuvres cinématographiques et télévisuelles, notamment par le biais d'une plateforme destinée au service de vidéo à la demande. Son siège social se situe à Los Gatos en Californie. Initialement, l'entreprise est uniquement présente dans le secteur de l'exploitation commerciale, par la fourniture d'un service en ligne de location et d'achat de DVD, livrés à domicile. Elle propose ensuite la location de ces vidéos, moyennant un abonnement mensuel. Le service de vidéo à la demande par abonnement est lancé en 2007. Depuis, l'entreprise s'est lancée dans la distribution d'un grand nombre de films et de séries télévisées ainsi que de créations originales, auxquelles elle consacre des investissements importants.`, link: `https://fr.wikipedia.org/wiki/Netflix`},
    {nom: "Sony Pictures Entertainment", image: "../img/diffusions/SonyPicturesHomeEntertainment.jpg", historique: `Sony Pictures Entertainment Inc. (SPE) est une société américaine de la Sony Corporation of America, elle-même filiale du géant japonais de l'électronique grand public Sony. Son siège social est situé à Culver City en Californie.
Les activités de Sony Pictures sont la production et la distribution de films de cinéma et de programmes télévisés en salle, à la télévision, en vidéo et sur Internet.
Le studio compte parmi ses principales franchises Spider-Man, Men in Black, ou 21 Jump Street.`, link: `https://fr.wikipedia.org/wiki/Sony_Pictures_Entertainment`},
    {nom: "Viki", image: "../img/diffusions/Viki.jpg", historique: `Rakuten Viki est un service américain de vidéo à la demande spécialisé dans le streaming de contenus asiatiques. Il diffuse des émissions, séries et films provenant de la Corée du Sud, de la Chine, du Japon, de Taïwan et de la Thaïlande, et propose également du contenu original. La plateforme permet aux utilisateurs de visionner du contenu sous-titré dans plus de 200 langues. Basée à San Mateo, en Californie, la société possède également des bureaux à Singapour, Tokyo et Séoul.`, link: `https://fr.wikipedia.org/wiki/Viki_(service_de_streaming)`},
    {nom: "YouTube", image: "../img/diffusions/Youtube.jpg", historique: `YouTube, prononcé en français [ ju.tyb] Écouterⓘ ou [ ju.tjub], est la principale plateforme de vidéos en ligne en Occident, sous forme d'application web et mobile. Les utilisateurs mettent en ligne, regardent en streaming, évaluent (avec un bouton j'aime), commentent et partagent le contenu, parfois en direct. Son site web figure dans la liste des sites web les plus visités.`, link: `https://fr.wikipedia.org/wiki/YouTube`},
    // {nom: "", image: "../img/diffusions/.jpg", historique: ``, link: ``},
    // {nom: "", image: "../img/diffusions/.jpg", historique: ``, link: ``},
    // {nom: "", image: "../img/diffusions/.jpg", historique: ``, link: ``},
];  